### ISSUE TITLE
Widgets loading + Localization

### ISSUE THREAD

**Issue by N-Molham** [Obox/layerswp#1]
Hello there,
I think you are doing a wonderful job here making that theme with that much of features and level of customization of amazing, specially open source :+1: 
Just small points to make:
- `cor/wudgets/init.php` file are loaded twice
- can you unify the localization method using the slug constant or another one like `define( 'LAYERS_TEXT_DOMAIN', 'theme-domain' );`

**Comment by marcperel** [comment]
Hey Nabeel,

Thanks for your feedback, we'll definitely check out why init loads twice.

However regarding the text domain we originally had it as a constant but we were advised to change that as it means if someone is translating the theme but not using a translator written in PHP to generate their PO file, then the text domain is ignored.

**Comment by vailjoy** [comment]
Adding documentation link for text domain for reference:
http://codex.wordpress.org/I18n_for_WordPress_Developers#Best_Practices
