### ISSUE TITLE
Feature Req: Custom CSS Framework - Bootstrap

### ISSUE THREAD

**Issue by regenrek** [Obox/layerswp#100]
Hi,

will it be possible to use bootstrap for Layers?

**Comment by marcperel** [comment]
Hi there,

For Layers we have our own framework which is tailor made for theming:

htp://docs.layerswp.com/framework/

We encourage all developers to use the framework when building for Layers

~ Marc

**Comment by vailjoy** [comment]
To be specific, you should use the Layers CSS an HTML framework. You can certainly use bootstrap js and its many plugins
