### ISSUE TITLE
Mixing PHP and JavaScript

### ISSUE THREAD

**Issue by omarabid** [Obox/layerswp#101]
I thought this is an anti-pattern and strongly discouraged?

https://github.com/Obox/layerswp/blob/master/core/widgets/modules/slider.php

**Comment by vailjoy** [comment]
Hi there,

This is primarily done for simplicity but there is likely also a technical requirement that Marc can comment to. These are the standards we follow, which speak more to format and less about implementation:
https://make.wordpress.org/core/handbook/coding-standards/php/
https://make.wordpress.org/core/handbook/coding-standards/javascript/

**Comment by marcperel** [comment]
Part of our development plan is moving scripts like this from the widget files into JS, but it's not an urgent task. 

Thanks Abid
