### ISSUE TITLE
WooCommerce CSS - Product Columns and alerts

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#103]
This standard WooCommerce shortcode has no column width:

[recent_products per_page="12" columns="4"]

The alerts are also not styled

Layers seems to de-enqueue the standard WooCommerce CSS file. Is this wise? The CSS required is:

.woocommerce ul.products li.product, .woocommerce-page ul.products li.product {
  float: left;
  margin: 0 3.8% 2.992em 0;
  padding: 0;
  position: relative;
  width: 22.05%;
}

**Comment by vailjoy** [comment]
Hi there,

Thanks for pointing this out :) I have added it to our trac. Note that full support for WooCommerce is provided via the StoreKit extension. If you are building a child theme, the above css is necessary to add to support your default column widths (by default, it is 3)

**Comment by raisonon** [comment]
Can you provide link for Storekit. IMO this should be default, especially as marketed as WC compatible Thanks.

**Comment by marcperel** [comment]
Hi @raisonon,

WooCommerce is supported by Layers in that all the WooCommerce elements are styled correctly, StoreKit adds extra functionality to Layers, better widgets and better control over items displayed in your store.

http://codecanyon.net/item/storekit-woocommerce-for-layers/11223808

~ Marc

**Comment by marcperel** [comment]
Column fix is arriving in 1.1.4 :)

**Comment by raisonon** [comment]
Ace work!
