### ISSUE TITLE
WooCommerce CSS Notices 

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#104]
Similar to https://github.com/Obox/layerswp/issues/103

As woocommerce css de-enqueued alerts are not styled:

eg. 
<div class="woocommerce-message">Message - Dummy text for this WooCommerce Notice</div>
<div class="woocommerce-info">Info - Dummy text for this WooCommerce Notice</div>
<div class="woocommerce-error">Error - Dummy text for this WooCommerce Notice</div>

**Comment by vailjoy** [comment]
Hi there,
Please see my response on #103
