### ISSUE TITLE
Issue with default table css overrides

### ISSUE THREAD

**Issue by femkhan** [Obox/layerswp#105]
Default table css overrides the datepicker css from the jquery calendar and other jquery UI. Specially the border 2px and a padding of 10 pixels.

**Comment by vailjoy** [comment]
Hello!
By default table CSS, are you referring to WordPress default CSS, or Layers CSS overriding your CSS?

**Comment by marcperel** [comment]
@vailjoy @davidperel here's an example of the issue:

http://www.aivahthemes.com/wp/dosa/reservation/

**Comment by femkhan** [comment]
Just wanted to know if there is any update on it?

**Comment by davidperel** [comment]
This fix will be included in our next update.

**Comment by marcperel** [comment]
An update on this issue, upon more investigation the border is not being added by Layers, the source is from the datepicker plugin itself:

```.iva-date-ui.ui-datepicker .ui-state-default {
  border: 2px solid #ffffff;
}```

```.iva-date-ui.ui-datepicker td span, .iva-date-ui.ui-datepicker td a {
  display: block;
  padding: 0.5em;
  text-align: center;
  text-decoration: none;
}```

**Comment by femkhan** [comment]
Figured out issue with the border from datepicker thanks Marc.
 but still if you inspect the padding still messes the layout of calendar.
