### ISSUE TITLE
Ability to Filter Layers Widget Form Controls Based on Value of Another via AJAX

### ISSUE THREAD

**Issue by d4mation-** [Obox/layerswp#106]
I'm working on extending the LayersWP Post Widget to work with Custom Post Types and Custom Taxonomies. I made it so that there was a Select Dropdown for Post Types, one for Taxonomies, and one for Terms.

I'm trying to find a way to load JavaScript into the Layers Widget Slide-Out Pane so that I can bind an On-Change event to each of the Select Dropdowns to filter the choices based on the selected Post Type or Taxonomy (For example, Posts only can see Categories, but Drinks can only see Drink Category. Having "All" chosen for Post Type would show both of them, but any choice would then filter downward). 

As far as I can tell, WordPress Core only supports loading JavaScript into the Customizer Preview Pane and using the Customizer API to hook it to the WIdget Form Controls for AJAX to alter the CSS via postmessage.

Could there be a way to add an Action Hook so that custom JavaScript could be enqueued for individual Layers Widgets in their Customization Panes? Possibly a variable hook where you include the ID of the Layers Widget in the Hook Name?

**Comment by d4mation-** [comment]
Actually, I figured out a way to get it working!

I ran the wp_enqueue_script call within the Widget Form itself instead of trying to hook into the Customizer Form and it began working. 

A custom hook would still be neat, but I suppose it isn't necessary.

**Comment by marcperel** [comment]
We'll check it out anyway, it could be nice for future dev work!

Thanks for sparking up the idea though.

**Comment by omarabid** [comment]
@d4mation- @marcperel WordPress itself has hooks for widgets. "widget-updated" and "widget-added" are the twos I'm using. They solved my problem now, but hooks/tools to use the Layers elements will be cool too.
