### ISSUE TITLE
Extend default design bar components - background

### ISSUE THREAD

**Issue by regenrek** [Obox/layerswp#107]
Hi

i managed to find a hook for extending the default  "background_component". I just want  the ability to use a pattern (list of predefined patterns) - instead of background-image or background-color without creating a new designbar or widget.

So I have come up with this code:

 ```php
function background_ext_component($args, $key, $type, $widget, $values) {

    // @TODO Fetch from JSON API
    $patterns = array(
        'pattern01.png' => 'pattern01.png',
        'pattern02.png' => 'pattern02.png',
        'pattern03.png' => 'pattern03.png',
        'pattern04.png' => 'pattern04.png',
    );

    $args['elements']['background-pattern'] = array(
            'type' => 'select-icons',
            'label' => __( 'Pattern', 'layerswp' ),
            //'button_label' => __( 'Choose Image', 'layerswp' ),
            'name' => $widget['name'] . '[background][pattern]',
            'id' => $widget['id'] . '-background-pattern',
            'value' => ( isset( $values['background']['pattern'] ) ) ? $values['background']['pattern'] : NULL,
            'options' => $patterns
    );

    return $args;
}

add_filter('layerswp_background_component_args', 'background_ext_component', 0, 5);
```

To get this working, I need to add some code in the **layers_inline_styles** function
core/helpers/template.php

```php
                // @TODO: Workaround - gets removed when updating layers...
                if( isset( $bg_args['pattern'] ) && '' != $bg_args['pattern'] ){
                    $image = get_stylesheet_directory_uri() .'/pattern/' . $bg_args['pattern'];
                    $css.= 'background-image: url(\'' . $image .'\');';
                }
```

1) It's just basic code but I don't like that its not safe for updates...

2) Is it possible to create new "types" besides the existing ones?

```
text, number, range, checkbox, select, multiselect, select-icons, textarea, tinymce, image, upload, background, color, button, trbl-fields (top, right, bottom, left), html
```

Sure I could create a new widget for that, but I think this is repetive code and I would like to hook into default widgets - this would be great.

Best Regards
Kevin

**Comment by marcperel** [comment]
If we add a line to `template.php` example adding the following to line `1082`:

`$css = apply_filters( 'layers_inline_' . $type . '_css' , $css );`

That should help you achieve what you're trying to do?

**Comment by regenrek** [comment]
Hi,

thank you for pointing this out. But for my needs I the args argument:

```php
        $css .= apply_filters( 'layers_inline_' . $type . '_css' , $css, $args );
```

or this

```php
        $css .= apply_filters( 'layers_inline_' . $type . '_css' , $css, $args[$type]);
```

The hook:
```php
function kc_inline_background_css($css, $args) {

    $bg_args = $args['background'];

    if( isset( $bg_args['pattern'] ) && '' != $bg_args['pattern'] ){
        $image = get_stylesheet_directory_uri() .'/pattern/' . $bg_args['pattern'];
        $css = 'background-image: url(\'' . $image .'\');background-repeat:repeat;background-position:top left';
    }

    return $css;

}
add_filter('layers_inline_background_css', 'kc_inline_background_css', 0, 2);
```

```php
function kc_inline_background_css($css, $args) {

    if( isset( $args['pattern'] ) && '' != $args['pattern'] ){
        $image = get_stylesheet_directory_uri() .'/pattern/' . $args['pattern'];
        $css = 'background-image: url(\'' . $image .'\');background-repeat:repeat;background-position:top left';
    }

    return $css;
}
add_filter('layers_inline_background_css', 'kc_inline_background_css', 0, 2);
```

Best Regards
Kevin

**Comment by marcperel** [comment]
That looks good. Will consider including it in the update.

**Comment by regenrek** [comment]
you have to ;-D

**Comment by marcperel** [comment]
Kevin, we're adding this filter to the `css-filter` branch, we'll be merging it in for 1.1.4

**Comment by regenrek** [comment]
@marcperel  thank you very much!

**Comment by naumanahmed19** [comment]
I noticed that its added in 1.1.4 but I am not very much families to filter can you please tell me how to use it. I had posted a question about it at 
http://docs.layerswp.com/help/question/10149/inlinie-styles-are-not-generating/

can you please tell me how to use it for this code.

```
if( !empty( $widget['data_pad']['top'] ) ){
	
	layers_inline_styles( '#' . $widget_id, 'data_pad',  
							array( 
								'selectors' => array( '.media' )  ,
								'padding-top'   =>  $widget['data_pad']['top']
							 ) 
						);
}
```

**Comment by marcperel** [comment]
@naumanahmed19 You won't need to use the filter for what you're trying to achieve, you can simply do the following:

```if( !empty( $widget['data_pad']['top'] ) ){

    layers_inline_styles(
                           '#' . $widget_id, 
                            array( 
                                'selectors' => array( '.media' )  ,
                                'css' => array( 'padding-top'   =>  $widget['data_pad']['top'] . 'px' )
                             ) 
                        );
}```

**Comment by naumanahmed19** [comment]
@marcperel thanks its working fine.

**Comment by naumanahmed19** [comment]
@marcperel is there any plan to create row element.?  row which has three columns with different widgets.

**Comment by marcperel** [comment]
It's always in our mind, but implementation on the way it works now isn't straight forward so the journey may take some time.

**Comment by naumanahmed19** [comment]
I tried to make it but getting some issues I am not sure if my approach is right or not. 

I am trying to make row element simple as default content element. For this it will create sidebar locations. As we can create simple columns in content element. In row we will ask use to add new sidebar location of 3 or 4 columns. Every sidebar location will be created as footer 1, footer2.. so user can add any widget in new created location. 

Is that make sense? I tried but problem is i am not getting right column id for each column at admin form side and front end side.

**Comment by marcperel** [comment]
So we were successful in making a widget which allowed you to add sidebars like the content widget, but the challenges were:

1. Sidebars weren't updated dynamically and therefore a user had to click Save & Publish, THEN refresh the page.
2. The exporter / importer script could not deal with the sidebars correctly.

The UI is not difficult and the basic registration too, it's getting the whole process to be dynamic and tie in easily.

~ Marc

**Comment by naumanahmed19** [comment]
Marc sorry for disturbing you again

this code works fine for 'color' property
```
if( !empty( $column['icon_color'] ) ) layers_inline_styles( '#' . $widget_id . '-' . $column_key , 'color', array( 'selectors' => array( '.service_widgt span' ) , 'color' =>  $column['icon_color']  ) );
```
but for background color it does not work. 
```
if( !empty( $column['icon_bg'] ) ) layers_inline_styles( '#' . $widget_id . '-' . $column_key , 'background',array( 'selectors' => array( '.service_widgt span' ) , 'background' =>  $column['icon_bg']  ) );
```			
i can see rule in firebug
```
#layers-widget-clinix_column_service-3-157 .service_widgt span {
    background-attachment: fixed;
    background-image: url("");
    background-size: cover;
}
```	.
I also tried background-color but its not working

**Comment by naumanahmed19** [comment]
got it fixed  :)
