### ISSUE TITLE
template-blog and index.php

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#109]
Is there any need for template-blog.php if the theme uses the index.php for blog archive?

**Comment by marcperel** [comment]
Hi Elliot,

Not really, it is possible to get the same effect by setting your static blog page, but some users like to have more control and that's why we have the page template

~ Marc

**Comment by raisonon** [comment]
Winner of quickest reply! Thanks. (as a minor aside - I did tweet. But is there a masonry blog template within Layers?)

**Comment by raisonon** [comment]
Forget that - have found as a widget
