### ISSUE TITLE
Blog Widget

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#110]
Trying to setup the site blog to use Masonry layout.

Have created a Layers page and added the Posts widget. Have selected the masonry option. 

There is an option to set the number of posts shown. There is no option to show all and have pagination.

Is it possible to add this option? It will be essential for all blogs.

**Comment by marcperel** [comment]
Hey Elliot,

We've maxed the choice to 100 posts per page purely because if a users chooses "All" which is '-1' in the Query WordPress gets exceptionally slow.

You can turn pagination on here:

https://www.dropbox.com/s/4tkjizbbbjpc2lb/Screenshot%202015-05-13%2011.51.38.png?dl=0

~ Marc

**Comment by raisonon** [comment]
Thanks - works well.

The option is very hidden as Chrome does not show scroll bars. It is not intuitive to scroll within the options to look for more options. You might want to fade out at the bottom or some other UX trick to indicate the user can scroll to reveal more.

See screenshot: https://www.dropbox.com/s/jinbfoppk6uxxf6/Screenshot%202015-05-13%2010.55.11.png?dl=0

**Comment by marcperel** [comment]
Thanks I've brought that up with the lads.
