### ISSUE TITLE
Using Layers for Taxonomy / Archive pages

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#111]
I am setting the site up to use Masonry blog layout. This has been achieved by creating a page and within layers selecting the posts widget.

Is there an option to apply this layout to the post categories as well? It would be good to have a layers option to determine the posts layout across the site and all archives to inherit the same layout.

**Comment by marcperel** [comment]
That's a nice idea, we'll add it to our future feature list :)

**Comment by raisonon** [comment]
Thanks - Keep us posted
