### ISSUE TITLE
Mobile menu hidden by navbar on iphone

### ISSUE THREAD

**Issue by ryanmccrary** [Obox/layerswp#112]
This is happening on multiple sites we have running layers. The mobile navigation is slightly behind the navbar such that the first link and close icon can't be seen

https://www.dropbox.com/s/i63vv2pdj80t9eo/2015-05-12%2012.25.02.png?dl=0

**Comment by d4mation-** [comment]
This is also an issue on Android (At least on 5.1 in Chrome 42.0.2311.111)

<img src="http://i.imgur.com/E1HgezH.png" width="200px">

**Comment by vailjoy** [comment]
We can confirm this on Android and IPhone when you have sticky/overlay enabled and scroll. This is an issue with CSS transform and fixed positioning, for which there is no elegant solution. What we can do is add some permanent padding to the top of the sidebar so the header is not overlapping it, but we cannot force the sidebar to sit below an overlay header. You also have the option of using custom css to make the menu full width or resetting the transform completely so it acts more like a traditional mobile drop-down. I will be writing a tutorial for that this week.

**Comment by vailjoy** [comment]
Need to also add -webkit-transform for safari

.open[class*=' off-canvas-'] {
 -webkit-transform: scale(1);
}

**Comment by newlocalmedia** [comment]
The real problem here is that the header menu (or any particular menu) is hard-coded into the mobile menu template. This should be a separate menu position, leaving the decision to the user as to which menu (if any) to assign there.

**Comment by vailjoy** [comment]
This appears to be fixed in 1.2.0. 

The header menu being called in the sidebar is a separate issue.

**Comment by d4mation-** [comment]
Doesn't seem fixed on my end. Running 1.2.0 and I've reinstalled the OS on my phone a few times since May so it definitely isn't a caching issue.

<img src="http://i.imgur.com/UEj8AW2.png" width="200px">

**Comment by Dory34** [comment]
Hi, I have a problem with the mobile navigation on template Layer Dawg: when the page scrolls if I click on the menu, it opens but behind the header bar so all buttons that are behind don't work. I'm not a developer and I don't know what should I do to correct this error, you can explain that I did not understand?
