### ISSUE TITLE
Notice when no Elements are specified for Custom Design Bar

### ISSUE THREAD

**Issue by omarabid** [Obox/layerswp#113]
If you try to do the following

```
	$this->design_bar(
					'top', // CSS Class Name
					array(
						...
					), // Widget Object
					$instance, // Widget Values
					array(
						'custom',
					), // Standard Components
					array(
						'width' => array(
							'icon-css' => 'icon-columns',
							'label' => 'Column Width',
						),
					)
				);
```

This triggers the following notice

```
Notice: Undefined index: elements in /devl/webserver/wp/wp-content/themes/layerswp/core/helpers/design-bar.php on line 142
```

Fair enough. Except when looking at the [code](https://github.com/Obox/layerswp/blob/35a14e99e02be75c1975e27609328ffb584b87b1/core/helpers/design-bar.php#L132) it doesn't seem that elements is planned to be a required thing and the filtering in line 142 (which do cause the notice) is not used anywhere.

Since I want to use the Custom bar for buttons, I suggest that I remove the notice by checking for `$args[ 'elements' ]` existence first and making sure that the filtering is taken into consideration. Let me know if that's a good fix or not.

**Comment by marcperel** [comment]
Thanks we've added a fallback for this which will be out in 1.1.4
