### ISSUE TITLE
Child Style Load Order

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#114]
Inline CSS is loaded after the child style.css file. This is bad practice (IMO) as we will want to overwrite these styles with our child theme.

Layers enqueues the child/style.css in templates.php with layers_apply_inline_styles

It was not easy to find where this was all enqueued but I have found it and written a Gist which will remove all child style.css and then re-enqueue with the style.css after the inline styles.

Have a look and perhaps if you agree with my logic you may change how this is managed in layers?

Thanks!

https://gist.github.com/raisonon/7320fb626227f7959a1c

**Comment by marcperel** [comment]
Hey Elliot,

We load the inline CSS last so that what ever a user chooses to do, that takes affect, you can read about re-ordering the CSS here: http://docs.layerswp.com/theming/ if you like.

**Comment by raisonon** [comment]
Am I missing something basic? We need to style basic elements of the site. H1, H2 etc.. Currently the inline styles are added last and therefore cascade and style these elements.

So we need to reorder and put child styles loading last.

Is the only way to do this with the gist I added?
