### ISSUE TITLE
Sitename SEO & HTML5 outline

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#115]
This should be H1 for home page and Span for other pages. Currently just H3 - not ideal SEO practice.

**Comment by vailjoy** [comment]
Hi there,

WordPress sets the standard for headings and reserves H1 for the sitename/logo. We also had an SEO expert advise on structuring headings for the broadest effect in SEO. Please refer to the following:
https://codex.wordpress.org/Designing_Headings

**Comment by raisonon** [comment]
Hi Vailjoy - I think you have made my point. The sitename/logo is currently set to H3 and not H1 - See: https://www.dropbox.com/s/7xbthln4e0fmmc3/Screenshot%202015-05-13%2013.46.37.png?dl=0

This should be H1 for the homepage..

**Comment by vailjoy** [comment]
Please see my edit. It was originally an H1, not sure what changed.

**Comment by vailjoy** [comment]
I was able to rework the structure and some headings to produce an effective HTML5 outline without it impacting the look or style of an existing site but we will need to test this against child themes and ensure the majority of our devs are not impacted before we can introduce it to the core.

**Comment by raisonon** [comment]
Hi @vailjoy - Any joy with getting this confirmed? Nearly ready to launch and need this ticked off. Cheers (and sorry to bug!)

**Comment by marcperel** [comment]
Hey Elliot,

I'd suggest using the CSS on the class name instead of the element, we don't have a confirmed date for this fix and I don't want to hold back your development.

What you can do is make your CSS work with H1 and H3s that way which ever is running, they'll both be dealt with.

~ Marc

**Comment by raisonon** [comment]
Just spotted that you have a dev branch that fixes this: https://github.com/Obox/layerswp/blob/HTML-Headings-Fix/partials/header-logo.php

I've attached my suggestions below. This is because you are supposed to have a single H1 per page. 

	<?php if('blank' != get_theme_mod('header_textcolor') ) { ?>
	        <div class="site-description">
				<?php if(is_home() || is_front_page() ) { ?>
		            <h1 class="sitename sitetitle"><a href="<?php echo home_url(); ?>"><?php echo get_bloginfo( 'title' ); ?></a></h1>
		            <h2 class="tagline"><?php echo get_bloginfo( 'description' ); ?></h2>
				<?php } else { ?>
		            <span class="sitename sitetitle"><a href="<?php echo home_url(); ?>"><?php echo get_bloginfo( 'title' ); ?></a></span>
		            <span class="tagline"><?php echo get_bloginfo( 'description' ); ?></span>
				<?php } ?>
	        </div>
	<?php } ?>

**Comment by deranda23** [comment]
Any progress on this topic? I love working with layerswp, you did an awesome job for a code-free interface. Sadly I am considering moving on because I rely on good SEO practice. Having no proper H1 and H2 titles is a non starter.

**Comment by barbarad** [comment]
It's not a code-free solution, but you can leave the section header blank and add H1 and H2 tags via the HTML tab in the editor, then style them with CSS. Do hope there's a better solution than this workaround coming soon though.

**Comment by davidperel** [comment]
Hi Everyone, I wanted to give an update here. By changing the home page sitename/logo to H1 has implications further down the page. I am doing some research on best practices, we need to be careful of wrapping every widget with an <if> which has to check what heading type was used in the previous section.

**Comment by barbarad** [comment]
Oh, please don't wrap the sitename in an H1 tag. That ties the hands of the marketing folk feeding us carefully crafted headers to be wrapped in H1 tags. Even continuing with a workaround would be better than that. A sitename H1 and another header/H1 below makes the page fail the said marketing people's SEO "audits." A solution is needed that doesn't create problems for the rest of the team, and therefor for us.

**Comment by davidperel** [comment]
Agreed, hence this problem taking a bit more time that expected

**Comment by raisonon** [comment]
@davidperel and @barbarad Not sure what the problem is. Easy to amend the sitename header as per my post in May. Best practice is to have the Brand Name as the H1 which is why I posted the amendment. If you want a custom H1 tag for the home, then you could have an option disable H1 for home or just do it the old fashioned way - use a child theme..

**Comment by davidperel** [comment]
It's the content further down the page. That hierarchy which has implications.

**Comment by lubosj** [comment]
I'm fairly new to Layers, but I really like the template and easy of use.
One thing that is major deal breaker for me now is that there are only h3 and h5 tags used.
I know that there are workarounds via text widgets, but that is not really user friendly for clients.

What about including dropdown with h1-h6 options next to each title within any widget? This way everybody could decide which heading to use where.
This would be massive improvement for SEO.

**Comment by davidperel** [comment]
Hi Everyone

Just giving you an update on this. We are about 50% complete with re-writing the HTML to be more semantic. That being said we want to give you more control over the heading tag (as recommended by a few of you) and are looking at easy ways for you to do so.

**Comment by lubosj** [comment]
Hi,
Any ETA on this?
Thanks!

**Comment by davidperel** [comment]
Cannot give exact dates but we are aiming for the end of March

On Wed, Mar 9, 2016 at 8:01 AM, Lubos Jezik <notifications@github.com>
wrote:

> Hi,
> Any ETA on this?
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Obox/layerswp/issues/115#issuecomment-194127880>.
>



-- 
Regards

David Perel
Co-founder, Obox

Twitter <http://twitter.com/obox>

**Comment by vailjoy** [comment]
While we are still discussing ways to give you more control over headings, please read through the following to understand more about how Google reads your content and how little headings matter when it comes to things like Layers pafges (vs your posts which use an H1 appropriately)

https://www.searchenginejournal.com/in-2014-how-important-is-an-h1-tag-for-seo/
http://docs.layerswp.com/doc/layers-and-seo/

**Comment by vailjoy** [comment]
Hey there,
1.5 is available for testing on the RC1 branch - please let us know what you think. Heading type select will be available in Layers Pro 1.6.
