### ISSUE TITLE
Child Theme localization (update documentation)

### ISSUE THREAD

**Issue by regenrek** [Obox/layerswp#117]
I went through the documentation (http://docs.layerswp.com/doc/how-to-translate-or-localize-layers/) to check if there is anything special to do if I want to use a custom localization in a child theme.

 1) It looks like the plugin "Codestyling localization" doesn't exists anymore http://wordpress.org/extend/plugins/codestyling-localization/ 

2) To get Wordpress recognize my  **layers-child/languages/*.mo**  folder/file, I need to add
the following in the function.php.

```php
add_action( 'after_setup_theme', 'my_custom_language' );
function my_custom_language() {
    load_child_theme_textdomain( 'layerswp', get_stylesheet_directory() . '/languages' );
}
```

This isn't an error but it should help others (maybe update the docs according to this)

Regards,
Kevin

**Comment by marcperel** [comment]
Nice, we'll leave it open for search ability.

**Comment by vailjoy** [comment]
Hi there,
Your child theme would only set a text domain to enable translation of its own text elements. You would not package language files for the Layers partent in your child theme (please contribute that to the core via pull request).

1. You can download it from the developer's website directly or use a local tool to create a po file. See https://codex.wordpress.org/Translating_WordPress

2.You are correct. Please don't do this, as it hijacks your child theme user's ability to access the core languages included in Layers.

**Comment by regenrek** [comment]
@vailjoy I usually edit my .po files with POEdit - I'm fine with this. I just thought other people should know this because the link to the plugin (in the docs) is broken.

2. Thank you for the information

Regards,
Kevin

**Comment by vailjoy** [comment]
Hi there,

I emailed the dev to ask what is going on. My guess is he did not update it since 3.9 and so now it has been removed. I have updated the doc link to point to his homepage. If you see a broken link in the future you can just click Site Feedback so it gets to me faster :)
