### ISSUE TITLE
Category Page - Titles for Posts are all H1

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#118]
Should only be one H1 per page - should be H4 or something else. The posts widget handles this correctly, but not partials/content-list.php

Screenshot: https://www.dropbox.com/s/zceof4eka9kjlem/Screenshot%202015-05-13%2014.51.02.png?dl=0

**Comment by vailjoy** [comment]
Hi there,

We are discussing this as part of your other issue, so I will close this one to keep everything on one thread. I was able to rework the structure and some headings to produce an effective HTML5 outline without it impacting the look or style of an existing site but we will need to test this against child themes and ensure the majority of our devs are not impacted before we can introduce it to the core.  I appreciate you bringing it up!

**Comment by raisonon** [comment]
Hi @vailjoy - Not sure where the duplicate is, but this item still needs resolving (as of 1.2.1).. Any update? Thanks
