### ISSUE TITLE
Category Descriptions

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#119]
Ideally these will be shown. This can be done by adding the following to the header-page-title.php:

<?php if (is_category()) echo '<div class="cat-description">' . category_description( $category_id ) .'</div>'; ?>

**Comment by marcperel** [comment]
In the `get_page_title();` function we do get the category description for categories, so if it's not pulling through it may be a bug

```} elseif( !is_page() && is_category() ) {
			$category = get_the_category();
			$title_array['title'] = $category[0]->name;
			$title_array['excerpt'] = $category[0]->description;```

**Comment by raisonon** [comment]
Aha - well mine were not coming through. I haven't done much custom tinkering to the theme so perhaps confirm if descriptions not coming through in your instance as well..

**Comment by marcperel** [comment]
Workin' over here https://www.dropbox.com/s/ptva96jzqvqf5mc/Screenshot%202015-05-13%2016.18.56.png?dl=0

**Comment by raisonon** [comment]
Looks like my bad. Not sure what happened there. I'm now showing double - so look like you are right this is being outputted already. Apologies.
