### ISSUE TITLE
Filter layers_customizer_sections not working

### ISSUE THREAD

**Issue by mahtar** [Obox/layerswp#121]
Following code should add new custom section in Customizer but it's not working.

```php
function my_layers_customizer_sections( $sections ){

    $social_media_section[ 'header-social-media' ] = array(
            'title'      => __( 'Social Media Profiles' , 'layerswp' ),
            'panel'     => 'header',
        );

    $sections = array_merge( $sections, $social_media_section );

    return $sections;
}
add_filter( 'layers_customizer_sections', 'my_layers_customizer_sections' );
```

**Comment by marcperel** [comment]
Hi there,

Have you also added the controls? Sections don't show up unless controls are present in the section.

**Comment by mahtar** [comment]
Hi, yes, controls were added but I just reviewed the code and found the issue - I wasn't returning the correct variable with new controls via layers_customizer_controls.

Thanks for quick response!
