### ISSUE TITLE
layers_post_featured_media could have a filter hook

### ISSUE THREAD

**Issue by siderlan** [Obox/layerswp#122]
Add support to a filter hook in the layers_post_featured_media function is a great way to override the post featured image.

The return of the function could be:
```return apply_filters('layers_post_featured_media', $output);```
instead of
```return $output;```

on line 431 of the core/helpers/post.php file.

**Comment by marcperel** [comment]
Nice one, maybe we'll sneak this into 1.1.4

**Comment by siderlan** [comment]
Isn't too long to a simple implementation? We are in the version 1.1.2.

**Comment by marcperel** [comment]
If you're in a rush you can sync with `develop` branch but 1.1.4 is penned in for a release tomorrow or early next week at the latest
