### ISSUE TITLE
how to create gallery 

### ISSUE THREAD

**Issue by avilac3** [Obox/layerswp#123]
hi, how can to create simple gallery in the builder.
thanks

**Comment by marcperel** [comment]
You can use the **Content Widget** to do this, just add a featured image and no text for each block, that'll do the trick.

**Comment by avilac3** [comment]
but, dont have the lightbox  :(
not it be easier to have another plugin.

**Comment by danielchicote** [comment]
Ligthbox links requires a new class in the hrefs, i think is needed a child theme for this.

**Comment by vailjoy** [comment]
Hi there,

Please also post this question to our community help:
http://docs.layerswp.com/help/

There are a few wonderful extensions that already integrate lightboxes, which you can find on CodeCanyon.
http://docs.layerswp.com/doc/what-plugins-are-compatible-with-layers/
