### ISSUE TITLE
Link to widgets on a page with Anchors

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#124]
You might want to link to an area of a page. For instance I have a contact form on the home page created using your maps and contact form widget.

Ideally we would be able to link to this section of the page.

You can do this using <a name="contact"></a> 

and then linking to /#contact

Perhaps widgets can have option to include this anchor so we can link to it? Or is there another way to link to page areas?

Thanks

**Comment by marcperel** [comment]
Hey Elliot,

This is a great addition, we'll consider adding it soon.

~ Marc

**Comment by marcperel** [comment]
Hey Elliot,

This is a nice suggestion, we'll consider including it in a future release, maybe even 1.1.4

**Comment by raisonon** [comment]
Thanks. This was more of a feature request than issue - is there a more appropriate place to post something like this or is it ok to post here?

**Comment by creativeer** [comment]
I think this is a feature that is in your Layers Pages Templates by default. Because you have a "onepager" template, but it isn't really a onepager. This would be the right purpose what raisonon means and what you communicate with your opener template, isn't it?

**Comment by marcperel** [comment]
@creativeer @raisonon it makes sense. The custom anchor points haven't made release `1.1.4` but we will include them in a future release.

@creativeer One issue with the starter is that it doesn't set your menu, so setting the anchors won't be the perfect solution just yet.
