### ISSUE TITLE
Content not 100% width in content widget

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#125]
When using the Content Widget. If choosing 12 columns It is not 100% width.

There is this CSS limiting it:

.media .excerpt {
  max-width: 745px;
}

**Comment by marcperel** [comment]
We're fixing this with `1.1.4` :)

**Comment by raisonon** [comment]
Ace. Ta

**Comment by raisonon** [comment]
This also occurs with the Blog Posts Widget excerpt. Not full width.

.section-title .excerpt {
  max-width: 745px;
}

**Comment by vailjoy** [comment]
Hi there,
This change is only in the Content Widget column content when set to 12/12 to support shortcodes. The widget excerpt itself is not changing - please use Advanced to modify it to fit your needs if desired.
