### ISSUE TITLE
Content area with just a button not working

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#126]
If I create a content widget with just button text and link then no button is shown.

I have to add some text (even if just a space) in excerpt for the button to show:

https://www.dropbox.com/s/84xfik945vrgk2n/Screenshot%202015-05-15%2018.19.06.png?dl=0

**Comment by vailjoy** [comment]
Hi there,
The columns need to get their structure from something, and the conditional logic will keep that structure from being created if you leave the content and title both blank. Hit the spacebar once in each field and it should resolve itself. Your other option is to use the Slider widget, which is more appropriate if you are trying to build a type of Call-to-Action banner.

**Comment by marcperel** [comment]
Fixed in 1.1.5 :dancer:
