### ISSUE TITLE
Issue: Customizer Defaut Settings 

### ISSUE THREAD

**Issue by naumanahmed19** [Obox/layerswp#127]
Possibly a issue for #fff color in header which make text white as well.
```
add_filter( 'layers_customizer_control_defaults', 'layers_child_customizer_defaults' );

function layers_child_customizer_defaults( $defaults ){

 $defaults = array(
       'header-background-color' => '#fff',
       
 );

 return $defaults;
}
```
I noticed it at new installation with my theme which have above function. But it works fine if I change color from color option and select #fff.

**Comment by vailjoy** [comment]
Hi there,

Your defaults should not define colors but should be setting these values to blank. Use CSS instead. That way the invert works correctly to change the text light or dark depending on the background color the user chooses. Please see the following:
http://docs.layerswp.com/theming/#customizer-controls-defaults
