### ISSUE TITLE
Issue: Map widget not  apply correct address.

### ISSUE THREAD

**Issue by webmas** [Obox/layerswp#128]
## Description of issue
When i set a map with it's address in the customizer, the live preview is ok.
I save the page but di result is showing always Wollongong on map.
If i edit the page the widget report the addres i have previously written.
Moreover the map isn't centered at the address.
![customizer](https://cloud.githubusercontent.com/assets/6018116/7662933/123a70e4-fb63-11e4-8301-770f00b4126d.jpg)
![page-online](https://cloud.githubusercontent.com/assets/6018116/7662932/1234f86c-fb63-11e4-9c08-2eb562f6c1a9.jpg)

## URL of page exhibiting the issue
http://2centesimi.net/~cvo-spazioweb/

## Web Browsers that exhibit the issue
Firefox 38, Internet explorer 10

## Error Message or Steps to Recreate
WordPress 4.2.1 italian
Layerswp 1.1.4

If in map.js I insert at line n.39  the	
			console.log(latitude);
			console.log(longitude);
 instructions the console in firefox debug report that the variables latitude and longitude are not defined.

**Comment by vailjoy** [comment]
Hi there,

We are aware of this issue and it is a limitation of the Google maps control in the Visual Customizer. As soon as we can find a viable solution that we are able to implement via Layers, we will do so ASAP!

**Comment by marcperel** [comment]
We're releasing a fix for this in 1.1.5 :)
