### ISSUE TITLE
Choose zoom level in map/contact widget

### ISSUE THREAD

**Issue by webmas** [Obox/layerswp#129]
## Description of issue
Can add choice of zoom level in the map widget and the choice for the map type with the controls position on the map.

**Comment by marcperel** [comment]
Hey Stefano,

This extension adds the kind of functionality you are looking for 

http://codecanyon.net/item/uber-google-maps-for-wordpress/10754256

~ Marc

**Comment by creativeer** [comment]
If i need a new Plugin, i see no reason to include your map widget. is this what you mean marc, cause i have your map widget included by default. maybe you can exclude this latitude thing and include the zoom level. By that way, siteorigin has also a map widget in his builder plugin, but when i include his map widget in your Layers Construct i have no option to make it fullwidth.

**Comment by marcperel** [comment]
@creativeer The plugin simply adds more functionality. The default map widget is fine for the basics, although zoom level is a nice addition we may consider in the future, thanks.
