### ISSUE TITLE
Pagination not working when using post list widget

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#130]
I can see pagination and it takes me to the correct URL but the same posts are being displayed on every page.

**Comment by creativeer** [comment]
I have the same Issues, but when i make the post arrangement to the simple list style and not the two other options (masonry and grid) then it seems to function properly. Can you confirm that raisonon?

**Comment by raisonon** [comment]
Yes, i am using masonry..

**Comment by vailjoy** [comment]
I can confirm the pagination works correctly with Masonry, It may just be an update issue in the customizer. Here is version 1.1.4 with masonry and pagination for testing:
http://vailjoy.com/layers/

**Comment by raisonon** [comment]
Yep, definitely not working and using Masonry or Grid...

https://www.dropbox.com/s/jjh1vhtcze238pl/Screenshot%202015-05-20%2011.58.12.png?dl=0

**Comment by raisonon** [comment]
Apologies for rushing you, but waiting on site live for this. Any chance I can provide you my WPE staging site info to resolve this and show you. If so, please DM here: https://twitter.com/raisononline/

**Comment by marcperel** [comment]
Elliot,

Can you please mail me on info@obox.co.za I'd like to get more details on your site setup.

Thanks,
Marc

**Comment by vailjoy** [comment]
This turned out to be an issue specifically with how pagination works on inner pages vs a homepage. It has been fixed and will be pushed with 1.1.5 :)

**Comment by marcperel** [comment]
Elliot if you're in a hurry, pull on `develop` branch, the fix is in that branch, or the `post-widget-fix` branch, that may be a better choice.

**Comment by raisonon** [comment]
Cheers! Thanks for fixing

**Comment by vailjoy** [comment]
This has been resolved in 1.2.2
