### ISSUE TITLE
Edit Layers pages throws "Not Acceptable" error

### ISSUE THREAD

**Issue by rsolvang** [Obox/layerswp#135]
Whenever I try to access/edit a Layers page, I get an "Not Acceptable" error. If I remove the "http://" in the URL and press enter, it works. This has been a persistent error since the initial release.

![skjermbilde fra 2015-05-18 11-33-17](https://cloud.githubusercontent.com/assets/1956027/7678163/39dc5234-fd52-11e4-98c8-9e3841caf3d6.png)

The sites are on shared hosting (HawkHost), and I have never experienced any problems like this before.

**Comment by vailjoy** [comment]
Hi there,

I am unable to recreate this so it does seem to be server-specific. Please ensure debug is off - you can do this by editing your wp-config.php to ensure WP_DEBUG is set to FALSE, and also ensuring phph error reporting is off. Many shared hosts enable it by default, which can cause havok with WordPress. See:
http://docs.layerswp.com/doc/troubleshooting-customizer-errors/

I am leaving this open in case our lead dev would like some more in-depth info from you on the hosting environment.

**Comment by rsolvang** [comment]
Adding the `ini_set( 'display_errors', 0 );` to wp-config.php did the trick! Thanks!

**Comment by rsolvang** [comment]
Sometimes the URL is printed not with "http://" but width "http%3A%2F%2F", and then there is no error.

**Comment by marcperel** [comment]
Can you tell where you clicked from? Did you click Edit Layout from a custom page?

That way we can debug the inconsistency.

Thanks,
Marc

**Comment by rsolvang** [comment]
It happens from anywhere (pages with Layers template, from within Layers Pages menu etc), except from Appearance > Customize. I guess because then there is no ?url=http://

**Comment by vailjoy** [comment]
Issue: Appearance > Customize appends a ?return=url-of-current-page to the customizer url whic is also what allows the X to return to whence you came. Our links into the customizer do not do this. Have you tried testing it with error reporting and WP_DEBUG set to false?

**Comment by kenreidy** [comment]
Same issue here. I also using hawkhost shared hosting.
