### ISSUE TITLE
Title consistency between blog page template and default template

### ISSUE THREAD

**Issue by avato** [Obox/layerswp#136]
Good morning.

Just want to thank you again for the brilliant work that went into this framework. I'm respecting it more and more every day.

In content-single.php file in the partials folder you have the "layers_before_single_post" on line 10 that will allow me disable showing  the title and diverting it  to a fancy one in a plugin that I'm working on. This works as expected.

In the blog page template however the template-blog.php starts with fetching the page title header, and then the header-page-title.php  already set title details, not allowing any actions to "work" the same magic with the page title for the blog page.

For consistency sake, can I ask that we add the following in the template_blog.php right at the top:

```php
<?php do_action('layers_before_blog_template'); ?>
<?php if (!isset ( $layers_page_title_shown ) ) { ?>
<?php get_template_part('partials/header','page-title'); ?>
<?php } ?>
```

This will allow developers to swing a cat at the blog page titles.

I know that one can make the changes in a child theme, but when you develop an extension you do not have the luxury of a child theme.

I'm happy to add the changes myself and try another of my up to now failed pull requests .

Complying with your rules, I just wanted to discuss it with you first.

AJ

**Comment by marcperel** [comment]
AJ you're welcome to make a PR for the issue, just make sure you PR on `develop`, if it's good to go we can merge into Develop.

**Comment by marcperel** [comment]
We've added this to the next release, thanks mate

**Comment by avato** [comment]
Thanks for the feedback.

I did not move forward on this request as I was looking at how the different taxonomies and how they handled the same.

I'm finding the framework fascinating and are currently moving all of my code groups over to the framework.

i just did not want to pepper you with stuff without looking carefully at the whole picture.

You've got a fan in me. This is really a smart system.

AJ
