### ISSUE TITLE
Feature Request: Add settings in Contact/Map widget for Google Maps API variables for Zoom, etc. 

### ISSUE THREAD

**Issue by newlocalmedia** [Obox/layerswp#139]
The zoom level for the map in the contact widget is hardcoded into the widget's Javascript assets. Ideally the map will have these variables based on parameters the user can set in the widget. A filterable function that sets the defaults would also support customization of the map in child themes.

**Comment by marcperel** [comment]
You're not the first to request the zoom feature, so we're considering including it into the next release.

**Comment by tiptronic** [comment]
Any news on this?

**Comment by marcperel** [comment]
@tiptronic Not yet, I'll keep this tab pinned and let you know once we update the widget in our development environment.

**Comment by marcperel** [comment]
Hey guys we found some space to push this with the next update :)

**Comment by tiptronic** [comment]
Very cool! Thx...
Basically I could help out from time to time - is there a list of stuff you currently work on?

**Comment by marcperel** [comment]
@tiptronic We have a Slack channel where we talk about issues that we have from time to time, if you'd like to join the Slack channel let me know.
