### ISSUE TITLE
Bugs in layers_load_template()

### ISSUE THREAD

**Issue by eliorivero** [Obox/layerswp#140]
- [ ] **Impossible to load templates in plugins when the template has the same name than one in the theme, like archive.php or single.php**

You first ask for `layers_get_template_locations()` but then, you check for the template slug first in the theme and then in the plugin. The result is that if a plugin has a template (in the plugin folder) named something like `archive.php` it will never be loaded because Layers already has an `archive.php` template and it will load it first.
The portion of code I'm referring to is this:
```php
if ( $theme_file = locate_template(  $template_slug ) ) {
	$file = $theme_file;
} elseif( !empty( $template_locations ) ) {
````

- [ ] **filter 'layers_template_' . $template uses the full path in the server**

The function ends with
```php
return apply_filters( 'layers_template_' . $template, $file );
```
add a
```php
var_dump( $template );
```
and you'll see it throws the full path for that template, thus making it impossible to attach a filter to it since the name of the filter hook will be different in different servers! it should be something like
```php
return apply_filters( 'layers_template_' . $template_slug, $file );
```
or
```php
return apply_filters( 'layers_template_' . str_replace( '.php', '', $template_slug ), $file );
```

**Comment by marcperel** [comment]
Thanks for the feedback Elio.

re: the `$template_slug` that's an inconsistency bug we'll fix, we will consider the order of the template loading. 

What type of modifications are you trying to achieve on the archive.php template?

Is it something we can achieve rather with hooks and filters?

~ Marc

**Comment by eliorivero** [comment]
Hi Marc, thanks for replying back.

I have a knowledge base plugin that loads templates for certain views. For example I use the filter `archive_template` to load a template for a custom post type archive view. But the filter `template_include` (which is applied after the  `archive_template` filter) overrides this so the archive.php template loaded is the one from the theme instead of the one in my plugin.

If that issue with filter `layers_template_$template` is solved and it's renamed to `layers_template_$template_slug` or similar, I could work around the template loading order using this filter. I tested it yesterday with my plugin and it successfully loaded the correct template for the custom post type defined in my plugin while still, also correctly, loading the archive template in theme for regular post archive views.

All the best.

**Comment by marcperel** [comment]
Elio,

Thanks for the response, how about making a Pull Request for this on `develop` branch? That way I can see your logic and consider including it into our code.

~ Marc

**Comment by eliorivero** [comment]
Hi, sorry for the late reply, I'm a little short of time these days. I'll try to do something over the weekend.

**Comment by marcperel** [comment]
Ellio,

I've been thinking about this issue and I will maintain the current working of the template extension.

The way it works now means that if you create a plugin, for example a portfolio plugin, Child Themes can override your plugin's single page with their own page styled to work with their theme.

In other words, it adds flexibility to the themers.

Thanks for bringing it up though it's an interesting debate.

~ Marc
