### ISSUE TITLE
Missing 2 options

### ISSUE THREAD

**Issue by naumanahmed19** [Obox/layerswp#142]
I think these 2 options should be in layers.

1 ) Background Fixed property for parallax effect.
2) 1 more option for layout full width and content in container.

**Comment by vailjoy** [comment]
Hello!
Using position: fixed for parallax is really not ideal and something we prefer to leave to child themes.

I am closing this as an enhancement request but it does not mean we have disregarded the feedback! #2 may be viable down the road :)

**Comment by naumanahmed19** [comment]
yes I know not a good way for parrallax but atleast core widgets have more options.

and is there any plan to create gallery type input? or you have any docs to create new input types?
