### ISSUE TITLE
Posts widget: can't edit what is being shown and author link bug

### ISSUE THREAD

**Issue by CarlosSouza** [Obox/layerswp#144]
Hi,

I'm getting some errors in version 1.1.4 with the posts widget:

- Hiding categories and publish date not working;
- The author link is broken, showing the HTML code as text:

![captura de tela 2015-05-21 as 12 52 13](https://cloud.githubusercontent.com/assets/833638/7752883/68992738-ffb8-11e4-80ee-4d03de359de5.png)

**Comment by vailjoy** [comment]
Hello!

I can confirm hide categories and date are working. Please see the test with the options unchecked here: http://vailjoy.com/layers

You can also see the author link correctly there.

1. Are you using a child theme?
2. Did you update through the Layers updater? If you downloaded Layers from here, please go to layerswp.com, redownload the production-ready zip and reinstall the theme.

**Comment by CarlosSouza** [comment]
Hello,

1 - I'm not using a child theme
2 - The Layers updater never worked for me. Installed it while I had Layers 1.1.2 and never showed anything regarding updates. So I uploaded 1.1.4 from layerswp.com and it did solved some bugs, but those remains :(

**Comment by CarlosSouza** [comment]
Figured it out: it's a problem with the Portuguese version of Wordpress. Made a fresh install in English and it worked flawlessly.
