### ISSUE TITLE
Moving Content Area to another page

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#145]
I've created a complex 6 column content area on a page. I now want to move to another page. Is this possible? Or do I need to re-create it?

Probably a #featurerequest

**Comment by webmas** [comment]
You can: Export the layout of your page, than create a new page and import that in the new page see instructions http://docs.layerswp.com/doc/backup-your-pages/#export-wordpress-content

Or you can duplicate the page and the system create a new identical page with the text (copy) added at the end of the title.

**Comment by raisonon** [comment]
Thanks
