### ISSUE TITLE
Documentation unreadable 

### ISSUE THREAD

**Issue by RomkaLTU** [Obox/layerswp#146]
Documentation absolutely not working in Firefox, in Chrome can't expand sample code text-area, lot of JS errors...

http://docs.layerswp.com/

Chrome 42.0.2311.152 m
Firefox 38.0.1

**Comment by webmas** [comment]
I already notified Marc about the error, they are working on. The problem appeared with the 38.0.1 update of Firefox

**Comment by akasham67** [comment]
I am also facing such types of problems like this image
![layerswp](https://cloud.githubusercontent.com/assets/4095794/7778699/b2998002-00ef-11e5-8ae6-5141afa5b325.JPG)

**Comment by vailjoy** [comment]
Please use the Site Feedback button to report issues with the site, we would like to keep Github for product isuses related to Layers specifically.
This was resolved this morning and was firefox specific caching issue.
