### ISSUE TITLE
Can not access documentation from any browser  

### ISSUE THREAD

**Issue by akasham67** [Obox/layerswp#147]
I can not access the documentation. I already tried in every browser but i am not able to access the documentation. In every browser it shows me like following image. 
![layerswp](https://cloud.githubusercontent.com/assets/4095794/7778735/1607a470-00f0-11e5-9f9a-c43b787ecf7f.JPG)

**Comment by vailjoy** [comment]
https://github.com/Obox/layerswp/issues/146
