### ISSUE TITLE
Bug In Layout Import and Duplicate Page 

### ISSUE THREAD

**Issue by naumanahmed19** [Obox/layerswp#148]
There is a bug in layout import/export and while duplicating page. 

My image path is 
uploads/sites/17/2015/05/5.png
uploads/sites/17/2015/05/2.png

and imported image path was (json is not exporting right paths) a

uploads/sites/17/2015/05/05.png
uploads/sites/17/2015/05/D2.png

I have uploaded (05.png and D2.png ) but not using in the page which i am trying to export

**Comment by vailjoy** [comment]
Hi there,
If you edit the page and click Add Media, then select "Images uploaded to this post", do you see both attached?
