### ISSUE TITLE
Issue: Mobile slide-in menu breaks when Header is Sticky

### ISSUE THREAD

**Issue by Stahlion** [Obox/layerswp#149]
## Description of issue
Mobile slide-in menu breaks when Header is Sticky.

## URL of page exhibiting the issue
www.mammacoach.se

## Web Browser(s) that exhibit the issue
Firefox, Chrome, Safari

## Error Message or Steps to Recreate
1. Goto site in mobile width.
2. Scroll down to have Sticky header to appear.
3. Press hamburger menu.
4. Notice that everything except the sticky header swipes to the left as intentional, leaving the sticky header to obstruct the mobile side bar with menu in it.

**Comment by vailjoy** [comment]
Hello,
First, please ensure you have the latest version of Layers installed. 
Please see this issue: https://github.com/Obox/layerswp/issues/112
