### ISSUE TITLE
TinyMCE for Content Widget

### ISSUE THREAD

**Issue by tmconnect** [Obox/layerswp#15]
I've tried to use the TinyMCE Editor in the Content Widget and get it to work by changing the type in the content.php on line 518.

At first I thought that nothing has changed, until I realized that the editor has changed. What's the reason you don't let the TinyMCE-Editor look like the standard WordPress Editor - that will be more WP-like.

I would like to see more options for formatting (e.g. text alignment). Is there any way to modify/add buttons? And for me the buttons are a much too large.

BTW: In the init.php you register the tinymce.js in the /core/widgets/js folder. But there is no tinymce.js!

Thanks for this great tool
Thomas

**Comment by marcperel** [comment]
Hey Thomas,

We actually use the Medium-style editor as our 'tinymce', here's an link:

https://github.com/daviferreira/medium-editor

That said we have not implemented it yet as we'd like to get the experience spot on, which as you can guess it's not quite there yet.

The regular TinyMCE can't be used as it does not like to be moved around the DOM, it's very difficult to get right!

~ Marc

**Comment by tmconnect** [comment]
Hi Marc,

thanks for the info.

Seems that the implementation of the Medium-Editor is still a little buggy.

1. After editing a text with some p-tags, saving the site and re-edit it I will get the plain HTML-Code in the visual editor like this
`<p>Give us a brief description of the feature that you are promoting. Try keep it short so that it is easy for people to scan your page. </p><p>Maecenas faucibus mollis interdum. Nullam quis risus eget urna mollis ornare vel eu leo. Maecenas faucibus mollis interdum. Sed posuere consectetur est at lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas faucibus mollis interdum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>` 
And this plaint text is show on the preview page.


2. I take a look at the Medium-Editor settings on their site and tried to add some buttons by changing the init call in the admin.js to this
`var editor = new MediumEditor('.editible-' + id, {
	anchorButton: true,
	anchorButtonClass: 'button',
	buttons: ['bold', 'italic', 'underline', 'anchor', 'header1', 'header2', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
});` 
But no chance to get the additional buttons - only the standard buttons are displayed.

Maybe a look into another WP plugin could help with your problems with the regular TinyMCE. The <a href="http://www.advancedcustomfields.com">Advanced Custom Fields Plugin</a> use the regular TinyMCE and within their Repeater Field the TinyMce can be reordered as well.

Because the free version of this plugin needs a premium addon for the Repeater Field and the new ACF V5 is a paid plugin I can create a test site for you where you can have a look to the function of the plugin. Please let me know If I should create a test site for you.

Cheers
Thomas
