### ISSUE TITLE
Can't find in layers documentation about "live preview method" 

### ISSUE THREAD

**Issue by alispx** [Obox/layerswp#150]
Hi,

i'm still can't find the live preview method. For example : i have checkbox control to hide footer section, if these checkbox is checked,  the PHP action is <code>remove_action( 'footer_section', 'main_footer' ); </code>. but how can i implement it in live preview? 

Thank you.

**Comment by marcperel** [comment]
Anything you do in the PHP should be visible in the live preview. The preview essentially just works with `get_theme_mod` and `get_option`, but for the preview mode it takes the information that is passed to it from the customizer form.

**Comment by alispx** [comment]
I got it, i use this hook <code>customize_preview_init</code> and the live preview works now. 

Thank you.
