### ISSUE TITLE
Duplicate Page Layout - IDs change

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#151]
If you duplicate a page layout all the widget IDs change. This makes styling pages hard work - any ideas about keeping this consistent on duplicate pages?

EG.   layers-widget-column-8-893   goes to  layers-widget-column-44-489

**Comment by marcperel** [comment]
Hey Elliot,

I've had a chat with @StuartOB and the solution we have come up with is to generate a unique class for each column that won't change across installations and page duplication, that way you know that your target element won't change.

Example:

```<div id="layers-widget-column-31-125" class="layers-masonry-column span-4  column layers-widget-column-125">```

See that the unique widget ID `31` will be dropped for constancy.

**Comment by raisonon** [comment]
That's a great idea - cheers!

**Comment by marcperel** [comment]
FYI Elliot this change has been added to the `develop` branch, you can switch and utilize it before next weeks' hotfix release.

Have a great weekend!
