### ISSUE TITLE
On smaller Screens (smaller than 770px) - Posts are not ordered correctly

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#153]
RE: Posts Widget

From the 4th onwards there is no longer equal division and the posts jump around.

Screenshot: https://www.dropbox.com/s/2viuvc8gqd216w0/Screenshot%202015-05-25%2021.41.39.png?dl=0

Screenshot: https://www.dropbox.com/s/jaofegj3ukxbz10/Screenshot%202015-05-25%2021.41.59.png?dl=0

**Comment by marcperel** [comment]
Elliot, what version are you running? The gutter should be working correctly since 1.1.2.

**Comment by raisonon** [comment]
Version: 1.1.4

**Comment by marcperel** [comment]
One more question, is that with Masonry enabled? If so, the order will not be correct since Masonry places each block as close together as possible, not necessarily maintaining order.
