### ISSUE TITLE
Posts display options dont work with list style list-list

### ISSUE THREAD

**Issue by DieTapete** [Obox/layerswp#155]
It just displays the content partial, which doesnt check the display options.
See line 222 in core/widgets/modules/post.php
``if( 'list-list' == $widget['design'][ 'liststyle' ] ) { ?>
<?php get_template_part( 'partials/content' , 'list' ); ?>
<?php } else {``

**Comment by marcperel** [comment]
Thanks for pointing this out, we'll investigate a fix, but we can't give a resolution timeline yet.

**Comment by vailjoy** [comment]
Combining with #130
