### ISSUE TITLE
Add action after partial content-single

### ISSUE THREAD

**Issue by murigama** [Obox/layerswp#156]
today there is the ```<?php do_action ('layers_before_single_title'); ?>``` Why not be the ```<? Php do_action ('layers_after_single_title'); ?>``` After the title of the single, and thus can for example insert a breadcrumb.

**Comment by marcperel** [comment]
That's a great spot, thanks Muri

**Comment by murigama** [comment]
I can do? and make a pull request.

**Comment by marcperel** [comment]
Thanks mate, we're adding a host of missing hooks  to 1.1.5
