### ISSUE TITLE
Editing Customizer for Widgets

### ISSUE THREAD

**Issue by Uranbold** [Obox/layerswp#157]
Hello,

I have experienced issue with Editing Page contents in Customizer. If 2 admin has working on Two different page on frontend Customizer. Then each page editing has conflict with each other. Our dev said Widget ID-s are actually same and this issue is come from the Parent Theme.

Also if i switch to our theme to Parent theme (Layers WP) then our theme contents are gone. We have added New Widget (Comes from Child Theme) but My Widget Contents are gone. If i check it on Theme Options are Widget content is saved but WP Sidebar like Disabled or some Historical Revision or something like is really missing.

If i released Premium Theme then it will be really pain for our customers. They require me they content has gone, Please fix it.

Thanks.

**Comment by marcperel** [comment]
Uran,

Thanks for the feedback.

Regarding two people on the Customizer, this is an issue WordPress will be fixing soon.

They're also investigating history in the customizer but we may be developing our own history / revision system for Layers.

~ Marc

**Comment by Uranbold** [comment]
Thanks @marcperel Appreciate for your quick response ;) GoodLuck.
