### ISSUE TITLE
'previewUrl' of undefined on customizer.js

### ISSUE THREAD

**Issue by bayka0216** [Obox/layerswp#158]
Hello,

I can't edit layout.
Cannot read property 'previewUrl; undefined on customizer.js line 64.
var default_url = wp.customize.previewer.previewUrl();

Please check it.

![layers-bug](https://cloud.githubusercontent.com/assets/12654984/7877354/17143cfa-0615-11e5-926f-5080f99ddd16.png)

**Comment by marcperel** [comment]
Thanks this is great feedback, what version of WordPress are you using?

**Comment by bayka0216** [comment]
wordpress 4.2.2 
layers 1.1.4

**Comment by bayka0216** [comment]
I checked console.log(wp.customize.previewer); result  "undefined"

I think layers/customizer.js load before wp/customizer js

**Comment by marcperel** [comment]
Thanks we're checking it out.

**Comment by marcperel** [comment]
@bayka0216 we're adding an `if()` statement around the function to avoid the error as it's not a breaking feature, but I'm not sure why you're getting the error specifically on the latest version of WordPress. Can you pull on `develop` branch and let us know if the issue persists?
