### ISSUE TITLE
Issue: grid bug

### ISSUE THREAD

**Issue by Stefan-Ioan** [Obox/layerswp#164]
## Description of issue
I add content widget and if I add 4 colum- first 12/12 and the others 4/12,4/12,4/12, the last is not on the same row ... (.row .span-4:nth-child(3n+4) { clear:left } )

## URL of page exhibiting the issue
Current is not on cause i guess is an issue(usability)... to avoid this issue I add in advanced>custom css: .row .span-4:nth-child(3n+4) {clear:none}.

## Solution
In my opinion, solution is to remove (.row .span-2:nth-child(6n+7), .row .span-3:nth-child(4n+5), .row .span-4:nth-child(3n+4), .row .span-6:nth-child(2n+3) {  clear: left;} ) cause span is already defined.

Sorry for my bad english, 
have a good day

**Comment by vailjoy** [comment]
This appears to be resolved in 1.2.0. Please update and let us know your results. If the issue persists, please provide a URL if possible and whether you have a child theme active or not. Please also try with all plugins disabled to verify there is no conflicting CSS loading.
