### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by llvasconcellos** [Obox/layerswp#165]
First of all, GREAT piece of software. Well done!

Just using it for about 10 minutes I've encountered some translation mistakes.
What is the procedure to fix this?
Can I fix it and send you a pull request or do you have other people in charge of this?

**Comment by vailjoy** [comment]
Hi there!

You can update the translation by loading the .po file into your own plugin or PoEdit, fixing the lines you think need fixing, then sending a pull request. :)
