### ISSUE TITLE
Font, size and other for menu

### ISSUE THREAD

**Issue by webmas** [Obox/layerswp#167]
Can add the font type, color and size choose for the menus? 
Or that is only possible using a child theme?

If i add the description to a menu' item can show that in a second line under the item in the menu'?

If a menu' item have a submenu can add a little triangle to the right side of the item?

**Comment by vailjoy** [comment]
Hi there,
For general questions or customization help, please use our Help forum here, where you might get a faster response:
http://docs.layerswp.com/help/

There is no font size option outside of Widgets in Layers, as it is designed with balanced typography from the onset. Some extensions add font-size options, but it is generally something we leave to custom CSS or child themes.
To add a triangle, you can use the :after pseudo element and a unicode triangle character.

This article explains how to enable walker and menu descriptions to a child theme with a custom header partial:
http://www.wpbeginner.com/wp-themes/how-to-add-menu-descriptions-in-your-wordpress-themes/

This article explains the :after CSS:
http://www.w3schools.com/cssref/sel_after.asp

Example:

.nav li.menu-item-has-children > a:after {
    content: "▾";
    margin-left: 5px;
}
