### ISSUE TITLE
Update to 1.1.5 and lost the content.

### ISSUE THREAD

**Issue by webmas** [Obox/layerswp#169]
Working on a test develop site WP 4.2.2 Italian, Layers 1.1.4

Before I've made the export of all installation content with the WP export function.
Updated to 1.1.5 and lost the content and the personalizations i have made to the site, i was using also a child theme.

Using the import function of previously backup didn't solve the issue.

Now i have reset the database of the wordpress to initial value using 	
WordPress Database Reset Plugin and reimported the backup but the pages correctly imported are only those where that are no Layers settings, the other pages with normal content are ok.

I've also lost the font settings.

You should double-check how the Layers settings are saved in the system.

**Comment by marcperel** [comment]
The customizer settings will be saved in the theme mods field in `wp_options`, (eg. `theme_mods_layerswp`), before you updated the theme, did you update any plugins? Did you do any theme switching at all? 

Thanks, Marc

**Comment by webmas** [comment]
The plugins where updated to latest versions, no theme switch, the fifteen is installed but not used.

**Comment by vailjoy** [comment]
Please review the following to help avoid this again in the future:
http://docs.layerswp.com/doc/backup-your-pages/
