### ISSUE TITLE
Update Swiper.js to version 3

### ISSUE THREAD

**Issue by gbonanome** [Obox/layerswp#171]
Hi all, Swiper slider has advanced from version 2 to version 3.

As far as I can see there's a lot of improvement and changes on the API (http://www.idangero.us/swiper/api/) and also the possibility to change transition effect from 'slide' to 'fade' (see http://docs.layerswp.com/help/question/8931/change-slider-effect-from-horizontal-to-fade/).

I've forked and wish to make a pull-request, but there's a problem with an option. There's no alternative to `calculateHeight` method in the API, so **Auto Height Slides** option doesn't work anymore. See http://www.idangero.us/swiper/forum/#!/general:what-is-the-new-alternative

Any help is appreciated https://github.com/gbonanome/layerswp/commits/swiper-update

**Comment by marcperel** [comment]
Thanks Gio,

We tried to implement V3 a few weeks before launch but because we could not get it spot on, we stuck with V2 until we can get a proper solution out.

I agree the fade/swipe affect change is a *really* nice feature!

**Comment by resarahman** [comment]
+1 with this... looking forward to see the swiper slider updated to v3

**Comment by tiptronic** [comment]
let me please just +1

**Comment by vailjoy** [comment]
This was done in 1.2.10
