### ISSUE TITLE
EM Font size problems with customizer

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#174]
We are adding custom CSS to manage the font size across the site.

For instance: #menu-top-menu-1 li a {font-size:2em}

The em size is different between the customizer view and the actual live view. This makes editing the site when in customizer a problem.

**Comment by vailjoy** [comment]
Hi there,
First, be sure to use REM not EM.
http://snook.ca/archives/html_and_css/font-size-with-rem

I can conirm this works with rem. For the main menu, for example, it inherits the main body font size declaration of 1.5rem.  To change the header menu font size only, I need to use the same selector the framework uses for applying font delcarations. If you use a browser inspector, you can see this as .nav-horizontal li a. So if I add
.nav-horizontal li a{font-size: 2rem;}
This will load in the customizer and stay the same in the live refresh of the homepage once published.

A good trick is checking the "Computed" tab of the CSS pane in the inspector to see how the element is getting its font size to begin with. This will tell you which selector to use or, if it is too broad, let you know that you need to drill down more specificially.

**Comment by raisonon** [comment]
Thanks Vailjoy - I'd not used REM before. Thanks for the insight. That does indeed fix this and also shows a better way of handling font-sizing. Cheers!
