### ISSUE TITLE
Adding Grid Size

### ISSUE THREAD

**Issue by Uranbold** [Obox/layerswp#177]
Hey guys, I have a simple feature request.

Why don't you guys adding full Grid combinations?
It's currently.
<pre>
4 of 12 Columns
6 of 12 Columns
8 of 12 Columns
12  of 12 Columns
</pre>
Sometimes i need a
<pre>
5 of 12 Columns
7 of 12 Columns
3 of 12 Columns
</pre>
If all Columns will added it looks like this.
<pre>
1 of 12 Columns
2 of 12 Columns
3 of 12 Columns
4 of 12 Columns
5 of 12 Columns
6 of 12 Columns
7 of 12 Columns
8 of 12 Columns
9 of 12 Columns
10 of 12 Columns
11 of 12 Columns
12 of 12 Columns.
</pre>
What do you guys think about this?

**Comment by marcperel** [comment]
Hey Uran,

What version are you running? We've added all combinations to the latest version.

~ Marc

**Comment by Uranbold** [comment]
Aah Really sorry we are not added for those our own created element.

Thanks.
