### ISSUE TITLE
Not valid displaying of tinymce input in widget controls

### ISSUE THREAD

**Issue by NGorco** [Obox/layerswp#181]
<?php echo $this->form_elements()->input(
								array(
									'type' => 'tinymce',
									'name' => $this->get_field_name( 'text' ) ,
									'id' => $this->get_field_id( 'text' ) ,
									'placeholder' => __( 'Formatted text' , 'layerswp' ),
									'value' => ( isset( $text ) ) ? $text : NULL ,
									'class' => 'layers-textarea layers-large'
								)
							); ?>

Type your text is white-coloured on white background. Also, wysiwyg input is not so usefull like wp_editor() wysiwyg. May be better to leave the old one.

**Comment by marcperel** [comment]
Hey there,

We are replacing the `tinymce` type with a new `rte` type for the next release which is a much better Text Editor for the widgets.

It's also worth noting true that TinyMCE does not work here as TinyMCE does not like to be moved around the DOM at all.

~ Marc

**Comment by vailjoy** [comment]
RTE now in 1.2.0
