### ISSUE TITLE
Menu' with too submenus

### ISSUE THREAD

**Issue by webmas** [Obox/layerswp#184]
If we have a menu' item with subitems and that subitems are near the right window border, than the submenus can go out of the window and can't be clickable.

**Comment by vailjoy** [comment]
Hello!

To reset the last sub-menu to a right-oriented position, add the following to the CSS panel in the customizer:

.nav-horizontal ul li:last-child .sub-menu{left: initial; right: 0;}

We will look into adding a permanent fix in a future update.

**Comment by vailjoy** [comment]
This is now fixed in 1.2.3
