### ISSUE TITLE
Jetpack Infinite Scroll

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#185]
Anyone been able to get Infinite Scroll working with Layers? Unsure which items to declare in support.

Ideally this can be integrated to core:

http://jetpack.me/support/infinite-scroll/

eg. 
add_theme_support( 'infinite-scroll', array(
    'container' => 'content',
    'footer' => 'page',
) );

**Comment by raisonon** [comment]
First note: Jetpack requires an ID on the container - perhaps add this in core. I've been able to render new posts but it's not serving the correct posts. Will feedback with any updates.

**Comment by marcperel** [comment]
I think it's a toss up between declaring support in the default archive pages or the widgets, it makes more sense to do it for the archive pages, if you do it for the post widget, there's a risk of the infinite scroll firing too soon and the page never ending.

**Comment by raisonon** [comment]
Did you get it to work on archive page? I could only get one post to appear at a time and it was always the same (the last) post...

**Comment by marcperel** [comment]
I haven't tried yet Elliot :)

**Comment by raisonon** [comment]
Closed as in fixed?
