### ISSUE TITLE
Incorrect Category Header Title

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#188]
See Screenshot: https://www.dropbox.com/s/09bl37qlfctxnfd/Screenshot%202015-06-17%2013.45.59.png?dl=0

Shows the incorrect header title. Using bare bones layers theme and no plugins.

Showing cat header for another category - from layers_get_page_title() in partials/header-page-title.php

**Comment by marcperel** [comment]
Thanks we'll check the logic out it's possible that the `get_category_title();` function is being interfered with by a post somwehere on the page, like the mobile sidebar for example.

**Comment by vailjoy** [comment]
I can confirm this, and it pulls the category from the first post on the loop in the archive when that post is in both the category being displayed and another category that would alphabetically come first.

**Comment by marcperel** [comment]
We're fixing this in the next version FYI @raisonon :)

**Comment by raisonon** [comment]
Ace!

**Comment by vailjoy** [comment]
This has been resolved in 1.2.2
