### ISSUE TITLE
Issue: "Posts" footer widget has some errors

### ISSUE THREAD

**Issue by molul** [Obox/layerswp#189]
## Description of issue
When configuring the posts list widget in the footer, I disable the excerpt, author, date and categories, but they're all still showing.

## URL of page exhibiting the issue
http://www.triptoy.tv/ (first column in the footer)

## Web Browser(s) that exhibit the issue
Chrome

**Comment by vailjoy** [comment]
Hi there,
I can confirm the meta checkboxes will show/hide the meta options correctly in 1.1.5. You can see this in action at http://vailjoy.com/layers/

**Comment by molul** [comment]
Weird... Anyway, I finally removed the option from my page because we have not enough news to make that section interesting. When I come back to it in the future I hope it works for me as well :)
