### ISSUE TITLE
Ahref added to Logo Element in Customizer (Styling conflict)

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#190]
In customizer the following is added in the logo element:

	<a href="http://vet.dev/" class="site-logo-link" style="display:none;"><img class="site-logo" data-size="medium"></a>

Which causes the text logo to inherit this style from framework.css:

	.site-logo-link + .site-description .sitename {
	  font-size: 1.6rem;
	}

This a element is not added when viewing the site live and I don't see why it is there. It makes it hard to keep logo the same size across customizer and live. See screenshots

Customizer: https://www.dropbox.com/s/cwdmk58o9nwz14z/Screenshot%202015-06-18%2009.42.32.png?dl=0

Live: https://www.dropbox.com/s/9dp3ftlshu6mcef/Screenshot%202015-06-18%2009.42.48.png?dl=0

**Comment by vailjoy** [comment]
This appears to have been fixed along the way
