### ISSUE TITLE
Issue: after changing the theme and changing back are all setting in layers are deleted.

### ISSUE THREAD

**Issue by Horscht** [Obox/layerswp#191]

**Comment by raisonon** [comment]
Just to confirm this occurs with me too.

**Comment by marcperel** [comment]
@Horscht  @raisonon Thanks guys, do you lose your Layers pages and widgets too? Or just the settings?

And are you changing to a non-Layers theme or a child theme?

**Comment by raisonon** [comment]
Changed from my child to layerswp and back.

**Comment by marcperel** [comment]
Okay thanks @raisonon, in theory this function should keep the widgets:

https://github.com/Obox/layerswp/blob/master/core/widgets/init.php#L91

... but I'll run some test I have a block of time I can dedicate to the tests now.

**Comment by marcperel** [comment]
@raisonon Are you switching in the customizer or in `/wp-admin/themes.php`

**Comment by marcperel** [comment]
Reason I'm asking is because I'm doing a straight switch via `/wp-admin/themes.php` and not losing my settings or widgets, these are my switches:

* Layers Child Theme > Layers
* Layers Child Theme > Layers > Layers Child Theme
* Layers Child Theme > Layers > Twenty Fifteeen > Layers
* Layers > Twenty Fifteen > Layers Child Theme
* Layers > Twenty Fifteen > Layers

**Comment by raisonon** [comment]
Using /wp-admin/themes.php

- Home page populated with Widgets
- Change from Layers Child > Layers
- Reload home page and see it is empty
- Change from Layers > Layers Child
- Reload home page and still empty.

**Comment by raisonon** [comment]
I have a custom sidebar... Might be related: https://www.dropbox.com/s/jojiw7vvms4jdfv/Screenshot%202015-06-19%2012.31.22.png?dl=0

**Comment by marcperel** [comment]
Custom sidebar in the Child theme? That could very well be related!

**Comment by meleshin** [comment]
If layers or child theme is activated while extended widget (plugin) is non activated or crashed then content is lost.
I use my widget (extension plugin) and child theme. To reproduce this:
1) Add my widget with some content
2) Deactivate plugin
3) Change from child theme to Layers or from Layers to child or from Layers to Twenty Fifteen and revert or from child to Twenty Fifteen and revert etc.
4) Activate plugin - widget and data not revert

**Comment by vailjoy** [comment]
Ref: https://github.com/Obox/layerswp/issues/215

**Comment by vailjoy** [comment]
This has been resolved, as far as Layers can control, with the revision functionality added in 1.2.11.
