### ISSUE TITLE
max-width is too small for content widget .section-title and .excerpt 

### ISSUE THREAD

**Issue by newlocalmedia** [Obox/layerswp#192]
Layers' content widget's primary section header and description (.section-title .excerpt at framework.css:612) are restricted to a max-width significantly less than their container (e.g. 745px versus 1024px in the desktop view) as well as the container for any columns that appear below it. 

This results in the section header always having a large blank spot on its right or left side if it's left-aligned or fully justified, especially if the font size is smaller. Only centered text really looks right there, and the default is left alignment. 

The section title and excerpt max-width probably should be matched to that of its container or simply not specified.

**Comment by vailjoy** [comment]
Hi there,

Layers is designed mobile-first, so this is to ensure maximum readability for the font size selections in the title and description (ie if you choose small text, it can result in a very wide column of one or two sentences that does not look good).

You can customize this easily using the Advanced option on the design bar.
