### ISSUE TITLE
Issue:  Tag links not working

### ISSUE THREAD

**Issue by MacGreenbear** [Obox/layerswp#193]
## Description of issue
On single posts, the assigned tags don't link...in fact, the href is simply blank.

**Comment by MacGreenbear** [comment]
On line 75 of post.php (core > helpers) replacing get_category_link( $tag->term_id ) with get_term_link( $tag ) works...please update this in the next iteration.

**Comment by marcperel** [comment]
Thanks @MacGreenbear we've fixed it for the next release have a great weekend!
