### ISSUE TITLE
Submenu hook

### ISSUE THREAD

**Issue by iammathews** [Obox/layerswp#194]
In the process of creating an extension for Layers, but it seems I cannot or am struggling to add a submenu page to the Layers admin menu.

It would be easier having a dedicated hook for this, something like: https://www.gravityhelp.com/documentation/article/gform_addon_navigation/

**Comment by Spark3000** [comment]
Hey Yusri.

Do you want to have a go adding this to core and then pull requesting. Please pull request on branch 'develop'

Sean

**Comment by iammathews** [comment]
A bit hectic today here Sean, but I did manage to do it. Might want to add it to the docs, so here's how it works:

```
add_filter( 'layers_ext_menus', 'add_menu_item' );
function add_menu_item( $menu_items ) {
    $menu_items[] = array(
    	'name' 			=> 'New Submenu',
    	'label' 		=> 'New Submenu',
    	'callback' 		=> 'submenu_handler'
    );
    return $menu_items;
}

function submenu_handler(){
	echo 'New Submenu page!';
}
```

You add that to your plugins functions.php

**Comment by vailjoy** [comment]
Thank you! This has been added to our codex.
