### ISSUE TITLE
Issue: When closing mobile bar not at the top of the page, header doesn't restore to its full width

### ISSUE THREAD

**Issue by molul** [Obox/layerswp#196]
## Description of issue
I made my website as a single page and I have a problem on cellphones: when I show the right mobile bar and click a link, the page moves to the selected section, but from there, if I click the "close" button or the mobile bar button, the header doesn't restore to its full width.

This happens in www.layerswp.com as well.

It would be handy an option to close the mobile bar when clicking a link, or at least an explanation on how to do it with jQuery or whatever so I can add it as a script in the footer.

## URL of page exhibiting the issue
http://www.triptoy.tv or http://www.layerswp.com/

## Web Browser(s) that exhibit the issue
Only tested in Chrome

## Error Message or Steps to Recreate
1.- Go to www.triptoy.tv or www.layerswp.com either on a cellphone or in PC, but in PCC, zoom the page enough to see the mobile bar button.
2.- Open the mobile bar.
3.- Scroll down until the sticky header appears.
4.- Now click the "close" button. The header will not restore to its full width.

This doesn't happen if you are at the top of the screen.

**Comment by vailjoy** [comment]
Please do not open duplicate issues. See my response to https://github.com/Obox/layerswp/issues/197

**Comment by molul** [comment]
Hi! If you mean this ticket is a duplicate of #197, it's a bit tricky. The problem is very similar but it's not exactly the same. Anyway, whatever works best for you is ok for me. I guess when one of the bugs is fixed, the other one will be as well.
