### ISSUE TITLE
Issue: Mobile Sticky Header bug in Chrome

### ISSUE THREAD

**Issue by mantas-mrw** [Obox/layerswp#200]
## Description of issue
Mobile Sticky Header bug in Chrome

## URL of page exhibiting the issue
http://www.layerswp.com/

## Web Browser(s) that exhibit the issue
Google Chrome
Device screen size: max-width: 767px

## Error Message or Steps to Recreate
* Scroll down a page, that sticky header menu would appear.
* Press menu icon. Menu appears, but the header doesn’t move left and stays on the top of the menu. When you press anywhere, header instantly moves to the correct position.
* Press close menu (X). Menu stays at the same position and doesn't move back with the menu

## Attachments
I recorded a video to show the issue. It can be downloaded on the following link:
http://www.filedropper.com/stickyheaderbuglayerswp

In the following images you can see the problem:
![sticky_header_bug_layerswp_1](https://cloud.githubusercontent.com/assets/13044906/8348814/c6a4290c-1b17-11e5-8783-fae194711234.jpg)
![sticky_header_bug_layerswp_2](https://cloud.githubusercontent.com/assets/13044906/8348815/c6a54b3e-1b17-11e5-9513-7ea367601c56.jpg)

**Comment by vailjoy** [comment]
Hi there,
I am not able to recreate this since the site was updated to 1.2.0 - tested here and on an Android device - please confirm :
http://www.responsinator.com/?url=layerswp.com&device=iphone-6&orientation=portrait

**Comment by molul** [comment]
Please use Chrom in Windows. It's happening to me as well with 1.2.0.

**Comment by mantas-mrw** [comment]
Hello @vailjoy 

I am afraid the problem still exists. Your given link simulates only the size of the page, it's not simulating the web browser.

Please try to use Chrome web browser and then resize the window. As @molul said, problem still exists, even on version 1.2.0.

Thank you,
Mantas

**Comment by vailjoy** [comment]
Hi there,

I was testing on an actual Android device and not able to re-create. We have gotten the issue to occur when the header is sticky and the page is scrolled (rather than the sidebar). This is being tracked on #197
