### ISSUE TITLE
Display Posts widget always shows meta

### ISSUE THREAD

**Issue by tiptronic** [Obox/layerswp#201]
No matter what I set in the widget's settings, it always shows date, author and category.

**Comment by marcperel** [comment]
Hey @tiptronic which view are you using? List / Grid or  Masonry?

**Comment by tiptronic** [comment]
Hi @marcperel - I was using List view

**Comment by marcperel** [comment]
Thanks Andy, it's a known issue we're trying to find a fix for +1

~ Marc

**Comment by tiptronic** [comment]
Great to hear, Marc. 
A great option for this widget would be, that if no post exist, the whole wigdet (<section>) is not rendered at all...

**Comment by tiptronic** [comment]
...now when I think about my last sentence... That would be a great option for ALL widgets :) - along with a feature to only show a widget at a given date/time :)
- Would it be possible to add that kind of functionality using an extension?

**Comment by marcperel** [comment]
It's a nice option for the `Display` section, for example "hide widget when no posts"

**Comment by tiptronic** [comment]
Exactly! 
Also a date/time-setting 'show widget on tuesdays' or 'show widget in a certain date-range'...
Imo that would be useful for any widget! That way we could even define 2 sliders - one showing during the week, the other during the weekend (or so ;))

**Comment by tiptronic** [comment]
I don't want to clutter the issues section further with this... is there a place where thinks like this are discussed?

**Comment by marcperel** [comment]
Sure you can discuss issues further on our Layers Documentation site:

http://docs.layerswp.com/help/

**Comment by vailjoy** [comment]
Hi there,

The meta issue has been fixed in 1.1.5 with the exception of the List layout, which is being tracked here:
https://github.com/Obox/layerswp/issues/155
