### ISSUE TITLE
Additions to welcome screen

### ISSUE THREAD

**Issue by avato** [Obox/layerswp#202]
Good morning.

Thanks for taking my request.

I'm in the process of writing my own welcome screen After the child theme setup.

The reason for that is the fact that I have after child theme setup processes like the installation of a controller plugin, installation of a slideshow plugin. ability to import and setup demo content and all the other usual suspects.

I already wrote a hijack script that hijacks your get started screen and injects my own, but would rather take a look at a option to properly incorporate this into the current setup screen. 

Would you guys support me adding the necessary code for you in an update or would you rather me going on my own way with this?

I'm willing to contribute and look at the expansion of the following over the coming time

1. Adding of an action to add welcome screen panels.
2. Providing proper documentation for developer resources.

possible additions depending on the ability to create a proper solution.

1. installation of the tgm plugin activation script and incorporation into the welcome screen (not for core but  as a designed solution for theme developers).
2. looking at the possibility to expand the Envato updater or similar to incorporate automated updates and update messages of a Envato child theme or extension. (also a child theme/plugin addon solution for theme and plugin authors).

This is on my to do list right now, and I though I might contribute to the community, but will understand perfectly if you have other plans at this stage.

Regards

AJ

**Comment by vailjoy** [comment]
This is documented here:
http://docs.layerswp.com/theming/#onboarding-admin-pages
