### ISSUE TITLE
Poor documentations for developer

### ISSUE THREAD

**Issue by AminulBD** [Obox/layerswp#204]
Hi,

When I visited the layers docs site, then I get a very nice looking page without great contents. There is no "how to" for using layers functions or creating custom things. If found something, but they are useless to develop any extension or custom things.

I've used unyson before, the item was awesome only for their documentation. You can read the documentation.

I think you should update your documentation site to make easy to understand for developer.

Thanks!

**Comment by vailjoy** [comment]
Hi there,

On the top right is a link to help for developers. That section contains extensive developer guides for creating child themes and extensions (with code examples and demo packages to get you started), plus the Code Reference contains  all hooks and functions with examples. If looking to do something specific, you can search for that and it should point you in the right direction. Layers is a bit more extensive and complex than unyson and is not able to benefit from such a compact developer guide, but their design is certainly nice and will certainly help use improve the overall usability of our docs.

In the future if you have feedback on the websites, please use the Site Feedback link so we can manage the feedback better. Thank you!
