### ISSUE TITLE
except not showing correctly after recent update

### ISSUE THREAD

**Issue by chrisboyle-eu** [Obox/layerswp#206]
The excerpt field is not displaying properly in the content editor, appears to be hiddin and wont open when clicked upon. Tried removing Layers and replacing with a fresh copy but no difference. Have attached a screen shot to show problem.

Thanks 
Chris

![screen shot 2015-07-02 at 14 44 22](https://cloud.githubusercontent.com/assets/7769354/8478442/53e3886a-20c9-11e5-90bf-5c523e1c3b9c.png)

**Comment by marcperel** [comment]
Hey Chris,

Thanks for the message, can you open up your Console and let us know if it shows any errors?

**Comment by chrisboyle-eu** [comment]
Hi thanks for the quick reply - doesnt seem to be anything major, something about icons? 

![screen shot 2015-07-02 at 14 54 39](https://cloud.githubusercontent.com/assets/7769354/8478615/6604c9a4-20ca-11e5-8b1e-346bdf5f0ac7.png)

**Comment by marcperel** [comment]
Cool, what browser is that? Or do you have a live site we can have a look at?

**Comment by marcperel** [comment]
Nevermind, we found the url :)

**Comment by chrisboyle-eu** [comment]
No problem, can grant you access privatly if needed.

**Comment by marcperel** [comment]
marc [at] obox.co.za can you swing me those details please Chris?

**Comment by marcperel** [comment]
Want to check it out sooner rather than later.

**Comment by chrisboyle-eu** [comment]
No problem, will set you up a temp account now. Thanks Marc.

**Comment by marcperel** [comment]
I've found the issue @chrisboyle-eu, in ```bootstrap.css``` there's the following line of CSS:

```.hide {
  display: none!important;
}```

I think we may need to change the way we hide the text editor on initial load with a less specific class.

I'll see what hotfix we can push to correct the issue by tomorrow.

~ Marc

**Comment by chrisboyle-eu** [comment]
Marc, thats brilliant - thanks very much for the help and for acting on this so quickly. Much appreciated. Will await your update.

Cheers,
Chris

**Comment by marcperel** [comment]
No problem, if you're in a tight spot you can edit the source code in ```/core/helpers/forms.php``` and remove the .hide class from the ```rte``` section.

**Comment by chrisboyle-eu** [comment]
No trouble will give that a go. :-)

**Comment by marcperel** [comment]
Chris we've pushed a fix to this in `origin develop` branch:

https://github.com/Obox/layerswp/tree/develop

So if you'd like you can pull there if you want the fix before we release it tomorrow.

**Comment by chrisboyle-eu** [comment]
Awesome, Marc. Will do so now. :+1:

**Comment by chrisboyle-eu** [comment]
Working a treat - thanks again Marc. 

Best,
Chris 

![screen shot 2015-07-02 at 15 51 51](https://cloud.githubusercontent.com/assets/7769354/8479866/595f65bc-20d2-11e5-9641-caf1f99ec874.png)

**Comment by marcperel** [comment]
Oh great, pre-release testing at its finest!

**Comment by chrisboyle-eu** [comment]
Thanks man :+1:
