### ISSUE TITLE
Javascript in old content breaks customizer after upgrade

### ISSUE THREAD

**Issue by newlocalmedia** [Obox/layerswp#207]
I had some JavaScript for obfuscating emails coded into Layers' content widget, and after upgrading to the current release the widget will not open. (I'm guessing this has to do with the visual editor added to the content widget now.) Instead I get a white screen with the email link in the upper right; that's the only thing being rendered. (Mac+Firefox 38.0.5)

The offending script is stored in `widget_layers-widget-column` within the `_options` table, but this can't be directly edited without wiping all the content widgets. 

If I export the page and import it to a new page, the JavaScript is preserved. (Sanitizing imports might be helpful here.) 

Is there a way I can turn off the visual editor to edit the code? Otherwise I'll try dropping back to the previous release to clear this up.

**Comment by marcperel** [comment]
Hi Dan,

We will be releasing a hot fix today and in that fix we will allow script
tags.

For the time being don't click "Save & Publish" until we have released the
fix.

~ Marc

**Comment by newlocalmedia** [comment]
Great, thanks!

**Comment by vailjoy** [comment]
1.2.2 is now available :)
