### ISSUE TITLE
Wordpress broken after 1.2.1 update

### ISSUE THREAD

**Issue by danielchicote** [Obox/layerswp#208]
Warning: require(/home/wordpress/public_html/cms/wp-content/themes/twentyfifteen/inc/custom-header.php) [function.require]: failed to open stream: No such file or directory in /home/wordpress/public_html/cms/wp-content/themes/twentyfifteen/functions.php on line 341

Fatal error: require() [function.require]: Failed opening required '/home/wordpress/public_html/cms/wp-content/themes/twentyfifteen/inc/custom-header.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/wordpress/public_html/cms/wp-content/themes/twentyfifteen/functions.php on line 341

**Comment by marcperel** [comment]
Hi Daniel,

Interesting that the TwentyFifteen theme is throwing the error.

Can you please check the name of the LayersWP folder and make sure it's `layerswp`?

We just corrected the folder name of the update within 2mins of uploading the fix.

**Comment by danielchicote** [comment]
The theme folder name after update is "layerswp-1.2.1"

**Comment by marcperel** [comment]
Can you please change the folder name `layerswp`

**Comment by mahtar** [comment]
Same here, layers folder name changed from layerswp to layerswp-1.2.1 after update which broke my child theme.

**Comment by mahtar** [comment]
Just saw it's been corrected, cheers.

**Comment by marcperel** [comment]
Thanks @mahtar and @danielchicote we appreciate your quick notification of the issue, we're glad we fixed it too.

**Comment by danielchicote** [comment]
I have renamed the folder to "layerswp" and  the error continues

**Comment by marcperel** [comment]
@danielchicote do you have sql access?

**Comment by marcperel** [comment]
If so go to `wp_options` and change `stylesheet` and `template` to `layerswp`, it seems that your site is stuck on Twenty Fifteen which in your case is broken

**Comment by danielchicote** [comment]
Solved, just simple restore the two table fields in options table from "twentyfifteen" to "layerswp".
:)

**Comment by marcperel** [comment]
Happy @danielchicote and happy that you can have a great not a bad weekend +1

**Comment by danielchicote** [comment]
@marcperel great update, the load of the editor is very fast now and the wysiwyg looks perfect!!
