### ISSUE TITLE
An error has occurred. Please reload the page and try again. When extension puts online.

### ISSUE THREAD

**Issue by sahidhossen** [Obox/layerswp#209]
I have tested my extension and widget in my local server and its worked fine. But when I put this extension in online and customize the widget  then its send an error : <strong> An error has occurred. Please reload the page and try again.</strong> 

Can you help me to fixed this error. I do not understand the error. 

![layers_error](https://cloud.githubusercontent.com/assets/12063077/8511316/0cc6daac-2332-11e5-8aa6-022c853eaaf4.png)

**Comment by marcperel** [comment]
H @sahidhossen,

This usually means that there is an error in your plugin but the Widget interface in the customizer does not return errors so you'll need to check your code to see what error is popping up.

It's not easy to debug, some times I just used to debug inside `Appearance > Widgets`.

~ M

**Comment by sahidhossen** [comment]
Thanks @marcperel  for replay me.
 But when I am working on my localhost its work without any error. Its show only when I upload it into my host server.

**Comment by marcperel** [comment]
Alright, in your live site go to Appearance > Widgets and see if there are any errors there.

**Comment by sahidhossen** [comment]
Oh, yes their is a error. 
It says <strong>Warning: Cannot modify header information - headers already sent by........</strong>.  
Ok, I have fixed it up. Its just have some white space. 

Thanks @marcperel

**Comment by marcperel** [comment]
Oh no damn the errant white space! 

Glad you found it @sahidhossen

**Comment by woppag** [comment]
An error has occurred. Please refresh the page and try again.  layerswp pro slide insert error  ( my PHP Memory Limit 256mb  how can the error be fixed

**Comment by MonaAsghari** [comment]
Hi
 when the users submit a form in contact us page of site, this error has occured : Plese Refresh the page and try again!
