### ISSUE TITLE
Issue: Customise tabs not working in Safari

### ISSUE THREAD

**Issue by jellymint** [Obox/layerswp#211]
## Description of issue
When going to the  Customise menu from any of the links which lead there. the tabs will only work occasionally in Safari. They work without issue in Firefox or Chrome.

## URL of page exhibiting the issue
I'm working on a local server so unable to provide this.

## Web Browser(s) that exhibit the issue
Safari

**Comment by vailjoy** [comment]
Hi there,
I was able to test the current version of Layers and work through the customizer and widgets without issue in Safari on a live server, so this may be difficult to troubleshoot.
There are some design issues in the WordPress core that could exacerbate your experience in the Customizer with Safari, example:
https://core.trac.wordpress.org/ticket/31987
The Customizer is part of the WordPress interface, so you can also test this using any other theme with customizer support.
Other things to check:
Have you deactivated all plugins?
Are you using a Child Theme?
Is Layers at 1.2.1?
Has the browser cache been cleared?
