### ISSUE TITLE
Text right in footer - bug?

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#212]
Currently not aligning right

Footer.php has 
    <div class="column span-6 clearfix t-right">

Think the t-right should be .layers-t-right so it picks style from assets/admin.css line 686:

	.layers-t-right{
	    text-align: right;
	}

**Comment by vailjoy** [comment]
HI there,
It should not be using any CSS from the admin.css, which is only for the admin. All front-end css is coming from framework.css and the footer nav is right aligned using pull-right in the nav element (framework.css line 340)- this is currently working correctly. Are you trying to modify the element?
