### ISSUE TITLE
Footer span - ability to change (easily!)

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#213]
We have a 4 links in the footer. Ideally we need only a span3 on the left and span 9 on the right.

See screenshot: https://www.dropbox.com/s/qeqi9vfzpagcih2/Screenshot%202015-07-10%2015.37.02.png?dl=0

It's a bit overkill to have to duplicate the entire footer.php to achieve this. I also think most people are going to put their links in the bottom right and so it might be better to have it default 3 - 9 ratio?

p.s. text-align is not working in footer (as shown in screenshot) and created a separate ticket here: https://github.com/Obox/layerswp/issues/212

**Comment by vailjoy** [comment]
Hi there,
It is easier to change the width of the spans using CSS than it is to change the class on the element in this case. 

http://docs.layerswp.com/theming/#styling
