### ISSUE TITLE
Updating for multisite not working!

### ISSUE THREAD

**Issue by denisciumbargi** [Obox/layerswp#214]
Hi, i have a multi site and i am decided to give layers a bash with one of the child sites i created before to choose if i will use Layers overall or not.

While i am happy with the simple ways to create content and edit the layouts i just discovered while following this that my site never got updated although i have the update plugin from you guys as well...

I am missing features and fixes because of that and i am not impressed since i have bought all the official extensions as well on Envato in order to enhance my site, spent a good few quid now not to be able to be up to date with the soft.

Check this out for multisite updates please.

**Comment by marcperel** [comment]
Hi Denis,

As network admin, when you go to the update screen and click "Check Now" you're saying that Layers does not show at all?

Can I ask if the theme is network enabled?

Is the main site on the network running Layers?

Thanks
~ M

**Comment by denisciumbargi** [comment]
Hi Marc,
thanks for the reply.

As a network admin, when i want to update my themes or plugins, Layers was never there although new versions of the theme were released.

Layers it is network enabled BUT not the main theme for most of my sites. I only use Layers on one of the sites, one that i am building now in order to test Layers to see if it is good enough for the rest of the sites also when comes to features and accessibility. I do have that plugin recommended by layers to keep the theme up to date and does NOT work also :)

**Comment by denisciumbargi** [comment]
No update on this... A bit of a downer...

**Comment by marcperel** [comment]
I've managed to get the updater working on multisite installs, so it may be a configuration issue.

What is the folder name of Layers on your install? It should be `layerswp`, but don't just change it yet, that may affect your `theme_mods` :)

**Comment by denisciumbargi** [comment]
@marcperel  thanks for the reply, yes, that is the name of the install folder... but my multisite still can't see if any updates are available for the theme.

**Comment by vailjoy** [comment]
Hi there,
Please confirm you have the Layers Updater installed and activated at the network level. Updates should then show under My Sites > Network Admin > Themes
