### ISSUE TITLE
pages contents disappeared when using backup function

### ISSUE THREAD

**Issue by 2075** [Obox/layerswp#215]
when clicking backup, i received a success message, but all the customized pages lost their content. is this expected or a bug? stupid enough i tried the backup on a live page..

is there any way of getting back the content?

**Comment by marcperel** [comment]
Hey @2075,

The backup function really should not affect the page content, what it does is take your widget setup and saved it to a field in the post meta for each page.

http://marc.perel.co/Screen-Shot-2015-07-14-09-17-23.png

When you go to Layers > Layers Pages, what is shown? Do you have any pages listed?

Thanks

**Comment by 2075** [comment]
Yes, the pages are listed (and where listed there before), looks like it overwrote the pages with null – luckily I had a backup but might be inconvenient.

Due to rolling back from the backup I cannot check now, but when opening the respective pages, just no content was shown, plus the general page config was overwritten as well, like footer elements etc where all without content.

**Comment by marcperel** [comment]
It sounds like you had an issue where your "Theme Mods" were overwritten with NULL, can you let me know what plugins you have running? I'd like to investigate this issue further.

**Comment by 2075** [comment]
Antispam Bee, Version 2.6.7 
ColorKit, Version 1.0
Contact Form 7, Version 4.2.1
Layers - Updater, Version 1.0.0
StoreKit, Version 1.0
UpdraftPlus, Version 1.10.3
WooCommerce, Version 2.3.11
WooCommerce PDF Invoices & Packing Slips, Version 1.5.15
WP Super Cache, Version 1.4.4

It could be related to WP Super Cache, but as the pages where just empty, I assume the cache has been purged, otherwise the caching would have delivered old versions instead of empty ones.

I can try later tonight with a local install as well.

**Comment by marcperel** [comment]
Yeah the only one that stands out is Super Cache, but I don't think they cache the database, if they do what could have happened is that the problem was already there but you could not see it because of the db cache.

**Comment by 2075** [comment]
Hm, to me it seems more like its because the pages already existed: I created pages before, changed the template to layers template when migrating to layerswp. Eventually the backup didn't check if pages existed and overwrote contents. But this wouldn't explain the disappeared footer configs etc.

**Comment by vailjoy** [comment]
We have solved this issue, as far as what the theme can prevent, with the revisions functionality in 1.2.11
