### ISSUE TITLE
Author Page - No title for author

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#216]
As per title.

eg. http://site.dev/author/elliot/

Screenshot: https://www.dropbox.com/s/yjowpusvs1t8efv/Screenshot%202015-07-16%2010.10.22.png?dl=0

**Comment by marcperel** [comment]
Thanks @raisonon will drop this into the next hotfix, and will be available in the `origin bug-fixes-july` branch.

**Comment by vailjoy** [comment]
This has been resolved in 1.2.2
