### ISSUE TITLE
New widget doesn't update values.

### ISSUE THREAD

**Issue by NistorCristian** [Obox/layerswp#217]
I created a new Widget using this guide:
http://docs.layerswp.com/development-tutorials-layers-builder-widgets/

I only added 2 field ... Title and excerpt. But if I write something in Title and then click on excerpt the title content dissapears. Or If I click save&publish it doesn't store the values.

I have to do some Ajax or something?

Here is my Widget.

http://jsfiddle.net/Lojd7upb/

Thank you

**Comment by marcperel** [comment]
@NistorCristian have you tried to `print_r( $widget );` at all? To see what the values are.

**Comment by NistorCristian** [comment]
Yes. This is what print_r returns:
Array ( [title] => Find Us [excerpt] => We are based in one of the most beautiful places on earth. Come visit us! )
And these are the defaults.

**Comment by marcperel** [comment]
Try this:

```function update($new_instance, $old_instance) {
		return $new_instance;
}```

**Comment by marcperel** [comment]
It seems you're missing the update logic I've penne din above.

**Comment by NistorCristian** [comment]
Yes. Thank you. That was the problem.

**Comment by marcperel** [comment]
:)
