### ISSUE TITLE
RTE Editor add non breakable characters in text

### ISSUE THREAD

**Issue by creativeer** [Obox/layerswp#218]
## Description of issue

Text that is written in excerpt window gets messy (look at screenshot) with unbreakable spaces that prevent a clear break between words and they just get cut off. so this behaviour prevents a clean paragraph text or list element and so on... 

## URL of page exhibiting the issue

localhost (xampp)

## Web Browsers that exhibit the issue

all

## Error Message or Steps to Recreate

write text in one box, create a new box, change list style to normal

---

what is that?

![screenshot-text-get-messy](https://cloud.githubusercontent.com/assets/2089316/8722172/06bac1c6-2bc2-11e5-9b7b-a43fb2fe408f.jpg)

**Comment by vailjoy** [comment]
Hi there,
It looks like this content should be inside of an unordered list - the behavior is normal for how the code appears (the string of non-breaking spaces means it will run off the end and not break...)

**Comment by creativeer** [comment]
You will tell me, that it is normal that this RTE Widget include nonbreakable spaces in text and listelements? Well this is new for me... And in the previous Versions of layers without this RTE, there was no adding of non breakable spaces. And i dont give this Box then more space because what is with Responsive then? And overflow visible means i have a scroll bar under this box then? Not really Vailjoy...

**Comment by marcperel** [comment]
@creativeer have you copy and pasted this text in from an external site?

And if you click the clear formatting button do the ```&nbsp;```s remain?

**Comment by creativeer** [comment]
Hey Marc,
no it is not from an external Website. 
Just take the default text, make a list element with the rte editor and copy that to make a 2nd (or more) list elements. Now if you change these elements back to normal, you have these non breakable spaces in your text and they don't go away.
Can you recreate this behaviour?

**Comment by marcperel** [comment]
Can you drop us an export of your page which is causing the issue? That'll help a lot in terms of finding a solution

**Comment by creativeer** [comment]
i can't add the json file here, so i make a copy paste from the json here into:


{"obox-layers-builder-146":{"layers-widget-column-7":{"design":{"layout":"layout-boxed","liststyle":"list-grid","gutter":"on","fonts":{"align":"text-left","size":"medium","color":""},"background":{"image":"","color":"","repeat":"no-repeat","position":"center"},"advanced":{"customclass":"","customcss":"","padding":{"top":"","right":"","bottom":"","left":""},"margin":{"top":"","right":"","bottom":"","left":""}}},"title":"Our Services","excerpt":"Our services run deep and are backed by over ten years of experience.","column_ids":"474,376,344","columns":{"474":{"design":{"background":{"image":"","color":"","repeat":"no-repeat","position":"center"},"featuredimage":"","featuredvideo":"","imagealign":"image-top","fonts":{"align":"text-left","size":"medium","color":""}},"width":"4","title":"Your service title","excerpt":"<p>Give\u00a0us\u00a0a\u00a0brief\u00a0description\u00a0of\u00a0the\u00a0service\u00a0that\u00a0you\u00a0are\u00a0promoting.\u00a0Try\u00a0keep\u00a0it\u00a0short\u00a0so\u00a0that\u00a0it\u00a0is\u00a0easy\u00a0for\u00a0people\u00a0to\u00a0scan\u00a0your\u00a0page.<\/p><p>Give us a brief description of the service that you are promoting. Try keep it short so that it is easy for people to scan your page.<\/p>","link":"","link_text":""},"376":{"design":{"background":{"image":"","color":"","repeat":"no-repeat","position":"center"},"featuredimage":"","featuredvideo":"","imagealign":"image-top","fonts":{"align":"text-left","size":"medium","color":""}},"width":"4","title":"Your service title","excerpt":"<ul><li>Give us a brief description of the service that you are promoting. Try keep it short so that it is easy for people to scan your page.<\/li><li>Give&nbsp;us&nbsp;a&nbsp;brief&nbsp;description&nbsp;of&nbsp;the&nbsp;service&nbsp;that&nbsp;you&nbsp;are&nbsp;promoting.&nbsp;Try&nbsp;keep&nbsp;it&nbsp;short&nbsp;so&nbsp;that&nbsp;it&nbsp;is&nbsp;easy&nbsp;for&nbsp;people&nbsp;to&nbsp;scan&nbsp;your&nbsp;page.<\/li><li>Give us a brief description of the service that you are promoting. Try keep it short so that it is easy for people to scan your page.<\/li><\/ul>","link":"","link_text":""},"344":{"design":{"background":{"image":"","color":"","repeat":"no-repeat","position":"center"},"featuredimage":"","featuredvideo":"","imagealign":"image-top","fonts":{"align":"text-left","size":"medium","color":""}},"width":"4","title":"Your service title","excerpt":"<p>Give\u00a0us\u00a0a\u00a0brief\u00a0description\u00a0of\u00a0the\u00a0service\u00a0that\u00a0you\u00a0are\u00a0promoting.\u00a0Try\u00a0keep\u00a0it\u00a0short\u00a0so\u00a0that\u00a0it\u00a0is\u00a0easy\u00a0for\u00a0people\u00a0to\u00a0scan\u00a0your\u00a0page.<\/p><p>Give us a brief description of the service that you are promoting. Try keep it short so that it is easy for people to scan your page.<\/p>","link":"","link_text":""}}}}}

**Comment by marcperel** [comment]
@creativeer Can you mail it to me marc at obox.co.za
