### ISSUE TITLE
design_bar_components doesn't update

### ISSUE THREAD

**Issue by NistorCristian** [Obox/layerswp#219]
I'm trying to make a gallery widget but I'm a little stuck. I used the Content widget as an example and I modified some stuff. But now if I do a change in design_bar_components, change the color for example, and click save and publish the array changes but if I refresh the page or admin page the color becomes NULL. This problem is also If I do:
			`$this->column_defaults = array (
				'title' => __( 'Your service title', 'layerswp' ),
				'width' => '4',
				'design' => array(
					'fonts' => array(
						'align' => 'text-center',
						'size' => 'medium',
						'color' => '#0489bd',
						'shadow' => NULL
					)
				)
			);`
It doesn't get the default values. I think it gets the Content default values.

![untitled-3](https://cloud.githubusercontent.com/assets/12628663/8749416/0cfb6e8a-2caa-11e5-89cf-686d2f897d14.png)

Here is my widget:
http://jsfiddle.net/zs17p7sp/

Any help whould be nice. Thank you

**Comment by marcperel** [comment]
Try printing out the values as you go down the column_item function, it'll help you debug if the defaults are taking over or not.

```function column_item( $widget_details = array() , $column_guid = NULL , $instance = NULL ){

                // Extract Instance if it's there so that we can use the values in our inputs
echo '<pre>';
print_r( $instance );
echo '</pre>';
                // $instance Defaults
                $instance_defaults = $this->column_defaults;

                // Parse $instance
                $column = wp_parse_args( $instance, $instance_defaults );
echo '<pre>';
print_r( $column );
echo '</pre>';
                // If there is no GUID create one. There should always be one but this is a fallback
                if( ! isset( $column_guid ) ) $column_guid = rand( 1 , 1000 );

                // Turn the widget details into an object, it makes the code cleaner
                $widget_details = (object) $widget_details;```

**Comment by NistorCristian** [comment]
I print_r them and it shows correcly. I don't think the problem is inside a column. If I write inside a column it is ok. Everything works. My problem is when I change values from design_bar_components. Like Layout, Columns, Text, Advanced, etc ...

**Comment by NistorCristian** [comment]
I made a print screen with my problem. The blue arrows work the red one don't work. I print_r inside function widget  $args, $instance, $instance_defaults and $widget and everything looks ok. I think somehow the stuff inside design_bar doesn't update.
![untitled-11](https://cloud.githubusercontent.com/assets/12628663/8760805/0fb9e144-2d39-11e5-8278-f61932700017.png)

**Comment by NistorCristian** [comment]
I modified something and now it works. But I don't know why. An explination would be nice :)
I changed this:
			`$this->design_bar(`
				`'side', // CSS Class Name`
				`array(`
					`'name' => $this->get_field_name( 'design-liststyle' ),`
					`'id' => $this->get_field_id( 'design-liststyle' ),`
				`), // Widget Object`
				`$widget, // Widget Values`
				`$design_bar_components, // Standard Components`
			`);`
to this:
                        `$this->design_bar(`
				`'side', // CSS Class Name`
				`array(`
					`'name' => $this->get_field_name( 'design' ),`
					`'id' => $this->get_field_id( 'design' ),`
				`), // Widget Object`
				`$widget, // Widget Values`
				`$design_bar_components // Standard Components`
			`);`

**Comment by vailjoy** [comment]
Hi there,
The field name is design, not design-lifestyle :)
