### ISSUE TITLE
RTE custom widget issue

### ISSUE THREAD

**Issue by naumanahmed19** [Obox/layerswp#221]
I have created a plugin which is working fine I am using rte . When i click at add new column rte does not work in new column. Have you guys changed anything in content widget (content.js) in last version? because i have copied it for my custom widget

**Comment by naumanahmed19** [comment]
ok got it working with using latest version content.js.

I have one more question 

why not create a single js for both slider and content. I have created 10 custom widgets and for each i have to add custom js and its increasing load time. 

If we use a unique id for each widget and using this id as a prefix in content.js then i think it is possible.

**Comment by marcperel** [comment]
Making a generic add/remove JS function is certainly something we're wanting to do in the future thanks @naumanahmed19
