### ISSUE TITLE
Using Hosting Temporary URL throws 403 error

### ISSUE THREAD

**Issue by bart-insight** [Obox/layerswp#222]
When using the hosting provider's temporary URL (domain not pointing to new hosting yet), I receive the following error when trying to edit a page using the WPLayers page template:

*temphostingurl*.com 403 Forbidden Error Page
If you arrived here due to a search or clicking on a link click your Browser's back button to return to the previous page. Thank you.

IP Address: *my location's IP address*

If I use the 'default' template, I can edit the page fine. The site displays well, and admin displays fine, only when I try to edit a layers page do I see the error. config.php is edited to point to temp url.

**Comment by vailjoy** [comment]
If you go into the customizer from the Appearance menu, then enter Edit Layout panel, does that work? (make sure the page is set as Home or can be reached through your nav menu, has been saved once as a Draft or Published, and has a Title)

**Comment by bart-insight** [comment]
Thanks for the feedback Vailjoy, the page was set as homepage, I saved it using the default template and tried for the helluvit to reset the permalinks, then went back to try the Layers page template/builder... it worked.  Thanks for your time to follow up!
