### ISSUE TITLE
Customize > Footer > Text > Copyright Text : Add Support for HTML

### ISSUE THREAD

**Issue by virgilshelton** [Obox/layerswp#223]
When customizing a theme and adding in HTML to the Copyright Text widget only support plan text is supported. 

Steps to reproduce the issue: 

1. Login to the WordPress backend, click Layers > Customers.
2. Click Footer > Text > and insert ;copy ```<a href="http://oboxthemes.com/">Obox</a>```
3. Press Save & Publish
4. Note that HTML is stripped and only the text Obox remains in the footer.

Expected Result

1. All HTML and JavaScript should remain. 

Use Case

1. Use JavaScript to print the current year so I don't have to update this on clients sites e.g. <script>document.write(new Date().getFullYear())</script>

Comments

1. I know I could do some magic in functions.php to append a PHP date but end-users would never think of this. 

 Thanks for the sweet theme BTW!

**Comment by marcperel** [comment]
We are actually planning on allowing HTML in the next release so hang tight
:)

**Comment by molul** [comment]
Cool! I was about to ask for the same thing :D

**Comment by virgilshelton** [comment]
Thanks! I hope you guys end up getting bought by Automattic, awesome work!

**Comment by vailjoy** [comment]
This has been resolved in 1.2.2

**Comment by virgilshelton** [comment]
Verified fixed, thank you!

**Comment by marcperel** [comment]
:+1: Weekend celebrations @virgilshelton !
