### ISSUE TITLE
class removed from section on archive

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#225]
The class container used to be on the `<section>` element. Latest version has it removed.

This means we get full width without wrapper on our archive pages.. Any reason for this?

Thanks

**Comment by marcperel** [comment]
Thanks Elliot,

Hm we should have sorted that out, what type of archive is it? Maybe we
missed a case :/

**Comment by raisonon** [comment]
It was most likely a custom taxonomy... Perhaps that is why?

**Comment by mahtar** [comment]
It looks like "container" class has to be added to <section> and <div class="row"> elements in certain places to keep the content boxed. This wasn't the case in previous Layers versions so if you were overriding Layers' templates this has to be updated in your files. 
Also seems that page.php needs to be updated on the Layers side to bring it into line with the changes.

**Comment by mahtar** [comment]
@raisonon - wrap the html code in your post in `` (backticks), otherwise GitHub removes them from the live post.

**Comment by marcperel** [comment]
Hey @raisonon @mahtar 

Guys thanks for bringing this up, I knew it was a risk with this hotfix, but we had to make the changes so that the `content-list.php` partial was correct. Previously the archive ```container``` had the `post_class();` function which was incorrect.

**Comment by marcperel** [comment]
Here are the classes any custom template needs:

```<section class="container content-main archive clearfix">```

**Comment by raisonon** [comment]
Thanks @mahtar and @marcperel - Have added `` to my original post. Much better! `(good to know)`

We'll look at this again with your suggestions in mind. Thanks for the help.

**Comment by vailjoy** [comment]
Please see the following for page template adjustments:
http://docs.layerswp.com/doc/layers-page-template-content-is-full-width/

**Comment by vailjoy** [comment]
This is now fixed in 1.2.3
