### ISSUE TITLE
Content Widget : Background Darken

### ISSUE THREAD

**Issue by cliftonscott** [Obox/layerswp#230]
I've tested this across two sites running LayersWP. Adding a content widget, then a background image, then checking the "Darken" option has no effect on the background and neither is a semi-transparent overlay created. Anyone else seeing this?

LayersWP 1.2.2

**Comment by cliftonscott** [comment]
Filtering layers_content_widget_container_class and passing $widget as a variable would allow a conditional that could be used to change the class (CSS) of the section. 

core/widgets/modules/content.php Line 120
$widget_container_class = implode( ' ', apply_filters( 'layers_content_widget_container_class' , $widget_container_class, $widget ) ); ?>

**Comment by cliftonscott** [comment]
Here is my solution to overcome this bug without hacking core. This is the procedural solution. Not optimum but it works. Then, I used CSS pseudo to apply the darkened overlay.

```php
add_filter('layers_content_widget_container_class', 'content_darken_background', 10, 2);
function content_darken_background($widget_container_class){
		$widgets = get_option('widget_layers-widget-column');
		foreach($widgets as $widget)
		{
			if(isset($widget['design']['background']['darken']) && $widget['design']['background']['darken'] == 'on')
			{
				$widget_container_class[] = 'content-widget-darken';
			}
		}
		return $widget_container_class;
	}
```

**Comment by marcperel** [comment]
Thanks @cliftonscott we'll consider this fix for the next release.

**Comment by vailjoy** [comment]
The background darken option has been removed from this widget in 1.2.11
