### ISSUE TITLE
layers_wrapper_class in header.php adding inline style that shifts each page down

### ISSUE THREAD

**Issue by virgilshelton** [Obox/layerswp#231]
Description: Please see a child theme I built at http://www.sumnerfurniture.com/ 

When Layers is just about to finish rendering the page the DIV  ```<div style="padding-top: 130px;" class="overlay content">``` applies the inline style padding-top: 130px ``` on all pages causing the DIV to shift on each page load. 

This is reproducible 100% on all versions of layers. 

Commenting out the function in headers.php fixes the issue which is not a fix but a test to make sure I found the location of the code for myself. 

Steps to reproduce.

1. Open http://www.sumnerfurniture.com/ 
2. Wait for page to load and notice the words on the first slide "Welcome to Sumner Furniture!" move down and each press of F5.

**Comment by vailjoy** [comment]
Hey there!

I am not the absolute best person to explain this but I will give it a shot while our devs are super busy - when you have a sticky or overlay header, there is a script that adjusts the padding on the content container to ensure the header doesn't overlap your titles or other good stuff on the page. Further complications happen when you have the top-image layout in the slider and no image, which is a second adjustment. The associated CSS fires off during the layers_inline_styles call in the footer, so if you have a slow loading page, you are going to see this adjustment take place. The first thing to aim for is as much speed as possible while loading. You can also hard-code the top-padding using the CSS panel in the customizer, which will fire in the header instead.

.

**Comment by virgilshelton** [comment]
I'll try the work around, however the bug is real and is currently reproducible on http://Layerswp.com 

Thanks!

**Comment by virgilshelton** [comment]
Thanks @vailjoy that worked I added 
```CSS
.wrapper-content{padding-top: 80px;}

```
