### ISSUE TITLE
LayersWP and WooCommerce

### ISSUE THREAD

**Issue by dedayoa** [Obox/layerswp#232]
One of the propositions of layers is its compatibility with woocommerce, however I made the mistake of of updating to Woocommerce 2.4 hours after its release and it has broken Layers.
Creating a new layers page does not work. The "loading widget" in the new page modal loads up, but nothing happens after that.
The only sign of an error I have found so far is an error 500 from the server

**Comment by marcperel** [comment]
We generally don't like giving this answer but are you sure that there are
no plugins running which are causing the error?

We have been running WC 2.4 for a while now without issue.

~ Marc

**Comment by dedayoa** [comment]
I'm sure. I did not have the problem until I updated woocommerce last night. I also confirmed by disabling woocommerce. Once I do, layers works fine.
![error500](https://cloud.githubusercontent.com/assets/2971690/9207179/d9c71e6a-4063-11e5-9103-0fa2e28318f2.jpg)
I tried uploading the above with my initial entry...but you can see the error I get once I click "...to create a new layer"

**Comment by marcperel** [comment]
Great thanks, what you can do in the mean time is add a new page by going
Pages > Add New, choose the Layers Builder template and edit your page that
way.

We will find the bug fix asap.

**Comment by dedayoa** [comment]
Although I think I remember not being able to save the created layers page, I have downgraded woocommerce in the mean time. I hope a fix from layers is available soon.

**Comment by marcperel** [comment]
We will try and replicate this bug as soon as possible. I'll assume you're
running WordPress 4.2.4?

**Comment by dedayoa** [comment]
Yes I am. Host is http://wandhost.com, Linux shared hosting
