### ISSUE TITLE
Admin Sub-Menu Empty for different roles

### ISSUE THREAD

**Issue by mdoerneman** [Obox/layerswp#235]
I set up a user with a different role such as Editor and the Layers submenu in the admin is empty. This is happening for other roles as well.

**Comment by vailjoy** [comment]
Hi there,
This is addressed here:
http://docs.layerswp.com/doc/editors-and-authors-cannot-see-layers-menu-or-customizer/

**Comment by marcperel** [comment]
Thanks Michael we'll have a look into this.

On Thu, Aug 13, 2015 at 3:03 PM, Michael Doerneman <notifications@github.com
