### ISSUE TITLE
Weather Theme: product tabs working no more after woocommerce 2.4 upgrade

### ISSUE THREAD

**Issue by altatof** [Obox/layerswp#237]

**Comment by marcperel** [comment]
Hey @altatof,

Running `WooCommerce 2.4.4` and Layers `1.2.2` we haven't had an issue, can you confirm the problem is not plugin related?

**Comment by altatof** [comment]
Hello, thanks for your reactivity.

In fact the problem comes with your *weather* child theme (sorry to not 
have mention before).

I'm running woocommerce 2.4.4 and layers 1.2.3 (since 5 minutes, before 
was 1.2.2).

The problem is that the click event of the tab header is not triggered 
in single-product.js (plugins/woocommerce/assets/js/frontend/ ).

I did not understand why.

But if you change the code to somewhat similar to woocommerce 2.3 
release, it works well !

And i confirm the problem appears with weather child theme only (good 
with standalone layers or other themes !!!)

Best regards
Christophe

Le 17/08/2015 12:56, marcperel a écrit :
>
> Hey @altatof <https://github.com/altatof>,
>
> Running |WooCommerce 2.4.4| and Layers |1.2.2| we haven't had an 
> issue, can you confirm the problem is not plugin related?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Obox/layerswp/issues/237#issuecomment-131780945>.
>

-- 
<small><i>Christophe Battarel<br/>
Responsable technique Altairis</i><br/>
+33 (0)9 52 71 70 96</small>

**Comment by marcperel** [comment]
Great thanks for the feedback!
