### ISSUE TITLE
Multiple array field name does not save

### ISSUE THREAD

**Issue by sahidhossen** [Obox/layerswp#239]
In the widget area multiple array field name does not save. When I type into the input field it's return empty value. Here is my field name and ID: 
<i>
 id="widget-layers-widget-according_column-13-sub_columns-910-114-title"
 name="widget-layers-widget-according_column[13][sub_columns][910][114][title]" 
</i>
I have created sub column into the column. But I could not save the field data. Please help me for this issue. 

Thanks.

**Comment by marcperel** [comment]
@sahidhossen this is an exciting issue I've had trouble with before, can you try printing the value for the top level inputs? `print_r( $instance[ 'widget-layers-widget-according_column' ] );` that's the first step to seeing how the input is being saved.

Take it from there and go down the tree until you find there the stopper is.

**Comment by sahidhossen** [comment]
I am very excited that my data is now save but Its does not appear into the input box when its bluer. I have store all of the data into $this->defaults['sub_columns'] and its save the data.
Here is print_r($this->defaults['sub_columns'])  information.  
![untitled](https://cloud.githubusercontent.com/assets/12063077/9351551/47991876-467c-11e5-82b5-2de434f5ee29.png)

Look at  the first array. Please help me for recover the data into the text field.

**Comment by marcperel** [comment]
Can you send me the code for your input?

```$this->input()```; etc.

**Comment by sahidhossen** [comment]
Here is my form element. I have create do duplicate function for this. 

 $this->form_elements()->input(
                            array(
                                'type' => 'text',
                                'name' => $this->get_custom_sub_field_name( $sub_widget_details, 'sub_columns', $column_guid,  $columnguid_sub, 'title' ),
                                'id' => $this->get_custom_sub_field_id( $sub_widget_details, 'sub_columns', $column_guid, $columnguid_sub, 'title' ),
                                'placeholder' => __( 'Enter Title' , 'layerswp' ),
                                'value' => ( isset( $title ) ) ? $title : NULL ,
                                'class' => 'layers-text',
                            )
                        );

**Comment by marcperel** [comment]
`'value' => ( isset( $title ) ) ? $title : NULL ,`

Have you checked that your column functions are correctly extracting `$title`?

**Comment by sahidhossen** [comment]
My column function work only the main form function. Its change instant when I bluer the field. 
  <?php var_dump($instance['sub_columns']); ?>

But it does not work into the according_column_item() and my custom function according_column_sub_item(). 
Its return default values into those two functions. Should I pass this value through an argument into this two function. I am totally confuse.

**Comment by marcperel** [comment]
Do me a favor, can you create a gist?

https://gist.github.com/

**Comment by sahidhossen** [comment]
I have solve this problem but in different away. Now its works as like horrible. I think I can change the layerswp looks and its solve many problem which has limitation of the layerswp.
