### ISSUE TITLE
Issue: Error Adding Custom section on customize 

### ISSUE THREAD

**Issue by zohurul88** [Obox/layerswp#240]
When I try to a Adding a Custom Section its displayed this error message 
Warning: Illegal string offset 'priority' in layerswp\core\customizer\registration.php on line 125

**Comment by marcperel** [comment]
@zohurul88 Make sure you're running the latest version of Layers, `1.2.4` which we launched yesterday, it should fix that issue +1

**Comment by zohurul88** [comment]
@marcperel I update to the current version of the layers 1.2.4 but I think its not working properly yet. 
At the new version section is added but when I going to customize mode it's shows me the same warning 
![untitled](https://cloud.githubusercontent.com/assets/6093194/9374243/bce1f62c-4715-11e5-873c-f3a7e2cb7ca5.png)

Here is my code: 

add_filter( 'layers_customizer_sections', 'tycoon_custom_sections', 100);
function tycoon_custom_sections($sections)
{
	$sections[ 'tycoon-settings' ] = array(
        'title'     => __( 'Social Media Profiles' , 'layerswp' ),
        'panel'     => 'site-settings',
    );

$sections = array_merge( $sections, $sections[ 'tycoon-settings' ] );

return $sections;
}


add_filter( 'layers_customizer_controls', 'tycoon_customizer_controls', 100 );

function tycoon_customizer_controls( $controls ){
    $controls[ 'tycoon-settings' ] = array(
       'social-twitter' => array(
            'type'      => 'layers-text',
            'label'     => __( 'Twitter Username' , 'layerswp' ),
        ),
       'social-facebook' => array(
            'type' => 'layers-text',
            'label'     => __( 'Facebook Vanity URL' , 'layerswp' ),
        ),
       'social-pinterest' => array(
            'type' => 'layers-text',
            'label'     => __( 'Pinterest Username' , 'layerswp' ),
        ),
    );
 
	return $controls;
}

**Comment by zohurul88** [comment]
I get the bug. and fix it. In your documentation you merge the array and return it but actually array merge not needed. The code will be 

add_filter( 'layers_customizer_sections', 'tycoon_custom_sections', 90);

function tycoon_custom_sections($sections)
{
$sections[ 'tycoon-settings' ] = array(
'title' => __( 'Social Media Profiles' , 'layerswp' ),
'panel' => 'site-settings',
);

return $sections;
}

**Comment by marcperel** [comment]
Fantastic, thanks MD :)

On Thu, Aug 20, 2015 at 12:21 PM, MD Zohurul Islam <notifications@github.com

**Comment by zohurul88** [comment]
@marcperel You Welcome
