### ISSUE TITLE
Problem with Events calendar plugin since WP 4.3

### ISSUE THREAD

**Issue by Jelena1** [Obox/layerswp#242]
Can you please resolve this issue? 

Link to plugin: https://wordpress.org/plugins/the-events-calendar/

I have theme that worked fine with this plugin until WP 4.3. Now customizer doesn't work
and it gives error: 

Fatal error: Call to undefined function get_current_screen() in /......../wp-content/plugins/the-events-calendar/src/Tribe/Query.php on line 302

I updated Layerswp to 1.2.4 but still it doesn't work.

Test with basic Layerswp theme and only that plugin active and still doesn't work.

Any help appreciated.

**Comment by vailjoy** [comment]
Hi there, 

This is an error in the plugin that the plugin author needs to resolve.
