### ISSUE TITLE
Issue: Layers Support for WP 4.3?

### ISSUE THREAD

**Issue by brandbrilliance** [Obox/layerswp#244]
## Description of issue
Layers doesn't work correctly with Wordpress 4.3

## URL of page exhibiting the issue
Hidden/Test

## Web Browser(s) that exhibit the issue
Safari 8.0.8

## Error Message or Steps to Recreate
Menus and other items are blank in the CUSTOMISE section

**Comment by vailjoy** [comment]
I can confirm Layers is 100% compatible with WordPress 4.3. If you are experiencing a PHP error, please deactivate all plugins and try again. If the error reappears, please copy and paste it here.

If menus and widgets are gone, make sure you did not delete Layers from WordPress, then reinstall it (that takes all your Layers data with it). The Layers updater plugin can be downloaded from the Layers Dashboard and allows for seamless updating of layers without a reinstall.

For general questions, please use support at http://docs.layerswp.com/help/
You can find update notes here and in the version announcement on that site.
