### ISSUE TITLE
Issue: Download Network Connect Reset

### ISSUE THREAD

**Issue by brandbrilliance** [Obox/layerswp#245]
## Description of issue
I've tried to download Layers to see if there is a newer version, but your current download just stops with a Safari Error "The Network connection was lost" -- I've tried like 10 times on various days. 

## URL of page exhibiting the issue
N/A

## Web Browser(s) that exhibit the issue
Safari 8.0.8

## Error Message or Steps to Recreate
Click on Download Link on website.

**Comment by vailjoy** [comment]
I can confirm the download link here works, and the one here http://layerswp.com
To report issues with the website, please use support: http://docs.lalyerswp.com/help/ or send us a tweet @layerswp. Git issues is for reporting bugs in the theme. Thanks!
