### ISSUE TITLE
Images not centered

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#249]
If using the default WP aligncenter class (added by WP) on images you wont get centered images

I suggest adding the following to .aligncenter 

`display: block;
    margin-right: auto;
    margin-left: auto;
    text-align: center;
    float: none;
    clear: both;
`

**Comment by vailjoy** [comment]
Hey I just wanted to say how much we appreciate your continued feedback!

**Comment by raisonon** [comment]
No worries - hope it's helpful and not nit picking!

**Comment by vailjoy** [comment]
Fixed in 1.2.14
