### ISSUE TITLE
HTML entities automatically converted 

### ISSUE THREAD

**Issue by virgilshelton** [Obox/layerswp#250]
I'm trying to insert a copy and past HTML snippet code for affiliates to promote banners on their blogs \ websites. I add the code bellow into a Content Widget using the show HTML button in the excerpt section and the ```&gt;``` and ```&lt;``` get converted to < and >.  

Here's an example. 

```<pre><code>&lt;a href="https://itunes.apple.com/app/id1014108140" target="_blank" style="border:none; text-decoration:none;"&gt;&lt;img src="http://heatrunningapp.com/images/ambassador/heat_square.jpg" alt="Unlock Your Animal" style="width:100%; max-width:180px; height:auto; max-height:150px; display:block; margin-top:10px; margin-bottom:10px;"&gt;&lt;/a&gt;</code></pre>```

Gets converted to 

```
<pre><code><a href="https://itunes.apple.com/app/id1014108140" target="_blank" style="border:none; text-decoration:none;"><img src="http://heatrunningapp.com/images/ambassador/heat_leader.jpg" alt="Unlock Your Animal" style="width:100%; max-width:728px; height:auto; max-height:90px; display:block; margin-top:10px; margin-bottom:10px;"></a></code></pre>
```

**Comment by vailjoy** [comment]
Hi there,
That would be normal behavior. If you are trying to display code, you only need to type it in the RTE view, not the code view. To wrap it in a pre style, then switch to code view and change the <p> tags to <pre> tags. When you switch  back to RTE view you should see the code in the correct format wrapped in the pre style box. (no need to use<code>). If you are trying to paste this code to use its output, paste it using the code view without the <code> and <pre> tags. You may need to move the styles into the Advanced button.
