### ISSUE TITLE
Issue: devkit removes backslash

### ISSUE THREAD

**Issue by openforest** [Obox/layerswp#251]
My CSS:
`.myitem:after {
  content:"\A \A ";
  white-space: pre;
}` 

After saving Devkit "sanitises" it to:
`.myitem:after {
  content:"A A ";
  white-space: pre;
}`

**Comment by openforest** [comment]
My CSS:
`.myitem:after {
  content:"\A \A ";
  white-space: pre;
}` 

After saving Devkit "sanitises" it to:
`.myitem:after {
  content:"A A ";
  white-space: pre;
}`

**Comment by vailjoy** [comment]
Hi there,

I can confirm this has been changed in the next version, which should be available as early as Friday.
