### ISSUE TITLE
Unable to copy widget anchor ID.

### ISSUE THREAD

**Issue by zohurul88** [Obox/layerswp#254]
Hi Layers.
I am try to copy the widget anchor ID but I can't. Because the field is disabled I think you should change it to  readonly. Then user can able to copy the ID. And your ID started with widget word but actual Id not started with it Please I think you should fix this ASAP.
![widget](https://cloud.githubusercontent.com/assets/6093194/9595424/35db26ae-5088-11e5-973a-b75e737b5289.jpg)

**Comment by marcperel** [comment]
Thanks @zohurul88 we'll put this into the next fix!

**Comment by vailjoy** [comment]
Fixed in 1.2.6
