### ISSUE TITLE
Moving Localhost to Online

### ISSUE THREAD

**Issue by Uranbold** [Obox/layerswp#255]
Hello,

After Moving Localhost to Online all contents are blank how do we restore it?

Thanks.

**Comment by webmas** [comment]
I think you must give further information about the steps you followed.
You can ask in the support forum, this is http://docs.layerswp.com/forums/question/from-localhost-to-provider/ a discussion with the steps to move a site from local to online.

**Comment by vailjoy** [comment]
Here is the doc :)
http://docs.layerswp.com/how-to-setup-a-local-development-environment/
