### ISSUE TITLE
How can i move customizer controls

### ISSUE THREAD

**Issue by geniuspro** [Obox/layerswp#256]
Hello. 
I want to move some options control from site customize on child theme.
Example: I want to move some panels from Customize -> Header -> Layout to My Own Options -> Header Options. 

Please help me.

I'm not good php developer and sorry my poor English. Thanks for the help me.

**Comment by vailjoy** [comment]
Hi there,

We don't really provide a way for you to change the core functionality. It is important to preserve mainly for the user experience to be unchanged in that regard from Layers to child. You can create custom controls for your child theme which mirror ours. Please see the guide here:
http://docs.layerswp.com/create-an-extension-adding-customizer-controls/

For general questions on layers and layers development, please visit the community forum here:
http://docs.layerswp.com/forums/

**Comment by olziinaa** [comment]
Thank you very much. :D
