### ISSUE TITLE
The 'Edit Layout' left navigation doesn't show up

### ISSUE THREAD

**Issue by philamery** [Obox/layerswp#259]
hi, 

I've just downloaded and installed the latest release (layerswp-1-2-4-2.zip) and looks like I can not edit any content element since the 'Edit Layout' menu which leads to content types for editing is simply missing from left side navigation. 
Any clue from anyone? 

PS
In one of my previous installs on another site I own, it works pretty fine.

**Comment by philamery** [comment]
hi, 

anyone facing this issue? 
please someone help, I really got stuck in this issue 
deleting and reinstalling the theme did not lead to any change, same issue remains 

p.

**Comment by philamery** [comment]
here is an attached screen capture to see what I mean 
![leftnavigation](https://cloud.githubusercontent.com/assets/10886661/9720814/64b1dd24-5592-11e5-8e15-7606416bd03b.png)

**Comment by marcperel** [comment]
@philamery Hey Phil, it sounds like on the live sit you may have a plugin which is not agreeing with WP 4.3, have you tried disabling your plugins and giving it another go?

**Comment by philamery** [comment]
@marcperel thanks for your advice, I went through each one of the plugins, switching them off step-by-step but unfortunately no result for the better, meaning, the Edit navigation still doesn't show up 
since it is a newly built project, currently I have very few plugins (Contact form 7, Loco Translate, WP Maintenance Mode, Yoast SEO and Zencache) 
I was suspicious on the either Loco Translate or the WP Maintenance mode plugins but turning them off, did not solve the issue however I noticed Loco Translate did not allow to ad an additional language for the Layers theme. 
now I'm really stucked in this 
I might consider giving access to my WP admin, just let me know

**Comment by philamery** [comment]
guess what @marcperel ? 
afterall, it turned out my browser (Chrome) was to blame for this cause, however, interestingly on another site of mine built also w/ Layers theme, this issue doesn't appear. Any idea? 
Meanwhile I can work further on in my FF browser. 
Thought I'll share the info w/ you and the whole community, though I'm still wondering why this issue appears only in one of my sites with same browser

**Comment by marcperel** [comment]
Hey @philamery,

It's apparently a known Chrome bug affecting all of WordPress which is quite sad: http://wptavern.com/a-bug-in-chrome-45-causes-wordpress-admin-menu-to-break

I'd suggest working in FF until the problem has been dealt with.

~ M

**Comment by philamery** [comment]
thanks @marcperel 
now, let's consider this issue as solved 
thanks again for your support
