### ISSUE TITLE
Panel Display None.

### ISSUE THREAD

**Issue by zohurul88** [Obox/layerswp#262]
Hi Obox
When I try to add a new panel it's added with inline style display none. How can I overcome this problem. Please let me know.
![1](https://cloud.githubusercontent.com/assets/6093194/9740927/3aaaa180-560c-11e5-9689-c44ad83c2e9c.png)
![2](https://cloud.githubusercontent.com/assets/6093194/9740928/3ad6a2d0-560c-11e5-8941-14523bc6072b.png)

**Comment by marcperel** [comment]
We've had this issue before, can you share the code that you're using to add the panel so that we can help you find the issue?

**Comment by vailjoy** [comment]
Ref: http://docs.layerswp.com/create-an-extension-adding-customizer-controls/

**Comment by resarahman** [comment]
I also had this issue. the case is because I'm calling the filter inside is_admin() condition

    if ( is_admin() ) {
      add_filter('layers_customizer_panels','layers_child_customizer_panels', 40);
    }

When I'm calling the filter function without is_admin() condition, it work fine. so the workaround would be please make sure you calling the filter function on the init.

**Comment by marcperel** [comment]
Thanks @resarahman

**Comment by vailjoy** [comment]
Documentation checked
