### ISSUE TITLE
Issue: customiser breaks with Simple Membership Plugin

### ISSUE THREAD

**Issue by tinamayswinkels** [Obox/layerswp#263]
## Description of issue
Customiser is endlessly loading for all pages if the simple membership plugin (one of the most popular membership plugins) is activated, including pages that don't contain any content from those pages. If it is deactivated overtime the editor needs to be used then end users will be presented with broken links and shortcodes. 

https://simple-membership-plugin.com/

## URL of page exhibiting the issue
www.entrepreneursocialclub.com.au

## Web Browser(s) that exhibit the issue
Safari, Firefox, Chrome (all latest versions) 

## Error Message or Steps to Recreate

No error messages displayed, just never stops loading (i.e. 10 mins +) Happens consistently when the plugin is activated and stops when it is deactivated.

**Comment by marcperel** [comment]
Hey @tinamayswinkels If you inspect the code of the iframe does it show any errors? The customizer not loading (or always loading but never completing) usually means that there's an error in the iframe section and the theme's footer is never reached.

**Comment by ddresch** [comment]
I ran into a similar error and the solution in my case was to increase php_execution_time which was default to 30sec. The hint to check the `sourcecode` of the page and not via `html-elements` / `js console` helped, there at the very end I could find the PHP execution time error.
