### ISSUE TITLE
Archive page with no post right-sidebar go to left

### ISSUE THREAD

**Issue by webmas** [Obox/layerswp#265]
In a new site i have added some taxonomies, that taxonomies will be populated in the future . 
Sidebar set to right.

Now the archive page for the taxonomy with no already associated post have no DIV for the content, there is only the right sidebar and <div class="column span-8"> </div> is missing.

The attached images show the problem and my solution, only a swap to two lines in archive.php code.
![no-posts-corrected](https://cloud.githubusercontent.com/assets/6018116/10019888/351e6564-6140-11e5-9e1b-3c3835ba5bc3.jpg)
![code](https://cloud.githubusercontent.com/assets/6018116/10019890/35299fec-6140-11e5-890b-7aad537617db.jpg)
![no-posts](https://cloud.githubusercontent.com/assets/6018116/10019889/35276b96-6140-11e5-96a3-8fb868090448.jpg)

**Comment by vailjoy** [comment]
Hi there,
The loop cannot be removed from the archive page template or you will never see any posts there. It is normal for the page to be blank if you are viewing a category archive with no posts. If you want to show a message, you can add something like the following right before the <?php endif: // if has_post() ?> line:

else :
    <div>
	<h3 class="post-title"><a href="#"><?php _e("Nothing Here Yet","layerswp"); ?></a></h3>
    </div>

**Comment by webmas** [comment]
Sorry, the question is little different. 
In my code the loop stay untouched.
Ok that the page with no posts must stay blank, but with the IF control before the DIV then in the generated html there is the sidebar with the "pull-right" class but this sidebar is pulled to the left( the column in third attached image ) because the content DIV column is missing ( the yellow line in first image with empty content) and therefore this break the template .
Swapping 

Original:
	<?php if( have_posts() ) : ?>
		<div <?php layers_center_column_class(); ?>>
			<?php while( have_posts() ) : the_post(); ?>
				<?php get_template_part( 'partials/content' , 'list' ); ?>
			<?php endwhile; // while has_post(); ?>

			<?php the_posts_pagination(); ?>
		</div>
	<?php endif; // if has_post() ?>

Modified:
	<div <?php layers_center_column_class(); ?>>
		<?php if( have_posts() ) : ?>
			<?php while( have_posts() ) : the_post(); ?>
				<?php get_template_part( 'partials/content' , 'list' ); ?>
			<?php endwhile; // while has_post(); ?>

			<?php the_posts_pagination(); ?>
		<?php endif; // if has_post() ?>
	</div>

I have tried this code and works correctly, with and without posts in the loop the content column is generated and the template is correctly designed.

**Comment by marcperel** [comment]
I understand the issue @webmas.

@vailjoy, @webmas is pointing out that with the default `archive.php` we get a blank div when no posts are found, but with his code that empty div is no longer there.

**Comment by vailjoy** [comment]
Fixed in 1.2.10
