### ISSUE TITLE
Advance css in core widget

### ISSUE THREAD

**Issue by debasiskoley** [Obox/layerswp#266]
Hi,
  All core widget advance css code are load into body tag. Please check if the custom css load before body tag will be valid with w3c validation.

**Comment by vailjoy** [comment]
For live customization to work in the widgets, some code needs to load inline or at the end of the document and cannot be placed in the head. It is difficult to run the output of a WordPres site through w3c validation. The template HTML is validated before it is turned into templates, and the templates/PHP markup is further validated by being run through the WP ThemeCheck plugin.
