### ISSUE TITLE
$widget['title'] in all core widget need to escape html

### ISSUE THREAD

**Issue by debasiskoley** [Obox/layerswp#267]
$widget['title'] in all core widget need to escape html. If any one enter html tag at title in core widget then now it show in h3 tag.

**Comment by vailjoy** [comment]
Hi there,

It currently is, converting any HTML to plain text. There are a few cases for why we would need to allow HTML in the comment actually so we will be running some tests. In the case where we end up allowing HTML content it will be important to ensure heading tags are not copied into the title.
