### ISSUE TITLE
Colums don't work weel in hooks positions

### ISSUE THREAD

**Issue by ckubs** [Obox/layerswp#27]
I'm trying to add some content after the header( in the hook position) the titles of my las 6 articles from the featured category, basically a list of links, done that and it works. But, when I want to put them in columns, for better looks, I encounter some sort of a bug. If I wrap them in the "column" class  the layout acts weird and the links aren't clickable anymore. They seem blocked by something, maybe something transparent that overlaps them.

**Comment by vailjoy** [comment]
Hello,
You need to contain them in a section with class "row" or a class with a display: block property.. Please see the Framework reference here:
http://docs.layerswp.com/layers-framework-grids/
