### ISSUE TITLE
WordPress Category Dropdown on Theme Customizer

### ISSUE THREAD

**Issue by geniuspro** [Obox/layerswp#270]
Hello. 
Thanks for the your awesome framework.

I need your help. How can i add category dropdown on theme customizer section. it is possible?

```
$controls[ 'rolog-options-archive-category' ] = array(
			// CONTENT OPTIONS
			'blog-options-heading' => array(
				'type'  => 'layers-heading',
				'label'    => esc_html__( 'Footer Options Padding' , 'layers-look' ),
			),
			'featured-post-category' => array(
	       		'type' => 'layers-select',
	       		'label'    => esc_html__( 'Category Blog Style' , 'layers-look' ),
				'default' => 'grid',
				'choices' => array(
					'grid' => esc_html__( 'grid' , 'layers-look' ),
					'medium' => esc_html__( 'Medium' , 'layers-look' ),
					'normal' => esc_html__( 'Normal' , 'layers-look' ),
				)
	       	),
}
```

Thanks

**Comment by vailjoy** [comment]
Hi there,
Please see the following:
http://docs.layerswp.com/create-an-extension-adding-customizer-controls/

It's possible to pass custom parameters for specific control types. These are available only for some control types. Example for "select" and "radio" controls: 'choices'=> yourtheme_get_categories(),
