### ISSUE TITLE
Add custom section but style="display:none"

### ISSUE THREAD

**Issue by gizalink** [Obox/layerswp#271]
Hi guys,

I'm using child theme layerswp. I have add code in functions.php of child theme
```
add_filter('layers_customizer_sections','layers_child_customizer_sections', 100);
if( !function_exists( 'layers_child_customizer_sections' ) ) {
   function layers_child_customizer_sections( $sections ){
      $sections[ 'info_header_gl' ] = array(
        'title' => __( 'Phone and Email' , 'child' ),
        'panel' => 'header',
      );
      return $sections;
   }
}
```

But when i see 

![Image of Gizalink](http://i.imgur.com/w6cLpn7.png)

Can you help me.

**Comment by vailjoy** [comment]
Hi there,

For a faster response, please post dev questions here:
http://docs.layerswp.com/forums/

Or join our dev channel on slack: http://docs.layerswp.com/developers/

1. Check your code against this tutorial:
http://docs.layerswp.com/create-an-extension-adding-customizer-controls/

2. Refer to Marc's response here:
https://github.com/Obox/layerswp/issues/262
