### ISSUE TITLE
Export / Import of layout .json files not working properly

### ISSUE THREAD

**Issue by ddresch** [Obox/layerswp#272]
Simple task as follows:

1. edit a layers page and press "export JSON" button
2. create new empty layers page
3. edit newly created page and import exported JSON file

Repeat the procedure multiple times and each time randomly another part of the exported page is missing?!?! Using the "duplicate" button gives the same random results.

For testing I exported the JSON file again and compared the files which at the end are identical. So where is the bug, my setup, my procedure how to "copy" a page?

Any help appreciated, cause this simple task of copying a page is not that uncommon and should be working out-of-the-box. Now the "workaround" is adding the missing content manually again!!!!

**Comment by vailjoy** [comment]
Hi there,
I was able to test and confirm both functions are working as designed.

1. Ensure the page to be exported has been saved and customizer settings published before exporting.
2. The export only saves Layers widget data. 3rd Party widgets will not be saved. 
3. If the widgets are there but you are just missing images, make sure the images exist in your media library with the same filename as the original page setup. 

Here are the step-by=step instructions which should be working without issue:
http://docs.layerswp.com/doc/how-to-create-a-style-kit/
