### ISSUE TITLE
Submenu dropdown on top nav

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#277]
There isn't one! Would be ideal to have this integrated

**Comment by vailjoy** [comment]
We made the design decision to limit this menu to top-level only for a couple reasons:

1. A drop down potentially overlaps the main menu 
2. It over-complicates navigation. The top menu is intended for quick links to things like My Account or a Client Area, and not page navigation (which is what the Header Menu is for)

This behavior can be customized in child themes or custom functions quite easily by changing the menu array with a filter:

Ref: https://github.com/Obox/layerswp/blob/master/partials/header-secondary.php#L10

function modify_nav_menu_args( $args )
{
	if( 'layers-secondary-right' == $args['theme_location'] )
	{
		$args['depth'] = -1;
	}

	return $args;
}

add_filter( 'wp_nav_menu_args', 'modify_nav_menu_args' );
