### ISSUE TITLE
add action to after wrapper content

### ISSUE THREAD

**Issue by sermedias** [Obox/layerswp#284]
i try to add title container via my functions file i am using overlay header. and i add a background to tittle container when i use after header or something header is not overlaying the title-container. when i add a do_action(something_etc) after the wrapper-content in header.php then i hooked it to a title container it has a overlay with header.. if is there a different way for it can you explain.

**Comment by vailjoy** [comment]
Hi there,

Can you clarify exactly what the end result you are going for would be? You can also post your question to our dev community here (where you can share your URL or screenshots)

http://docs.layerswp.com/forums/
