### ISSUE TITLE
Content section - color font (4 in 1)

### ISSUE THREAD

**Issue by VadymVolos** [Obox/layerswp#287]
Hi! In the settings you can choose the color for the text ( .section-title AND media-body ) But, necessary for each of the 4 blocks separate choice. I can do it in css. But people do not know how to do it.
```css
.layers-content-widget .section-title .heading { }
.layers-content-widget .section-title .excerpt { }

.layers-content-widget .list-grid .media-body .heading { }
.layers-content-widget .list-grid .media-body .excerpt { }
```

**Comment by VadymVolos** [comment]
![2](https://cloud.githubusercontent.com/assets/12669290/11093994/f5d3c5a2-8895-11e5-892e-6ea10573f8cd.png)

**Comment by vailjoy** [comment]
Hi there,
To keep things simple we have one content color control, and one for the widget title. To color the content title separately from the content excerpt, you must use Custom CSS in the Advanced panel. This does require some knowledge of how to use CSS selectors, however we do have a primer on using the Advanced option to do these kinds of tweaks here:
http://docs.layerswp.com/doc/how-to-use-the-advanced-design-bar-option-to-add-custom-classes-to-widgets/
