### ISSUE TITLE
Slider centering

### ISSUE THREAD

**Issue by marcello77** [Obox/layerswp#288]
Hi,
the Slider widget seems to have some centering problem as shown in attachments.
This didn't happen in the older versions.

Any idea?

Thank you

(Layerwp is great!)

![schermata-2015-11-13-alle-11 36 45](https://cloud.githubusercontent.com/assets/15831723/11144356/4a958370-89fc-11e5-8d6e-b910986ec8bf.jpg)
![schermata-2015-11-13-alle-11 36 54](https://cloud.githubusercontent.com/assets/15831723/11144354/4a930758-89fc-11e5-90fa-6e9ca74ff0d9.jpg)
![schermata-2015-11-13-alle-11 37 35](https://cloud.githubusercontent.com/assets/15831723/11144355/4a9576aa-89fc-11e5-8d8d-bec58ca73e33.jpg)

**Comment by marcello77** [comment]
I'm using Layers 1.2.7

**Comment by vailjoy** [comment]
Hi there,
Please update to 1.2.9, thanks!
