### ISSUE TITLE
Advanced Content Links

### ISSUE THREAD

**Issue by marcello77** [Obox/layerswp#289]
Hi,
Advanced Content's button link produces empty <a href as shown in the attachment.

Why?

Thank you
![schermata-2015-11-13-alle-11 51 01](https://cloud.githubusercontent.com/assets/15831723/11144501/61f9eed8-89fd-11e5-95a8-9f7048949953.jpg)

**Comment by marcello77** [comment]
I'm using Layers 1.2.7

**Comment by vailjoy** [comment]
Hi there,

Please ensure you are on our latest version 1.2.9. If the button fields are blank, there should be no HTML written, so just ensure both of those fields are removed. If you are referring to the Advanced Content widget in a Layers Extension and need development help, please post your question here:
http://docs.layerswp.com/forums/
