### ISSUE TITLE
Slider glitches

### ISSUE THREAD

**Issue by DieTapete** [Obox/layerswp#293]
**The slider widget seems to be buggy on mobile.** 
Sometimes the slides appear all at once and underneath each other instead of side by side:

![bug](https://cloud.githubusercontent.com/assets/1159445/11258355/a66059ea-8e58-11e5-8dc8-fbe5554b7a34.jpg)

This glitch also appears on desktop but only for a short moment. Maybe this could be some kind of race condition or it's a bug in the swiper library. 
Referene: http://groundtruthsolutions.org/

**Comment by vailjoy** [comment]
Hi there,
Is this still a problem in 1.2.9?

**Comment by vailjoy** [comment]
This is resolved in 1.2.10, ETA is before tomorrow.
