### ISSUE TITLE
Blog Widget - showing author and date (when disabled)

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#295]
See:

https://www.dropbox.com/s/979r93byexvlf9x/Screenshot%202015-11-20%2018.12.38.png?dl=0
https://www.dropbox.com/s/1kuc3uv5fpczre3/Screenshot%202015-11-20%2018.13.28.png?dl=0

**Comment by marcperel** [comment]
Are you running Layers Pro Elliot?

**Comment by raisonon** [comment]
No - but updated to latest version of layers and that caused this

**Comment by marcperel** [comment]
Thanks! I'll tell Stu and we'll sort it out.

**Comment by VadymVolos** [comment]
Me too. When removed four checkmark (date, author, tags, category).

![1](https://cloud.githubusercontent.com/assets/12669290/11589615/7e2df5d6-9a92-11e5-9be1-ed8824befeb7.png)

**Comment by vailjoy** [comment]
This has been fixed and will be available in 1.3.0
