### ISSUE TITLE
Issue: Placement of SVG logo in titlebar wrong (also: LayersPro plugin)

### ISSUE THREAD

**Issue by tiptronic** [Obox/layerswp#296]
If I place a SVG as logo in the titlebar it's always drawn centered and moves the rest of the titlebar to the right edge.

Attached are 2 screenshot which show the problem. On the first one I'm using a .svg, and on the second one i'm using a .png of the same logo.

Happens on 1.2.9 - with Layers-Pro plugin

![screenshot 2015-11-21 18 06 22](https://cloud.githubusercontent.com/assets/80752/11319537/adec8f16-907a-11e5-9dda-c5d6dad4a9ae.png)
![screenshot 2015-11-21 18 05 38](https://cloud.githubusercontent.com/assets/80752/11319538/ae0f22f6-907a-11e5-8807-63c7145aec9a.png)

**Comment by vailjoy** [comment]
Hi there,
I am not able to recreate this, can you provide a direct link to the images? What are the image dimensions?

**Comment by tiptronic** [comment]
hi @vailjoy 
meanwhile I found the culprit; here's the deal:
- if you export the svg from illustrator it doesn't respect artboard dimensions and sets *very strange* own values.
- if I export from Sketch viewbox-sizes, etc... are correctly set and the logo is drawn properly.

The behaviour is still a little strange, so I attached 2 files where you can see the artifact...

[logosvg_tiptronic.zip](https://github.com/Obox/layerswp/files/52094/logosvg_tiptronic.zip)
