### ISSUE TITLE
Image Ratios not working

### ISSUE THREAD

**Issue by adommo** [Obox/layerswp#298]
I have choosen `Round` option for `Image Ratio` on `Post` widget of `LayersWP`. see the image below.
![1](https://cloud.githubusercontent.com/assets/5094765/11451445/b3dabd8c-95f0-11e5-8137-7a83b6a8311d.png)

The above setting should render round image as other widgets do. See the image below.
![2](https://cloud.githubusercontent.com/assets/5094765/11451455/0ae15d5c-95f1-11e5-9280-8bf2bf2a7902.png)

**Comment by vailjoy** [comment]
Hi there,
We are aware of a curent issue affecting image ratios. WordPress 4.4 will be changing default image handling so we are hoping this improves this feature and will resolve it in the next update.
