### ISSUE TITLE
Tabs without plugins

### ISSUE THREAD

**Issue by gb97** [Obox/layerswp#30]
Hello

Is it possible to load (internal)wp pages in the tabs with what's built-in in to Layerswp without using any more plug-ins?

```
<div class="nav nav-tabs">    
	    <ul class="tabs">
		<li class="active"><a href="#tab-1">Active Tab</a></li>
        <li><a href="#tabs-2">Regular tab</a></li>
        <li><a href="#tabs-3">Regular tab</a></li>
    </ul>
</div>
```
LIke this:
![tabs1](https://cloud.githubusercontent.com/assets/7217143/6427615/7dc9194c-bf3a-11e4-9195-2a1a36fb36d7.png)

How about a secondary vertical menu that loads (internal)wp or layerswp pages:
![tabs2](https://cloud.githubusercontent.com/assets/7217143/6427609/74977d1e-bf3a-11e4-949f-7737a412bc8c.png)

Also, are there user forums on WP.org/stackoverflow or anywhere for Layerswp?

thanks & great job!

**Comment by gb97** [comment]
I used this tutorial that implements jQuery UI in & it works great with the (twentytwelve) theme:
http://davecoast.com/dc_blog/how-to-jquery-ui-tabs-in-wordpress-child-theme/

I used the same code with a layerswp (child) theme & it doesn't work & this is what happens:
- With a regular WP page, tabs are not displayed but tabs contents work correctly.
- With a blank layerwp page & an added text widget with the tabs html code, tabs are not displayed & tabs contents don't work correctly.

**Question: How would I use & implement jQuery UI tabs with layerwp theme?**

This is what I'm doing & these files are placed in layerswp-child directory:

**style.css**
```
/*
Theme Name: Layers
Description:  A WordPress site builder so simple and intuitive, you’ll be a pro the first time you use it.
Author: Obox Themes
Author URI: http://www.oboxthemes.com/
Theme URI: http://demo.layerswp.com/
Version: 1.0.3
Tags: white
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain: layerswp
*/

/* Get the parent theme style sheet */
@import url("../layerswp/style.css");
@import url("//code.jquery.com/ui/1.11.3/jquery-ui.min.js");
```
**functions.php**
```
<?php
function demo_tabs_script_loader() {
	if (!is_admin()) { // only load for front end, not when I'm in the dashboard
			// Clear jQuery if already registered
		wp_deregister_script('jquery');
		wp_enqueue_script( // From jquery.com copy CDN (or download) 		
			'jquery',
			'//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js'
		); // End of enqueue jQuery
		wp_enqueue_script( // From jqueryui.com copy CDN (or download) 
			'jqueryui',
			'//ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js',
			array('jquery')
		); // End of enqueue jQuery UI 
		wp_enqueue_script( // Load up my script 
			'demo-script-one',
			get_stylesheet_directory_uri() . '/assets/js/demoTabsScript.js',
			array('jquery')
		); // End of enqueue Demo Script One
	} // End of Not-Is Admin if statement
} // End of Demo Tabs Script Loader Function
add_action('wp_enqueue_scripts', 'demo_tabs_script_loader'); 
// End of functions.php
```
**demoTabsScript.js  placed in /assets/js/demoTabsScript.js**
```
jQuery(document).ready(function($) {
	$( ".demoTabsClass" ).tabs();
});
```


**Placed in a TEXT widget  in a blank layerswp page:**
```
<h1>Demo of jQuery UI Tabs</h1><br>
	<div id="demoTabsId" class="demoTabsClass">
		<ul>
			<li><a href="#Tab1">Tab 1</a></li>
			<li><a href="#Tab2">Tab 2</a></li>
			<li><a href="#Tab3">Tab 3</a></li>
		</ul>
		<div id="Tab1">
			<p>Tab1 contents</p>
		</div>
		<div id="Tab2">
			<p>Tab2 contents</p>
		</div>
		<div id="Tab3">
			<p>Tab3 contents</p>
		</div>
	</div>
```
Result: Tabs don't work
![tabs](https://cloud.githubusercontent.com/assets/7217143/6432492/806372b4-c008-11e4-87a8-beb6cd4a2f29.png)

**Comment by vailjoy** [comment]
Hi there,
We are only able to address bugs and issues via Gi so I apologize for the abridged response. Please see http://docs.layerswp.com for theming guides and our framework reference. 

To get interactive tabs you need to either create a child theme that enqueues jquery ui and jquery tabs (already in the WordPress core) and then build a shortcode that uses the Layers framework tab classes and the jQuery tab script snippet to identify the selectors, or you must use a plugin like shortcodes ultimate. Shortcodes with jQuery elements that are styles specifically for layers will be available via an extension in the future.
Your other option is to code pure CSS tabs using a combination of the markup in this example, and our tab classes for the overall look and feel.
https://css-tricks.com/examples/CSSTabs/

**Comment by gb97** [comment]
ok, thanks for your help & suggetions.
