### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by ixlipixli** [Obox/layerswp#302]
Hi,

I am having trouble with editing a layout or the content of it.
Whenever I click on "Edit Layout"/ "Edit" I get forwarded and I see a sidebar on the left (with nothing in it but the Name of the Tempalte) and the loader in the middle, which is just spinning endlessly. I waited more than 10 minutes and nothing happened.

How can I fix this?

Thank you in advance!

**Comment by vailjoy** [comment]
Hi there,

Please see the following guide for troubleshooting the Customizer. 
http://docs.layerswp.com/doc/troubleshooting-customizer-errors/
If you continue to have issues using Layers, please post on our community support forum here:
http://docs.layerswp.com/forums/
 this just helps our developers stay focused on development tasks here on GitHub. Thank you!

**Comment by davidperel** [comment]
Hi, with WordPress 4.4 out this issue should be solved. Please take a look and let us know.

Dave
