### ISSUE TITLE
Tabs and Accordions

### ISSUE THREAD

**Issue by VadymVolos** [Obox/layerswp#303]
http://docs.layerswp.com/doc/layers-tab-widget/
http://docs.layerswp.com/doc/layers-accordion-widget/

Hi! Please add Tabs and Accordions.
I can not find them. But the instructions there.

**Comment by marcperel** [comment]
They're available here @VadymVolos http://codecanyon.net/item/layers-pro-extended-customization-for-layers/11225042

**Comment by VadymVolos** [comment]
Thank you!

In the development of a child theme is a bad thing when the topic will also depend on an extra paid plugins. The users will not like it. :(

**Comment by marcperel** [comment]
We have to break out some functionality to stay true to the promise of keeping Layers clean for building on top of I'm afraid.
