### ISSUE TITLE
Image is medium size instead of full size on a full width content widget

### ISSUE THREAD

**Issue by frabrunelle** [Obox/layerswp#307]
Hi, I was doing some tests on my staging site to upgrade to the new versions of WordPress (4.4) and Layers (1.2.10).

Everything is working well, except one small bug.

You will see it if you look at the homepage of my site: http://seasteading.staging.wpengine.com/

The first image is supposed to be in full size but after I made the update, it shows up only in medium size. So it doesn't look very sharp now.

Are you able to reproduce this issue? Thank you.

**Comment by vailjoy** [comment]
Hi there,
I am not - if the Column is set to 12/12 with the image centered, a 1280px wide image will fill the entire column without issue (the original must be at least 1000px). If you are setting a background, you should use Stretch, and then the background will still only fill the column itself which is boxed. To full the widget full width to the screen you would need to set the Widget background with Stretch enabled.

**Comment by frabrunelle** [comment]
It seems like the issue is due to the new built-in support of WordPress for responsive images: https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/.

Here is the difference between my production and staging server:

```html
<img width="1920" height="994"
src="http://seasteading.staging.wpengine.com/wp-content/uploads/2015/02/Seasteading-From-DeltaSync-Blimp-min.png"
class="attachment-layers--large size-layers--large"
alt="Seasteading From DeltaSync Blimp-min"
srcset="http://seasteading.staging.wpengine.com/wp-content/uploads/2015/02/Seasteading-From-DeltaSync-Blimp-min-300x155.png 300w, http://seasteading.staging.wpengine.com/wp-content/uploads/2015/02/Seasteading-From-DeltaSync-Blimp-min-1024x530.png 1024w"
sizes="(max-width: 1920px) 100vw, 1920px">
```

```html
<img width="1920" height="994"
src="http://seasteading.wpengine.netdna-cdn.com/wp-content/uploads/2015/02/Seasteading-From-DeltaSync-Blimp-min.png"
class="attachment-layers--large"
alt="Seasteading From DeltaSync Blimp-min">
```

so I guess the issue is not specific to Layers but I wonder if there is a way Layers can address the issue. it seems like it would be possible to control this by adding some code to Layers, but I haven't look to much at this point. it's definitely preventing me from updating to WordPress 4.4, so I'll probably have to look into it more.

1. Regenerating my images using the Regenerate Thumbnails plugin did work! Now the markup looks pretty much the same as it did before. I'll try this on my production site and see if it works too.

```html
<img width="1920" height="994"
src="http://seasteading.staging.wpengine.com/wp-content/uploads/2015/02/Seasteading-From-DeltaSync-Blimp-min.png"
class="attachment-layers--large size-layers--large"
alt="Seasteading From DeltaSync Blimp-min">
```

2. With the slider widget, the image is cropped and doesn't look as good as when I use the content widget.

**Comment by vailjoy** [comment]
We are looking into it! Thank you for the above data, it is helpful.

**Comment by vailjoy** [comment]
Hi there,

After a lot of testing we have found this to be due to your WordPress Media settings. If you go to Settings > Media, change the Medium dimensions to at least 700 by 1000 and save, then regenerate your thumbnails. The original image must be at least this wide to respond properly to image ratio settings when full width is enabled.

**Comment by frabrunelle** [comment]
OK great. I was setting the Medium setting to 800x600 as you suggested in an earlier comment.

I'll try 700x1000 next time.
