### ISSUE TITLE
Creating Widgets within Child Theme 

### ISSUE THREAD

**Issue by NorCalAl** [Obox/layerswp#31]
## Description of issue
I've followed the basic steps for the creation of my layers child theme and all works. However, I need to create a new widget for a CPT. In the parent theme, it's simple enough: add the line to init.php and copy over the post.php to CPT-NAME.php, then modify the contents. 

However, I'm not sure how that can be done within the child theme. My first question is how to reference the new widget within the init.php. Do I copy the entire file over from the parent theme (meaning updates won't update the file or will require me to copy it over and modify it - which I'm fine with)? Once that's done, will it just replace the init.php of the parent theme or do I need to link or reference it somewhere (functions.php?)?

**Comment by vailjoy** [comment]
Hi there,
We are only able to address bug reports here on Git so I apologize for the abridged response.

In short, builder widgets and CPTs need to be done through a plugin - you can't easily extend the layers_widget class from a child theme (its functions load before the parent) and you shouldn't copy any files from the core into a child theme. 

Please see http://docs.layerswp.com/ for theming guides - we hope to have more extensive documentation around creating custom builder widgets in the near future. For now, I recommend creating a normal widget using the wp_widget class that queries your CPT, and reference our framework docs for how to style the grid/content columns to look like the Posts widget, for example (you can also look at the content section of the posts widget from layers to get an idea of how it is structured)

**Comment by vailjoy** [comment]
Just wanted to update that this is available here:
http://docs.layerswp.com/development-tutorials-layers-builder-widgets/
