### ISSUE TITLE
An Small Bug in Transfer Page

### ISSUE THREAD

**Issue by sabzalian** [Obox/layerswp#310]
![layers_transfer_bug](https://cloud.githubusercontent.com/assets/16229248/11727454/ce0a15ba-9f7b-11e5-8670-67650d2e018a.jpg)

[layers_transfer_bug.zip](https://github.com/Obox/layerswp/files/58693/layers_transfer_bug.zip)

Hi, Please solve this issue:
Go to Layers Transfer Page, click on "Transfer my Pages Now" button, after completion of the transfer (100%), click on "Transfer my Pages Now" button again and again and again until one million percent! ;-)

I think it should be a disabled button after one click. 

A Zip file contains a video that shows this small bug has been attached. Please find it.

Thanks

**Comment by vailjoy** [comment]
Hi there,

Thanks for reporting this one - I can confirm the button should not be clickable again if the success message is visible.

**Comment by vailjoy** [comment]
Hi there, 
This has been solved with the intorduction of auto-revisions and the rmeoval of the transfer pages option
