### ISSUE TITLE
Button Add a Widget not available

### ISSUE THREAD

**Issue by meleshin** [Obox/layerswp#311]
After last update button Add a Widget may be sometime not available if you have long list of widgets.
If widget list has scrolling and first opening was done by Shift Click then this button will not be available.
How to reproduce (tested in Chrome, Windows 10).
1) Add a lot of widgets, so that scrolling has appeared in the left pane of Customizer (in widgets list).
2) Click Save and Publish
3) Close and reopen Customizer or press F5 for refresh page.
4) Then open any widget for editing by Shift Click (necessarily the only this way)
5) Now you can't scroll widget list on left side for viewing button Add a Widget. And also you can't view  last widgets in widget list.

**Comment by vailjoy** [comment]
Hi there,

What screen resolution are you in? In general, a Layers page should really not have so many widgets that they scroll off the sidebar - it is one indication that you have too many. This will cause the cusotmizer to become very slow and your page exports to possibly fail. With that said, the Add Widget button is part of the WordPress customizer interface so I am not sure we could resolve this.
