### ISSUE TITLE
Divide by 0 Error

### ISSUE THREAD

**Issue by sabzalian** [Obox/layerswp#312]
![bug2](https://cloud.githubusercontent.com/assets/16229248/11805338/ca061d4e-a302-11e5-9c69-6376acd1d4b4.jpg)

Hi dears,
Please find the attached screenshot. I think when we have no any Layers page, "Transfer" should be inactive because the divisor (denominator) in the percentage of progress is zero. Please go to "Transfer" section when you have no any Layers page and click on "Transfer My Pages Now" to see the result.

Thanks

**Comment by vailjoy** [comment]
I agree. Refining this interface is on our roadmap for 2016

**Comment by vailjoy** [comment]
Transfer pages has been removed and replaced with Revisions in 1.2.11
