### ISSUE TITLE
Slider load issue

### ISSUE THREAD

**Issue by FortifyFlint** [Obox/layerswp#313]
Looks like images are not loading correctly in the slider on initial site load. However, after the page loads and if you adjust the browser width (or alter phone/tablet orientation), the image appears. Attaching screenshot of initial page load compared with adjusted browser width.

On Layers 1-2-10. 

![screen shot 2015-12-21 at 10 26 47 am 2](https://cloud.githubusercontent.com/assets/7727854/11935551/0e9ec0da-a7ce-11e5-810c-a5ffd0d8605f.png)
![screen shot 2015-12-21 at 10 29 22 am 2](https://cloud.githubusercontent.com/assets/7727854/11935550/0e9c0cbe-a7ce-11e5-9655-0a6ca50c0963.png)

**Comment by vailjoy** [comment]
Hi there,

What Layout is your slider set to, and is Auto-Height slides enabled? (it shouldnt be)
