### ISSUE TITLE
'layers-trbl-fields' customizer control returns empty string

### ISSUE THREAD

**Issue by dameer** [Obox/layerswp#314]
I was playing around with 'layers-trbl-fields' customizer control (added as an enhancement since 1.2.6) and realized that it always returns empty string.
...or it's just my own lack of knowledge.
Beside, 'layers-trbl-fields' customizer control hasn't been documented at all.

Here's the test code:
```
// add new section to Site Settings panel
if( !function_exists( 'td_builder_columns' ) ) {
	
	function td_builder_columns( $sections ) {

		$section = array(
			'td-builder-columns' => array(
				'title' => esc_attr__( 'Builder Columns' , 'td' ),
				'panel' => 'site-settings',
			),
		);
	
		$sections = array_merge( $sections, $section );
		
		return $sections;
		
	}
	
}
add_filter( 'layers_customizer_sections', 'td_builder_columns', 100 );


// make some panel options...
if( !function_exists( 'td_builder_columns_settings' ) ) {
	
	function td_builder_columns_settings( $controls ) {

		$controls[ 'td-builder-columns' ] = array(
			
			'ebc-layout-custom-padding' => array(
				'label' => esc_attr__( 'Padding (px)' , 'td' ),
				'type' => 'layers-trbl-fields',
				'class'	=> 'layers-pull-top layers-pull-bottom',
			),
			
			'ebc-layout-custom-margin' => array(
				'label' => esc_attr__( 'Margin (px)' , 'td' ),
				'type' => 'layers-trbl-fields',
				'class'	=> 'layers-pull-top layers-pull-bottom',
			),
			
		);
	
		return $controls;
		
	}
}
add_filter( 'layers_customizer_controls', 'td_builder_columns_settings', 100 );


// grab customizer options
if( !function_exists( 'td_builder_columns_settings_render' ) ) {
	
	function td_builder_columns_settings_render() {
		
		$ebc_layout_custom_padding = layers_get_theme_mod( 'ebc-layout-custom-padding', FALSE );
		$ebc_layout_custom_margin  = layers_get_theme_mod( 'ebc-layout-custom-margin', FALSE );
		
        // HOW DO I GRAB 'layers-trbl-fields' VALUES ?!? ----------------------------------
		var_dump( $ebc_layout_custom_padding ); // this one ALWAYS returns an empty string
        var_dump( $ebc_layout_custom_margin );  // this one ALWAYS returns an empty string
        // --------------------------------------------------------------------------------
		
	}
	
}
add_action( 'wp_enqueue_scripts', 'td_builder_columns_settings_render', 100 );
```

**Comment by alispx** [comment]
You can try this : 
<code>
// grab customizer options
if( !function_exists( 'td_builder_columns_settings_render' ) ) {

    function td_builder_columns_settings_render() {

        $ebc_layout_custom_padding_top 		= layers_get_theme_mod( 'ebc-layout-custom-padding-top', FALSE );
        $ebc_layout_custom_padding_right 	= layers_get_theme_mod( 'ebc-layout-custom-padding-right', FALSE );
        $ebc_layout_custom_padding_bottom 	= layers_get_theme_mod( 'ebc-layout-custom-padding-bottom', FALSE );
        $ebc_layout_custom_padding_left 	= layers_get_theme_mod( 'ebc-layout-custom-padding-left', FALSE );

        $ebc_layout_custom_margin_top  		= layers_get_theme_mod( 'ebc-layout-custom-margin-top', FALSE );
        $ebc_layout_custom_margin_right  	= layers_get_theme_mod( 'ebc-layout-custom-margin-right', FALSE );
        $ebc_layout_custom_margin_bottom  	= layers_get_theme_mod( 'ebc-layout-custom-margin-bottom', FALSE );
        $ebc_layout_custom_margin_left  	= layers_get_theme_mod( 'ebc-layout-custom-margin-left', FALSE );

        // HOW DO I GRAB 'layers-trbl-fields' VALUES ?!? ----------------------------------
        var_dump( $ebc_layout_custom_padding_top ); 
        var_dump( $ebc_layout_custom_padding_right ); 
        var_dump( $ebc_layout_custom_padding_bottom ); 
        var_dump( $ebc_layout_custom_padding_left ); 

        var_dump( $ebc_layout_custom_margin_top );  
        var_dump( $ebc_layout_custom_margin_right );  
        var_dump( $ebc_layout_custom_margin_bottom );  
        var_dump( $ebc_layout_custom_margin_left );  
        // --------------------------------------------------------------------------------

    }

}
add_action( 'wp_enqueue_scripts', 'td_builder_columns_settings_render', 100 );
</code>

**Comment by dameer** [comment]
Thanks mate, already figured it out in the mean time. Here's what I came up with - in case anyone needs it:
```
// grab customizer options
if( !function_exists( 'td_builder_columns_settings_render' ) ) {

    function td_builder_columns_settings_render() {

        $ebc_layout_custom_padding = layers_get_theme_mod( 'ebc-layout-custom-padding', FALSE );
        $ebc_layout_custom_margin  = layers_get_theme_mod( 'ebc-layout-custom-margin', FALSE );

		// element to apply the settings to
		$element = '#my-element';
		
		// margin and padding
		$props = array( 'margin', 'padding' );
		$trbls = array( 'top', 'right', 'bottom', 'left' );
		
		$cnt_props = 0;
		$cnt_trbls = 0;
		
		for( $i = 0; $i < $cnt_props; $i ++ ) {
			
			for( $j = 0; $j < $cnt_trbls; $j ++ ) {
				
				$val = layers_get_theme_mod( 'ebc-layout-custom-' . $props[ $i ] . '-' . $trbls[ $j ] ); 
				
				if( isset( $val ) && '' != $val && is_numeric( $val ) ) {
					
					layers_inline_styles( array(
						'selectors' => array( 
							$element, 
						),
						'css' => array(
							$props[ $i ] . '-' . $trbls[ $j ] => $val . 'px',  
						),
					) );
					
				}
				
			}
		}

    }

}
add_action( 'wp_enqueue_scripts', 'td_builder_columns_settings_render', 100 );
```

Section and panel option functions are just fine so the above example shows how to grab these "layers-trbl-fields" values and apply it alive via customizer.
