### ISSUE TITLE
Woocommerce sidebars don't works in v1.0.4

### ISSUE THREAD

**Issue by luizbills** [Obox/layerswp#32]
Both left and right sidebars.

**Comment by vailjoy** [comment]
Hi there,
I can confirm they are currently working. Make sure you have widgets in the sidebars and try deactivating all other plugins besides WooCommerce if issues persist. See http://vailjoy.com/layers/shop/ for comparison.

**Comment by luizbills** [comment]
Right sidebar works here too. But left sidebar or both at same time, don't works.
### [Printscreens](http://drp.io/a/X16x8H-t/mJ0xIHWt/-/-)

**Comment by vailjoy** [comment]
Hi there,

I can confirm this is working in our current developement version, so it is possible it is already fixed and slated for 1.0.5. Please see the demo link above where I have enabled both sidebars (again, they must have widgets in them before you will see them)

If you have two sidebars enabled in the shop, you may use the following workaround to ensure the gutter is applied on the middle column, placed into the CSS panel in the Customizer:
 .woocommerce .span-6{margin-right: 20px !important;}

**Comment by vailjoy** [comment]
Fixed in 1.0.5
