### ISSUE TITLE
Virtual Pages not working

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#320]
As per: https://premium.wpmudev.org/forums/topic/qa-post-and-archive-display-as-normal-post-and-archive-page#post-1019241

I'm using Q&A plugin by WPMUDEV with LayersWP Theme/Framework.

The archive page layout is used and so is the post template on the virtual pages created by the plugin. It should be using the plugin templates.

WPMUDev asked me to contact layers as the theme is interfering with how Virtual Pages are templated. 

https://yogrow.co/questions/
https://yogrow.co/questions/what-is-the-best-seo-growth-hack-you-know/

Thanks

**Comment by raisonon** [comment]
This might need to be closed. I edited the WPMU plugin myself and fixed by adding prioirty to the add_filter

'		add_filter( 'single_template', array( &$this, 'handle_template' ), 15 );
		add_filter( 'archive_template', array( &$this, 'handle_template' ), 15 );'

Will feedback whether this is a correct fix or something that layers should change.

**Comment by marcperel** [comment]
Thanks @raisonon I was struggling to get to the bottom of that
