### ISSUE TITLE
Excerpt RTE content clipping

### ISSUE THREAD

**Issue by kbox** [Obox/layerswp#322]
Content Widget RTE bullet formatting overflowing and clipped.
![screenshot](https://cloud.githubusercontent.com/assets/1896386/12655361/8cacf84c-c633-11e5-8b25-dd78dbb2fc00.jpg)

**Comment by vailjoy** [comment]
Hi there,
If you copy/paste content into the widget, it can carry a lot of garbage with it that breaks the layout.
Click the code view button on the RTE and ensure there are no "&nbsp;"  Example:

<li>Give&nbsp;us&nbsp;a&nbsp;brief&nbsp;description&nbsp;of&nbsp;the&nbsp;service&nbsp;that&nbsp;you&nbsp;are&nbsp;promoting.</li>

The easiest thing to ensure wrapping is to type your content into the RTE, then style it using the tools.

Your list HTML should look like this (example):

<ul>
<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed dolor...</li>
</ul>

**Comment by kbox** [comment]
Thanks, I tried typing directly and yes that seems to be the issue. However copying and pasting is a very common thing with inserting content and should not cause a problem. Retyping really long content can be a pain so I think this still needs to be addressed. Also, if you're in code view and you close the panel it defaults to code view the next time you open it and you can no longer toggle back.

**Comment by davidperel** [comment]
Hi KBox

The reason this is happening is likely due to &nbsp; 's in the HTML. If you remove them then your sentences should break to a new line. We are investigating a solution to this with CSS however in the meanwhile I suggest checking the HTML for &nbsp's

**Comment by kbox** [comment]
If I copy and paste content then format it it automatically adds in &nbsp; to replace the spaces and I think that causes the content not wrapping.

**Comment by davidperel** [comment]
Yes, unfortunately no RTE is perfect in this regard (we tried implementing TinyMCE but it didn't work well in the customizer interface).

A fix will be out in Layers 1.2.11 on Thursday.

**Comment by kbox** [comment]
Cool. Looking forward to the update :)
