### ISSUE TITLE
Broken images in Chrome

### ISSUE THREAD

**Issue by SaulsCreative** [Obox/layerswp#325]
All my images used with the customizer are broken in chrome. The path to the image is correct but the image is broken and not displaying.

**Comment by marcperel** [comment]
This is highly likely to be related to the updates brought upon by WordPress 4.4, which you can read about here:

http://docs.layerswp.com/doc/wordpress-images-dont-load-after-4-4-update-with-ssl-enabled/

**Comment by SaulsCreative** [comment]
Thank you so much @marcperel  Works great now

**Comment by marcperel** [comment]
Awesome @SaulsCreative!
