### ISSUE TITLE
Post Widget Actions

### ISSUE THREAD

**Issue by mikedidthis** [Obox/layerswp#330]
Hi,

Firstly thanks for the hard work on Layers, its been a blast to work with.

I am using `add_action( 'layers_after_list_title', 'my_meta' )` to add the `.meta-info` to a different element on the list page.

Is there a action to do the same for the Post Widget?

**Comment by vailjoy** [comment]
Hi there,
Not currently - you would need to filter layers_post_meta(), or if you just want to change the position of the meta element, use CSS and absolute positioning to put it elsewhere in the column.  Adding actions to widgets is on our agenda, but something we are waiting to do until some more heavy changes and optimizations are implemented.
