### ISSUE TITLE
Category (subcategory)

### ISSUE THREAD

**Issue by vadimssh** [Obox/layerswp#334]
Dear Layers team,
![catalog 2](https://cloud.githubusercontent.com/assets/17766072/13672582/24945f36-e6de-11e5-8f8e-358a0831ea41.png)

I have an issue with directory(product catalog). How i can fold catalog by main category. I mean, can I display only main category here without subcategory? Thank you!

**Comment by vailjoy** [comment]
Hi there,

When building your menu in the customizer or Appearance > Menus screen, you can add product categories to the menu where it should only show the category name, or you can set a custom label for the menu link. If you are using a different plugin to generate this menu, you will need to contact the plugin author.
