### ISSUE TITLE
Support for WPML translations

### ISSUE THREAD

**Issue by jesucarr** [Obox/layerswp#335]
When translating a Layers page using the WPML plugin, the page gets duplicated to the new language, but not the widgets, so the resulting page is empty in the new language. It would be necessary to export/import the content for each new language. Is there a way to make that happen automatically, or is there a better workflow?

**Comment by vailjoy** [comment]
Hi there,
WPML is only able to support translation of standard widget titles using the String Translation extension. For content in Layers widgets, etc, you must translate text you enter by hand. Please see the following:
http://docs.layerswp.com/doc/how-to-translate-widgets-or-display-different-widgets-per-language/
https://wpml.org/2011/03/howto-display-different-widgets-per-language/

**Comment by jesucarr** [comment]
Thanks for the Duplicate function in the Layers page suggestion. After doing that you can change the language and connect it to the original language. A bit annoying the extra steps and to remember to not use the WPML usual workflow, but it works. I'd suggest to integrate with them better.

**Comment by vailjoy** [comment]
Hi there,
Just to clarify, there is nothing we can do to make this better - it is a limitation in WPML.
