### ISSUE TITLE
Issue: Layers Icon CSS loads and overrides other plugins icons

### ISSUE THREAD

**Issue by brandbrilliance** [Obox/layerswp#337]
## Description of issue
Layers loads all their JS and CSS for any admin page and therefore other extensions that user the [icon-] class gets messed up. Caldera Forms is a primary example. Caldera forms loads their icons only when their admin page is up and running, but layers' (!important) tag overrides it and the wrong icons appear in their interface. 

![layers-css-bug](https://cloud.githubusercontent.com/assets/1362479/14104277/9c4e8702-f5a4-11e5-9a23-0380549e37ca.jpg)

## URL of page exhibiting the issue
Any Wordpress admin installation with multiple plugins installed.

## Web Browsers that exhibit the issue
Any

## Error Message or Steps to Recreate
Load Layers and Caldera Forms, Look at the "remove" icon on the left of a row, and that actually shows the layers icon instead. 

## Steps to fix the issue
Layers should determine which admin pages it's on and lazy load their JS/CSS and other bits which are only needed in the customizer section and/or their own admin pages. It should never load anything layers in the admin interface otherwise, it also just slows down the admin interface to load everything when not needed.

**Comment by vailjoy** [comment]
Please see https://github.com/Obox/layerswp/issues/108
