### ISSUE TITLE
Issue: Widget Background Darken Option Unused (content/slider)

### ISSUE THREAD

**Issue by brandbrilliance** [Obox/layerswp#338]
## Description of issue
Both the Content and Slider Widgets have a "darken" option, but it doesn't generate any code, classes when you check it, nor is it used anywhere in the actual code of the widget. I thought it would generate a class on an additional overlay element, similar to what the slider does on each of the slides.

## URL of page exhibiting the issue
N/A

## Web Browsers that exhibit the issue
N/A

## Error Message or Steps to Recreate
Darken checkbox on Widget Settings has no effect/used.

![layers-widget-darken](https://cloud.githubusercontent.com/assets/1362479/14109497/9e338374-f5c2-11e5-9854-ec8de5f5385a.jpg)

**Comment by vailjoy** [comment]
The slider darken works in 1.2.14. The Content Widget darken has been fixed in 1.5. If you are a developer, you can access the RC1 branch and download to test.

**Comment by brandbrilliance** [comment]
Note that this ISN'T on the actual elements, but on the MAIN SECTION (right side). The elements do work, e.g. slides
