### ISSUE TITLE
Hello! I've just installaed Layers like a normal theme but the customizer icons are missing! When i try to customize my website, there are no icons!  Here's a little screenshot to understand the problem: http://imgur.com/ETnh6C2 What can i do? i reinstalled layers with filezilla too and tried with another browser...But nothing change!

### ISSUE THREAD

**Issue by Gangatmb** [Obox/layerswp#34]

**Comment by AndreasWebdev** [comment]
Do you access via http or https? It seems like the Icon Font does not load propertly!

**Comment by Gangatmb** [comment]
how can i check it? when i try to customize the website, my url is just http://www.alessandrolagasca.it/wp-admin/customize.php

**Comment by AndreasWebdev** [comment]
Alright. Please upload this test.htm file on your host: https://github.com/AndreasWebdev/FontsDebug/
Its a little page I've written. It contains a normal font and an icon font to test if this is what the problem causes.

**Comment by Gangatmb** [comment]
done! but.. what am i supposed to do now? how can i see that page while using layers? If i open you file with a browser, i can perfectly see thos icons, but i don't know how to open that page inside wordpress :) sorry for my nooby question! i'll add a screenshot of my ftp right now http://imgur.com/lwGDlci
Thank you for you help mate!

**Comment by Gangatmb** [comment]
news: I've uploaded Layers on another host, altervista.org and everything is working http://imgur.com/4cDLzDI
How is possible? I've payed for a one year host, where i'm experiencing that issue :(

**Comment by AndreasWebdev** [comment]
Try going on the test.htm page and post a screenshot..

**Comment by Gangatmb** [comment]
If i go on that page, it seems working :O http://imgur.com/txCCSOb

**Comment by AndreasWebdev** [comment]
Alright.. It seems like its not a general problem with your computer nor browser nor server. The question is: Why does the iconfont that on your wordpress installation?

Could you check the wordpress settings of your page and the altervista.org installation of wordpress? Maybe there is something wrong..

**Comment by Gangatmb** [comment]
First, thank you for your awesome help :)
Secondo, i'll explain better: the last screen, from altervista.org, was just a test on that hosting service (which is free) and where everything works properly. I personally use a different hosting, which is http://www.tophost.it/th/index.php and where i can't still see thos icons in the customizer. Here, i've also tried to reinstall wordpress via ftp. Are there other kind of installation, or something?

**Comment by gbonanome** [comment]
I have the same issue on the server, while on my local machine there are no problem with fonts.

I think is a server problem with MIME types, because I have a 404 error on woff and ttf fonts while the file are there with the correct permissions.

![schermata 2015-03-18 alle 12 21 04](https://cloud.githubusercontent.com/assets/1076656/6707658/50bf8462-cd69-11e4-9ed1-a72fe28b0be2.png)

Sadly I don't know how to solve the problem :disappointed: I've checked the server and it seems to me that the machine is capable of recognize the MIME types. There could be an apache module to activate?

**Comment by Gangatmb** [comment]
Glad to see that i'm not the only one who has this kind of problem :) Anyway, i'm italian too, nice to meet you!
As i mentioned, i didn't have problems with altervista's host and a friend of mine told me that it works properly on aruba server.
Which kind of host are you using right now? My host answered me with a beautiful message like "We don't know how you can solve the problem...just change theme!" Thaaaank you -.-'

**Comment by gbonanome** [comment]
I'm using dominiok.it and the only quick&dirt fix is to change how fonts are provided by @font-face

You have to change [/core/assets/icons.css](https://github.com/Obox/layerswp/blob/master/core/assets/icons.css) and [/assets/css/layers-icons.css](https://github.com/Obox/layerswp/blob/master/assets/css/layers-icons.css) removing the [*bulletproof* syntax](http://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/). So cut away the ending *?-f3u2tk* and *?-5q4unt*

For example my resulting icons.css start as the following
```
@font-face {
	font-family: 'layers-interface';
	src:url('fonts/layers-interface.eot');
	src:url('fonts/layers-interface.eot?#iefix') format('embedded-opentype'),
		url('fonts/layers-interface.woff') format('woff'),
		url('fonts/layers-interface.ttf') format('truetype'),
		url('fonts/layers-interface.svg?#layers-interface') format('svg');
	font-weight: normal;
	font-style: normal;
}
```

I don't like this solution, and maybe there's a better way to handle this syntax with correct MIME types.

**Comment by Gangatmb** [comment]
DONE!!! Thank you so much man !!!! PERFECT
