### ISSUE TITLE
[Warning] Invalid CSS property declaration at: ; (responsive.css, line 32)

### ISSUE THREAD

**Issue by easterncoder** [Obox/layerswp#343]
I'm getting this CSS warning in Safari on Mac
`[Warning] Invalid CSS property declaration at: ; (responsive.css, line 32)`

Attached is a patch that corrects this.

Thanks.

[assets_css_responsive.css.patch.zip](https://github.com/Obox/layerswp/files/225763/assets_css_responsive.css.patch.zip)

**Comment by vailjoy** [comment]
Hi there,
Please send us a pull request with fixes or create a gist with the updated code and link here, thanks!

**Comment by easterncoder** [comment]
Looks like the updates made to responsive.css makes this moot. Closing this now.
