### ISSUE TITLE
Sticky Header Issues

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#35]
Two issues

- If Top Nav Bar enabled by selecting a top left and top right menu, then on scroll the margin-top:30px is still active. (.admin-bar .header-sticky.is_stuck.is_stuck_show)
- On first scroll down, the sticky does not follow. On second it does, but is not smooth.

**Comment by vailjoy** [comment]
Hi there,

The top bar is hidden on scroll on purpose and is not affected by the sticky setting. I have it working as expected here, can you take a look for comparison?
http://vailjoy.com/layers/

**Comment by raisonon** [comment]
Ok, you are right. I have my own plugin I use for development which puts the wpadminbar at the bottom of the page. I use: 

#wpadminbar {
  top: auto !important;
  bottom: 0;
  position: fixed;
}

When this CSS is added then you get the issue. Maybe best to close this, as I might be the only one who prefers admin bar at the bottom.

Screenshot: https://www.dropbox.com/s/cc68vx3nh53cqm5/Screenshot%202015-03-11%2010.36.07.png?dl=0
