### ISSUE TITLE
LayersWP Pro Tabs module: changing text size does nothing

### ISSUE THREAD

**Issue by molul** [Obox/layerswp#352]
When I change the text size in a tab widget (see screenshot), nothing changes.

![tabsbug](https://cloud.githubusercontent.com/assets/2084933/15039160/c88891fa-12aa-11e6-92af-bded0b535fe8.png)

I'm using latest version of LayersWP, 1.5.

**Comment by vailjoy** [comment]
Please give feedback or request help for Layers Pro via Layers Messenger. This repo and tracking system are for Layers free project only. Thanks!

Ensure Layers has been updated to 1.5.1 and Layers Pro to 1.6.2.
