### ISSUE TITLE
Tabs module needs more customization

### ISSUE THREAD

**Issue by molul** [Obox/layerswp#353]
The tabs module is very useful, although I'm afraid I expected more. You can change the background colour and stuff, but I miss the following:

-Being able to choose all tabs titles' colour, idle and mouseover.
-Being able to choose all tabs titles' background colour, idle and mouseover.
-Being able to choose tabs position: left (currently the only option), center (the one I want to use) and right.
-Being able to choose the tabs content text colour.
-Being able to choose the tabs content text size.
-Smooth size transition when changing between two tabs with different height.

**Comment by marcperel** [comment]
Thanks nice suggestions @molul I think we've chosen to really iterate on this and the accordion widget, reason being that we weren't sure exactly what users would be creating with them.

**Comment by molul** [comment]
Nice! Glad to help :)
