### ISSUE TITLE
Layers 1.5 broke a web form I had in the footer

### ISSUE THREAD

**Issue by molul** [Obox/layerswp#355]
Hi. I had a contact form in the footer. The form was built from our CRM, so anyone that uses it, gets added to our leads database. The html code is like this (removing the company's references):

<div id="externalWebForm"><script type="text/javascript" src="MY FORM URL"></script></div>

It worked fine until version 1.5. Now, when I save the page, this code is rewritten as <div id="externalWebForm"></div>, removing the <script> part that loaded the form.

Could you please take a look at this issue?

**Comment by vailjoy** [comment]
Please give feedback or request help for Layers Pro via Layers Messenger. This repo and tracking system are for Layers free project only. Thanks!
