### ISSUE TITLE
LayersWP Pro 1.5: Posts carousel widget don't show dots

### ISSUE THREAD

**Issue by molul** [Obox/layerswp#356]
I have a Posts carousel in my home page. It is configured to show dots but they won't show up. I can see the div with classes "swiper-pagination swiper-pagination-clickable swiper-pagination-bullets", but I think they're placed wrong, as they're inside a div but the dots div position is outside the parent div bounds, thus not showing unless I change its position to be inside the bounds.

This happens in Firefox and Chrome.

**Comment by vailjoy** [comment]
Please give feedback or request help for Layers Pro via Layers Messenger. This repo and tracking system are for Layers free project only. Thanks!
