### ISSUE TITLE
LayersWP Pro 1.5: posts in posts carousel are cut

### ISSUE THREAD

**Issue by molul** [Obox/layerswp#357]
Hi. In customizer, the posts carousel looks fine (except that dots are hidden), but when I view the page, the posts carousel has been cut. Also, if I right-click one of the post and select "Inspect element", all posts suddenly resize to the right height.

When page is loaded:
![1](https://cloud.githubusercontent.com/assets/2084933/15112193/cdd2640c-15ec-11e6-8a25-70dd12e8264b.png)

After clicking on "Inspect element":
![2](https://cloud.githubusercontent.com/assets/2084933/15112192/cdced698-15ec-11e6-8e8c-1b6e703bf695.png)

**Comment by vailjoy** [comment]
Please give feedback or request help for Layers Pro via Layers Messenger. This repo and tracking system are for Layers free project only. Thanks!

**Comment by vailjoy** [comment]
Please give feedback or request help for Layers Pro via Layers Messenger. This repo and tracking system are for Layers free project only. Thanks!
