### ISSUE TITLE
LayerWP Pro 1.5 - Posts carousel widget: clicking on a post in the carousel does nothing on Chrome

### ISSUE THREAD

**Issue by molul** [Obox/layerswp#358]
Not much else to say: when I click on any of the posts in a posts carousel, although a link is detected (I can see the url at the bottom of the window), the link is not open.

Lots of bugs in the Posts carousel widget so far :(

EDIT: it only happens in Chrome. It's alright on Firefox.

**Comment by vailjoy** [comment]
Please give feedback or request help for Layers Pro via Layers Messenger. This repo and tracking system are for Layers free project only. Thanks!


I can confirm the carousel is working fine in the current version of Layers Pro. Ensure Layers is at 1.5.1 and Layers Pro has bveen updated to 1.6.2
