### ISSUE TITLE
LayersWP Pro 1.5: Tabs should turn into accordion in mobile

### ISSUE THREAD

**Issue by molul** [Obox/layerswp#359]
While tabs widget works fine in mobile, it looks a bit weird, as all tabs are together and the selected tab content always appears below the last tab. I think it would be better that tabs were converted to accordion in mobile, as the current mobile view looks weird.

**Comment by vailjoy** [comment]
Hi there,

Please report any bugs or issues with Layers Pro via Layers Messenger. This repo and issue tracking are for the Layers core theme only. Thanks!
