### ISSUE TITLE
WooCommerce Grouped Produt

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#36]
WooCommerce Grouped Products label is all black.

See screenshot: https://www.dropbox.com/s/lmp4985wzwvzdqz/Screenshot%202015-03-11%2012.41.21.png?dl=0

**Comment by vailjoy** [comment]
Hi there,

Ask a workaround, add the following to the CSS panel in the Customizer:
.product-type-grouped .cart .label {
  vertical-align: middle;
  padding: 10px;
  background: transparent;
}
.product-type-grouped .cart .price {
  display: table-cell;
  vertical-align: middle;
}

**Comment by davidperel** [comment]
Hi Raisonon

I've created a fix that is handled better on a global level, it will be pushed in next weeks update. In the meanwhile I'd suggest using this CSS:

    table td.label{
        background: none;
        vertical-align: middle;
    }
    table td.label label{
        margin: 0;
    }
    table td.price{
        display: table-cell;
        vertical-align: middle;
    }

Dave

**Comment by vailjoy** [comment]
Fixed in 1.0.5
