### ISSUE TITLE
Fullscreen slider initially loads incorrectly with overlay menu

### ISSUE THREAD

**Issue by SeagynDL** [Obox/layerswp#361]
If I use a fullscreen slider with a transparent overlay menu it doesn't load the fullscreen slider correctly. The slider seems like it initially loads below the menu and then does not shift below it and thus when you scroll down you see more of the slider without the overlay.

Example: http://new.riverschurch.co.za/

**Comment by marcperel** [comment]
Thanks @SeagynDL , it looks like we'll have to fire the event on load as well as resize.

**Comment by SeagynDL** [comment]
Great, thanks Marc. Is there any way to prevent the menu from showing a
solid background until the load event is fired?

**Comment by marcperel** [comment]
That's actually a separate issue, the issue you're referring to is a delay in the CSS loading order, which is very difficult to get right!

**Comment by SeagynDL** [comment]
Hey Marc, is the fix for the first issue going to be rolled out or do you still need a fix for it? I can jump into it if needed.

**Comment by vailjoy** [comment]
Hi there,
This should be solved with Layers 1.5.4. Please also ensure any Layers extensions you may be running, as well as DevKit, have been updated.
