### ISSUE TITLE
Hidden Mobile Menu overlay z-index overlaps footer links and stops them working (on right of page)

### ISSUE THREAD

**Issue by raisonon** [Obox/layerswp#369]
Try clicking on the footer links on the right here: https://yogrow.co

You'll see that <div class="wrapper invert off-canvas-right" is overlayed on this and stops the links from working. Perhaps only set the z-index of this div when it is displayed...

Thanks

**Comment by vailjoy** [comment]
Hello,
This does not happen by design (the menu shoves the entire content wrapper over)
http://design.google.com/resizer/#url=http%3A%2F%2Flayerswp.com

Have you tried testing it with your child theme deactivated?
