### ISSUE TITLE
Post widget Export data missing in josn

### ISSUE THREAD

**Issue by inkcolor** [Obox/layerswp#370]
Hi, reporting this issue after testing many times on fresh installation without any changes on layerswp.
1. Created page using layers wp default widget. content, slider and post
2. save ever tying properly.
3. export json file
4. now install new fresh wordpress with layerswp.
5. importing json file which was backed-up before.
6. everything looks good, but post widget missing after importing json.

Thanks

**Comment by vailjoy** [comment]
Hi there,
I am able to export a page and have the post widget come across OK. Can you get in touch with us via Layers Messenger from the affected install so we can troubleshoot? At the most basic ensure all the theme and plugin versions on the site you are exporting from are updated, as well as the site you are exporting to.
