### ISSUE TITLE
How to add a search box in the header?

### ISSUE THREAD

**Issue by danielchicote** [Obox/layerswp#38]
Hello, i want to add a search box before the header menu. Is needed to code it by hand? Excuse me if this is above documented, but i cant find it.

Congratulations for your framework, in my opinion are simply EXCEPTIONAL and have a great future.

**Comment by danielchicote** [comment]
Excuses: http://docs.layerswp.com/help/question/3006/how-can-i-add-a-search-box-to-the-header-area/

**Comment by marcperel** [comment]
Daniel, we'll have a look at our
