### ISSUE TITLE
Please replace the author name with author first name and last name

### ISSUE THREAD

**Issue by debasiskoley** [Obox/layerswp#385]
Please change the core function 

function layers_get_the_author() {
    $author_fname = get_the_author_meta('first_name');
    $author_lname = get_the_author_meta('last_name');
        return sprintf( __( '<a href="%1$s" title="%2$s" rel="author" class="layers-author">%3$s</a>' , 'cross' ),
            esc_url( get_author_posts_url( get_the_author_meta( 'ID' ) ) ),
            esc_attr( sprintf( __( 'View all posts by %s', 'cross' ), trim( "$author_fname $author_lname" ) ) ), //;get_the_author()
            esc_attr( trim( "$author_fname $author_lname" ) ) //get_the_author()
        );
    }
// layers_get_the_author

**Comment by vailjoy** [comment]
Hi there,
We use the WordPress default so that users can control this from within WordPress or other plugins.
