### ISSUE TITLE
Shortcodes not working

### ISSUE THREAD

**Issue by devzing** [Obox/layerswp#4]
Are shortcodes supported? I can't seem to get them to work.

**Comment by marcperel** [comment]
Hey Wayne,

Which widget are you using? They 'should work' but there could be a bug there.

~ Marc

**Comment by devzing** [comment]
I was trying in a Content widget. I was trying in the "short excerpt"

Playing around a bit more shows that it only works in the column excerpt.
Seems like it should work in both.

Thanks,
Wayne

On Fri, Feb 20, 2015 at 8:01 PM, marcperel <notifications@github.com> wrote:

> Hey Wayne,
>
> Which widget are you using? They 'should work' but there could be a bug
> there.
>
> ~ Marc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Obox/layerswp/issues/4#issuecomment-75354486>.
>



-- 
devZing.com <http://devzing.com/> - Development Infrastructure On Demand

**Comment by marcperel** [comment]
Yeah that's definitely something we will test and add to the 1.0.3 release.

**Comment by devzing** [comment]
Nice. Thanks.

On Saturday, February 21, 2015, marcperel <notifications@github.com> wrote:

> Yeah that's definitely something we will test and add to the 1.0.3 release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Obox/layerswp/issues/4#issuecomment-75361649>.
>


-- 
devZing.com <http://devzing.com/> - Development Infrastructure On Demand
