### ISSUE TITLE
Post widget error when using tags

### ISSUE THREAD

**Issue by Webtica** [Obox/layerswp#407]
Hi, 
I was working on a client site yesterday and i got some problems when posting and using tags. 
When i disable tags , categories and author the problem goes away. 
I have the same issue on the post page itself. 
This is a problem regarding my serverpilot hosting setup because when i try it on my local install it works fine. i am using PHP 7.1 and Mysql 5.7 just so you know.
Hope this helps fix this issue. 

Thanks
Dieter 

![1](https://cloud.githubusercontent.com/assets/26842388/25004637/a6f6fed2-2055-11e7-91f1-ed89e6097d32.png)
![2](https://cloud.githubusercontent.com/assets/26842388/25004638/a6f899ae-2055-11e7-9c95-5525cb3a8102.png)

**Comment by marcperel** [comment]
I've just added some code which should fix this in the next release @Webtica

**Comment by Webtica** [comment]
Great! 
I'll close the issue for now.
I'll try again once released and if the issue returns i'll let you know Marc :-) 

Have a great week! 
Dieter

**Comment by Webtica** [comment]
Tested it and it fixed the problem 👍 :-)
