### ISSUE TITLE
Google Font - Works Sans

### ISSUE THREAD

**Issue by Webtica** [Obox/layerswp#408]
Hi , 

Is it possible to add Work sans to layers in a next update? 
Is it possible to manually add google fonts if they get released, where would i do this? 
https://fonts.google.com/specimen/Work+Sans

Thanks 
Dieter

**Comment by marcperel** [comment]
Just pushed it to `develop` @Webtica

**Comment by Webtica** [comment]
Thanks Marc! 
Did you get to check the other issue i posted about the tags and categories in posts? 

Kind regards 
Dieter

**Comment by Webtica** [comment]
Fixed!
