### ISSUE TITLE
Setup Widget Defaults for header_excerpt

### ISSUE THREAD

**Issue by slaving** [Obox/layerswp#409]
header_excerpt defaults not updated in related widgets

**Comment by marcperel** [comment]
Hey @slaving can you elaborate more on this?

**Comment by slaving** [comment]
For example:
wp-content/themes/layerswp/core/widgets/modules/content.php:67

Still 'fonts', but it should be 'header_excerpt'

And it would be great to separate the function for defaults (set_defaults) for override in custom widgets.

**Comment by slaving** [comment]
became irrelevant
