### ISSUE TITLE
layerswp.com Not Allowing Any Downloads

### ISSUE THREAD

**Issue by schmuckinsurance** [Obox/layerswp#424]
I have an account on your site, have purchased a number of themes/plugins, and cannot access any of my downloads. The download links on my account page take me to the homepage and the download links on the homepage take me to my account page. Also, I found it odd that the latest theme version showing was 2.0.5...Did you restore a backup by chance?

**Comment by marcperel** [comment]
Thanks @schmuckinsurance we're fixing it right away!

**Comment by marcperel** [comment]
This has been fixed +1
