### ISSUE TITLE
Warning: Cannot modify header information

### ISSUE THREAD

**Issue by vmcosta** [Obox/layerswp#47]
Hi Guys, awesome product, thanks for doing it.

I'm having some issues trying to export layouts from a page, when I export a page I'm getting the above warnings, you can check what I mean in the screenshot attached.

New install and running latest version of WP.

![screen shot 2015-03-20 at 11 04 04](https://cloud.githubusercontent.com/assets/1929920/6750323/f340132c-cef0-11e4-962a-486a01285945.png)

**Comment by marcperel** [comment]
Hi Victor,

Thanks for bringing this up, which browser are you using to export your files? It should simply download a JSON file rater than spit out all those errors.

**Comment by vmcosta** [comment]
Hi Marc, 

I'm using latest Safari version Version 8.0.4 (10600.4.10.7). 
Also tested with Google Chrome with no luck.

**Comment by marcperel** [comment]
Thanks Victor, we'll investigate the issue!

**Comment by vmcosta** [comment]
Marc, It seams that the latest version 1.0.6 fixed the issue, I'm now able to export.

**Comment by vmcosta** [comment]
For the ones having this issue, what I did was place this code at the top after the opening <?php tag in wp-config.php `ob_start();` It is working nice for me again.

**Comment by gthapar** [comment]
Facing the same issue! You can't expect every user to put `ob_start();` in config file.

Google Chrome
Version 41.0.2272.118 (64-bit)

**Comment by marcperel** [comment]
@gthapar have you updated to the latest version of Layers? We released a fix for the issue on Thursday.

~ Marc

**Comment by gthapar** [comment]
Oops! my mistake.. I was running v1.0.6.

Any safe way to upgrade? I replaced older version with new but now my saved pages seem to have cleared (only WP default widgets appear).

**Comment by gthapar** [comment]
I was using landing page template but now everything gone. See the screenshot below -

![screen shot 2015-04-05 at 6 06 50 pm](https://cloud.githubusercontent.com/assets/4481867/6996837/a12304fc-dbbe-11e4-8d85-b7bc0023a435.png)

**Comment by gthapar** [comment]
Tried older version again but no luck. All content gone.. :(

**Comment by marcperel** [comment]
Hi @gthapar,

When you ran the update did you change themes at all?

Next check, if you hover the Layers menu in WP-admin do you see the *Layers Pages* menu?

**Comment by gthapar** [comment]
I just replaced the files. Didn't use the updater plugin.

Yes, I do see Layers Pages menu. Clicking it redirects to normal WP page post type.

**Comment by gthapar** [comment]
And I had to re-activate the theme.

**Comment by marcperel** [comment]
Regarding the page menu, if the theme did not register any Layers Pages it would not have shown.

Having to re-activate the theme may have been the issue. Last question is what version of WordPress are you running?

**Comment by gthapar** [comment]
Running 4.1.1
