### ISSUE TITLE
JSON: Sorry, this file type is not permitted for security reasons.

### ISSUE THREAD

**Issue by surjithctly** [Obox/layerswp#48]
When uploading a json file as part of Importing Style Kit, It shows an error in the media manager.

`Sorry, this file type is not permitted for security reasons. `

It seems wordpress does not allow json mime type by default. or Is it caused by any other configuration?

I'm on Localhost => WP 4.1.1

**Comment by marcperel** [comment]
Hi Surjith,

We've noted an issue with this and will push an update to fix the issue soon.

Thanks

**Comment by surjithctly** [comment]
Awesome. 

While you are here, Is there any sample Style Kit to download? Currently its hard to find out what a StyleKit will look like.

**Comment by vailjoy** [comment]
Please reference the following if you have a multi-site install: http://docs.layerswp.com/doc/cannot-import-style-kit-preset-json-file-sorry-this-file-type-is-not-permitted-for-security-reasons/

You can find a complete guide for creating kits here:
http://docs.layerswp.com/doc/how-to-create-a-style-kit/

The example kit is linked near the end. You may also find additional tutorials specific to CSS customization here:
http://docs.layerswp.com/product/style-kits/?submit=Go

**Comment by surjithctly** [comment]
@vailjoy But I don't have a multi-site settings. Also, The URL seems denied to me.

"The example kit is linked near the end. " <== Are you sure? I can't find it in the given link. May be I'm overlooked? 

Also, In the doc, its mentioned that we can copy Read Me from Crayon-xxxxx, no idea how to find that file because it is also not a link :( 

Thanks for helping out.

**Comment by surjithctly** [comment]
Got the example kit.. I just tried the last link :)

**Comment by gthapar** [comment]
Upload & Import does nothing even after json file is uploaded to the media uploader.

**Comment by webwarrior** [comment]
Any updates on this?

**Comment by mmcduffie1** [comment]
Any updates on this? I am having this issue on the current Wordpress and most current Layers via the website. Not a git pull.
