### ISSUE TITLE
Image Error while importing StyleKit

### ISSUE THREAD

**Issue by surjithctly** [Obox/layerswp#49]
When importing a stylekit, Image may fail to load. That's normal and you have said there is another way. Like importing manually from Media.

But this will not work incase of WordPress. Because WordPress stores images as /YEAR/MONTH format. 

for example : You ave created Kitten Stylekit and uploaded the image in /2015/3. So when Importing xml and json, the image path stored in XML is

`http://localhost/layers/layersapp/wp-content/sites/2015/3/name.jpg`

Now I'm importing the Stylekit after months, eg: /2015/4

As, the import image from xml fails because its localhost URL, So As per the instructions, I manually add images to my wordpress, But it will stored in /2015/4

So, Images with /2015/03/ will not work. We may need to manually add every image, and I tried with your demo kit, Its really hard for me as an Author. Then no need to mention about normal users.

Also, You have created the style kit from localhost, where the path is  localhost/layers/layersapp/

And the user is importing it to localhost/awesomeco/ 

In this case, The Image URL in the JSON & CSS fail again, because there you have given absolute URL of your local project path where users path is entirely different.

So, Please find a solution for this, I'm creating a StyleKit, and this is main function user have to do, and they may get angry when didn't find as we shown in the demo.

Also, The import process is very long. I suggest you to make it even more simple like just upload a ZIP file containing JS, Images, CSS. and everything will be done automatically.

**Comment by marcperel** [comment]
Hi Surjith,

Thanks for the run down. I'll address some of your issues.

1. In theory the /year/month/ should not be a problem as the code searches for the last part of the image URL, ie. 'name.jpg' is what will be searched for in the database. So in theory if you upload all the images it should match them to your own database.

``public function check_for_image_in_media( $image_url = NULL ){
		global $wpdb;

		if( NULL == $image_url ) return;

		$image_pieces = explode( '/', $image_url );

		$i = $image_pieces[count($image_pieces)-1];

		return $wpdb->get_var( $wpdb->prepare( "SELECT ID FROM {$wpdb->posts} WHERE guid LIKE %s", "%$i%" ) );
	}``

2. We are looking at ways to improve Stylekit imports, not just for the preset Layouts but for customizer options too. It's certainly high on our roadmap priorities.

**Comment by surjithctly** [comment]
Yeah. I'm confused to see that some of the images are loaded but some not. 

Also, Is that same for CSS too? where you have used abolute URL. it will not change right?

FYI : Here is the screenshot of page I got when I imported. Is this normal? There are some images and text missing.. 

http://i.imgur.com/t83Kpjf.png

**Comment by vailjoy** [comment]
Hi there,
The screenshot indicates you grabbed a version of the demo file that was there for about 5 minutes. How unlucky! Please check this tutorial again and download the current file. That file contains a live XML and remotely hosted images, which should import correctly. 

http://docs.layerswp.com/doc/how-to-import-a-style-kit/

On the upside, you can see firsthand what will happen if the kit is not staged from a live server :)

Images set by custom css will have to be uploaded manually and the path changed in the imported CSS, so it is really best if the images are remotely hosted.There is no way around this. We discourage extensive image replacement in style kit css for this reason - if the css customization is too extensive, it is probably time for a child theme!  In the example, the button images are hosted by google and apple respectively so should come through on your new import.

**Comment by surjithctly** [comment]
@vailjoy Much better. But still missing the header, pink bg and kitten images.

It seems the previous settings is not replaced with the new settings. Is it happened because of that?

When I imported new json, the CSS I added yesterday was there. No changes.

Is there any way to reset the Layers Theme to default? 

Thanks for helping out..

**Comment by vailjoy** [comment]
Hi there,
I have redone the demo kit completely, which you can grab here:

http://docs.layerswp.com/wp-content/uploads/2015/03/demo_layers-style-kit.zip

You should always import pages to a fresh page, never import it over the top of an existing page.
To reset Layers, you can drop all your database files, then go to yoursite.com/install.php to reinitialize setup, or you can just click on Posts, delete all, empty trash, delete pages, empty trash, then delete categories and empty trash.

If your kit is going to be sold or distributed to the public, it should really be staged on a live server so the media can be imported automatically. If there is no internet, they must import the xml without clicking the import media box, then go to the media library, add new, select all in the images folder, and upload manually, THEN import the pages.

**Comment by surjithctly** [comment]
Great. I will have a look.

Regarding this : 
"You should always import pages to a fresh page, never import it over the top of an existing page."

I have removed all pages, but the customizations stays same.

Ex : I created Home Page => Customized and added a custom CSS
      I deleted Home Page
     Again, I created new Home Page => The previous settings were intact.

Is this usual?

Thank you for your help.

**Comment by vailjoy** [comment]
Are you emptying the trash?
I still can't reproduce this but I'll keep trying :}

The style kit process has been smoothed out a bit this week so it should continue to get better

**Comment by surjithctly** [comment]
I mean those settings we need to do manually?

Site Settings:

    Logo & Title: Custom Logo with text option unchecked
    Fonts: Open Sans for the Body and Buttons, and Montserrat for the headings.

Header:

    Boxed
    Logo Left
    Sticky
    Background Color - Clear

Footer:

    Boxed
    Widget Areas: None
    Text & Link Color: #cccccc
    Background Color: #494949


I'm not sure why these settings are not saved with the export. Then What's actually we are exporting? Its very long and time consuming to import a stylekit and make it running. I tried to push this from my local to live server and it took  me more than half an hour to complete the process. (includes plugin installations etc.) Now no need to mention a normal end user :(

Please make the process simple, Only then it will be easy for end users. Otherwise we will end up receiving N number of support requests and One star rating.

I really liked the product and you guys are done a very good job. But need to work more to get this work.

**Comment by vailjoy** [comment]
Hi there,

The export currently only saves Page-specific data. The Site settings, header and footer are global. We are looking into good options for creating a single export that saves the entire set of data to help expedite kit creation. 

For now, the readme should be giving advice for how to setup the theme, not defining these settings. Style Kits are intended as styling for presentation only and need to work with all header, footer and site settings/allow the user to choose whatever they want there. When your customization begins to get into needing to specify customizer defaults or layouts, then a child theme is more appropriate and provides a function for setting up defaults. Hope that helps!
