### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by em-** [Obox/layerswp#5]
You state that your code falls under GPLv2, but then proceed with stating that the license forbids others from "Publicly sell Child Themes or Extensions derived from or based on Layers outside of approved marketplaces" which sounds quite wrong.

Note that RMS himself and the FSF used to sell copies of GPL-licensed software on floppy disks some time back, thus I'm quite sure the GPL does *not* prevent people from selling GPL software even if I'm not a lawyer. What the GPL forbids is to sell compiled/obfuscated software without it being accompanied by the original source code (it talks about the "preferred form of modification", IIRC): given that this is PHP, this means that the software distributed only needs to have the non-minified source for every module it ships.

Note that none of the OSS license prevents people from re-selling the licensed software: in fact, adding such a requirement would make it definitely non Open Source (again, I'm not a lawyer, but I'm pretty sure this is the case).

**Comment by em-** [comment]
Oh, you may look at the [Affero GPL](http://www.gnu.org/licenses/agpl-3.0.html) which may be better suited to code meant for remote consumption (even if my **strong** recommendation would be to just use the same license as Wordpress, using a license shared with the ecosystem usually gives better results).

Oh, btw, nice project! :)

**Comment by vailjoy** [comment]
Hi there,

Thanks for your feedback! The license is based on WordPress requirements and has been reviewed by our legal contacts and partners.

Please see section 2 here:
https://wordpress.org/about/gpl/

The blurb about child themes means you cannot sell Child themes that require an individual to download and install layers, using layers as the promotional base for your sales. This is to protect our brand and exclusive sales agreements with Envato. You will be given the means of selling child themes through official channels at a later date.

You can create a derivative of Layers as a completely new theme and sell it, provided it meets #2 above. The concept of derivative is often a bit vague- essentially it means your version needs to be changed enough to not be an exact copy of our theme. To sell derivatives, you also need to ensure links to the source, attribution and ability for users to get the FREE core code is retained.

You may not build a hosted service around Layers, for example, and charge people for access to the theme without it being explicitly clear that the theme can be downloaded for free and self-hosted. Hope that makes sense!

**Comment by em-** [comment]
Oh, sorry, for some weird reason I was under the impression that WP was under a non-copyleft license. :/ Given that WP itself is GPLv2+ I'd then suggest to expliclty allow for later version of the GPL: since Wordpress is released under the "GPLv2 (or later)" terms it could be upgraded to GPLv3 in the future, making such version incompatible with GPLv2 project like yours.

In this case I don't see any of the usual concerns about the GPLv3 that could apply (eg. there's no risk of tivoization) so I think using "GPLv2 (or later)" would be a good choice even for Layers.

> The blurb about child themes means you cannot sell Child themes that require an individual to download and install layers, using layers as the promotional base for your sales. This is to protect our brand and exclusive sales agreements with Envato. You will be given the means of selling child themes through official channels at a later date.

Note that, as far as I can tell, this is an additional restriction that would make this software non-GPL compatible (eg. I could not take your code and use it in a pure GPL project) and definitely non OSI-compliant as it looks like a "No Discrimination Against Fields of Endeavor" violation.

Again, I'm not a lawyer, but I really doubt that projects like Debian or Fedora (which are usually considered the gold standard when evaluating open source licenses) would accept additional clauses to the GPL like the one you described.

If possible I would ask you to drop this additional requirement and simply use the "GPLv2 (or later)" terms, or at least mark the additional restriction as such and not as an "explanation" of the GPLv2 since I fail to see how this restriction could follow from it.

> The concept of derivative is often a bit vague- essentially it means your version needs to be changed enough to not be an exact copy of our theme. To sell derivatives, you also need to ensure links to the source, attribution and ability for users to get the FREE core code is retained.

I don't think the GPL has any provision for this: my understanding is that nothing in the GPL prevents you from selling a GPL project as-is, provided you accompany it with the corresponding sources:

>>  1. You may copy and distribute verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice and disclaimer of warranty; keep intact all the notices that refer to this License and to the absence of any warranty; and give any other recipients of the Program a copy of this License along with the Program.
>>
>> You may charge a fee for the physical act of transferring a copy, and you may at your option offer warranty protection in exchange for a fee. 

See http://www.gnu.org/licenses/gpl-2.0.html#section1

> You may not build a hosted service around Layers, for example, and charge people for access to the theme without it being explicitly clear that the theme can be downloaded for free and self-hosted. Hope that makes sense!

This looks very much what the AGPLv3 offers over plain GPL. The GPL licenses (both v2 and v3) explicitly refer to distribution of the code, and remote access does not involve it.


Honestly I'd discuss these points with your legal partners again, possibly formally or informally contacting the SFLC, the OSI or the FSF for clarifications. Of course getting rid of these extra restrictions would be the best option, but it's unfortunately not up to me to decide. :)

**Comment by vailjoy** [comment]
Hi there,

I have updated our License section to  hopefully be more clear.

In a nutshell, you can sell whatever you want, but you can't remove the attribution and you must make the source available for free in a situation where you are charging folks for a hosted version. Keep in mind there is still copyright involved that is not part of GPL (which only covers source code). Taking Layers, rebranding it, changing a little CSS and reselling it would probably be seen as a copyright violation. Let me know if that is still cloudy!

**Comment by em-** [comment]
Thanks, it's much better!

That said I still think that there are still restrictions that are at odds with the GPL:

> It forbids you to: Publicly sell Child Themes or Extensions derived from or based on Layers outside of approved marketplaces

This still seems to conflict with [§1](http://www.gnu.org/licenses/gpl-2.0.html#section1):

>>  You may copy and distribute verbatim copies of the Program's source code as you receive it, in any medium
I'm also unsure about the passage below:

> It does not require you to: Include the full source of Layers itself, or of any modifications you may have made to it, in any redistribution

As I read it, it looks like someone could give me an obfuscated version of Layers they have improved without giving me full corresponding source code. That's definitely something that the GPL prohibits in [§3](http://www.gnu.org/licenses/gpl-2.0.html#section3):

>>  You may copy and distribute the Program (or a work based on it, under Section 2) in object code or executable form under the terms of Sections 1 and 2 above provided that you also do one of the following: 
>> * Accompany it with the complete corresponding machine-readable source code, which must be distributed under the terms of Sections 1 and 2 above on a medium customarily used for software interchange;

Also note that if images and other assets aren't covered by the GPL you should probably note that. I'd strongly advise doing that though (or at least I'd suggest to use one of the OSI-compatible Creative Commons licenses), as it quickly becomes an unwieldly mess for distributors which will probably prefer to ignore the project just to avoid any problem.

> Taking Layers, rebranding it, changing a little CSS and reselling it would probably be seen as a copyright violation. Let me know if that is still cloudy!

If the rebrander keeps the original copyright notices intact they are perfectly entitled to do that. Of course it would be a silly exercise as you could just undercut them by telling their clients they have been ripped of, but you need to be aware that it's a possibility.

To be honest I'd avoid any explanation of what the GPL allows you or not: having a license and an additional explanation that may conflict with the license can easily get you in a legal gray area.

I'm more concerned with some misunderstanding that you may have about the GPL, as it would be sad to have you feel betrayed if someone turned out to do things you thought were unallowed.

Oh, btw, any chance to include the *GPLv2 (or any later version)* language, to improve code crosspollination with Wordpress itself? Are you specifically opposed to your software being relicensed under the GPLv3 should the need arise?
