### ISSUE TITLE
docs.layerswp.com loading issues

### ISSUE THREAD

**Issue by alexpatin** [Obox/layerswp#52]
Hey there,

I have had some trouble pulling up the documentation site for Layers. I have tried in multiple browsers / networks and unfortunately the site is almost always unresponsive. Sometimes (~20% it loads <5-10s, but most of the time it has been completely inaccessible to me :disappointed: 

I know this isn't necessarily an issue with the theme per se, but I figured I would put it here since it is related and others would have the opportunity to comment with their documentation browsing experience.

Other than the loading however, the docs are strong!

**Comment by alexpatin** [comment]
I saw the docs were down this AM for me and are now back up! Everything is loading much faster now. Whatever you did, great job! I will close this issue.

**Comment by vailjoy** [comment]
As an FYI, this issues list is for the Layers product only - please report docs site issues via the Site Feedback button - if the site is down, we definitely know it. Thanks!
