### ISSUE TITLE
Creating an extension as a plugin

### ISSUE THREAD

**Issue by ZigZagMonty** [Obox/layerswp#54]
Hello,

I was playing around with layers and I thought of creating an extension. I wrote the below code in a plugin file -
```php
if( !class_exists( 'My_Widget' ) ) {
	class My_Widget extends Layers_Widget {
            // nothing yet
        }
}
```
But I get an error message saying that `Class 'Layers_Widget' not found`.

I made a check and it seems like Class Layers_Widget is available on 'init' hook. But I can't seem to get the extension to work. Is it a bug or I am doing something wrong? How should I go about creating an extension which can be added as a plugin?

Thanks!

**Comment by marcperel** [comment]
Hey Monty,

Our docs on the init should be up to date. If you include your widget file with this hook there should be no issue:

`add_action( 'widgets_init', 'my_widget_include', 50 );`

**Comment by ZigZagMonty** [comment]
Thank you so much!

I actually tried `add_action( 'widgets_init', 'my_widget_include', 20 );` but forgot to try increasing the priority.

It does work now, thanks again!

**Comment by marcperel** [comment]
Great!
