### ISSUE TITLE
Color Element Issue

### ISSUE THREAD

**Issue by gthapar** [Obox/layerswp#56]
Hi, 

There seems to be an issue with color element. Changing dynamically added color element does not trigger change in preview.

Steps to re-produce:
1. Add slider widget.
2. Add additional slide.
3. Change text color in dynamically added slide.

After following the steps you will notice that changing color in dynamically added slide does not trigger preview to change.

I have tested it with content widget too and the result is the same.

**Comment by vailjoy** [comment]
Hello!
Just a note that I can recreate this in the slider widget in 1.0.8. The content widget is working. The issue appears to be fixed on our development branch so you can expect better results in 1.0.9

**Comment by gthapar** [comment]
Great!

**Comment by eliorivero** [comment]
Hi, I had this issue myself too with Slider widget so I fixed it and this PR solves it https://github.com/Obox/layerswp/pull/72

**Comment by vailjoy** [comment]
Just a note that this is now fixed with 1.0+
