### ISSUE TITLE
Layers settings for the default WP text widget?

### ISSUE THREAD

**Issue by ckubs** [Obox/layerswp#6]
Hello. Installed layers yesterday, made some tests and although the framework is very promising I've missed a little more page customisability. For example to have 2 inline widgets( 50%-50%) or 3. 

Found a plugin that gives me the option to call any widget as a shortcode, and then added some shortcodes like that in a text widget( the WP one), each of them wrapped in a column class( 6, 4 ... etc) to achieve what I need. Unfortunatelly only your proprietary widgets can be customized, the others can't, and I can use my text widget only boxed not from side to side( full width). This is how is going to be, do you plan to add some widget settings like full width/boxed layout and custom class for the normal(non Layer) widgets too, or at least to make your own text widget with html, shortcodes ...etc, support?

**Comment by vailjoy** [comment]
Hi there,
Layers builder pages are intended for use with Layers widgets. I recommend using the Content widget instead of a text widget.
Please see our documentation here:
http://docs.layerswp.com/setup-guide/#build-your-home-page

**Comment by ckubs** [comment]
@vailjoy Yes I understand. But I need a Text widget( optimised or made especially for Layers to benefit from some settings like full width) not a content widget, and like me probably many potential users/customers. What you recommend me is a content widget targeted for some use scenarios and in mine I don't need( and actually sits in my way) a the content title, the content excerpt( wich I don't have) and the content columns( wich I don't have).

I just want to add a content slider( article slider, separate plugin, not the Layers slider) like the one I'm using right now with the current theme, to pack everything and switch to Layers. If I do it with functions using "echo do_shortcode( '[post-slides]' );"  and want to call it in a hook position, let's say "before_layers_builder_widgets" I get my slider, it's working normal but the main content, what's between </header> and <footer> is all gone. If I want to put the shortcode in a text widget, in  this case the wordpress text widget, I get my slider, I get the main content but the widget is not Layers widget so, I don't get the option to make it full width, from side to side.

So, I'm not talking about a content widget. I'm talking about a text area widget like the one from wordpress, that supports HTML imput and wordpress shortcodes. The default wordpress one does the job as I said but, as I said being a non Layers widget it doesn't benefit from the Layers settings.

**Comment by marcperel** [comment]
@ckubs Hi, the excerpt area for each column in the content widget works just like the text widget, it accepts HTML and shortcodes without any issue. If you leave out the main title and excerpt, and the column titles, that HTML just won't show, so you'll just need to use the *excerpt* area for the columns.

We could have made a totally bespoke text widget with column addition just like the content widget, but that would be creating a double feature since you can achieve the same affect using just the content widget itself.

**Comment by ckubs** [comment]
@marcperel So, If I just want to add my shortcode in a widget area and don't want the columns I can't do that? Otherwise, it would look extremelly akward to have a featured articles section under: Main title > Main excerpt > Column Title > Featured articles slider with all those, that must be left there. You should make it a little easy, to be able to make the excerpt and column title optional, not mandatory.

Also, this plugin( my current theme has a recent posts slider/carousel with owl and this is the only one I found on the wp plugins database, that can mimic that) has some compatibility issues with your builder( other shortcodes are fine), and I can't add it with do_shortcode in a hook position either. When I try to output it that way, everything is ok on the archives pages, on single.php but on the pages with built layouts, in my case the homepage, when this is present in a hook possition, nothing is broken but what's between header and footer, the content, is gone.

Well I guess I cant switch yet to yout framework, if I can't solve that.

**Comment by ckubs** [comment]
@marcperel Ok I could accomplish most of the things I needed. Unfortunatelly It doesn't helping me too much, as I said that content title, excerpt and column title are mandatory. If I could disable the excerpt and one of the two, content title or column title, it would be awesome.

**Comment by marcperel** [comment]
Ckubs if you just leave them blank they won't have any affect on the front end so I think you're safe. 

I'm going to close this ticket for the time being as we'd prefer to keep this channel for bugs and enhancements, thanks for the great feedback though.

**Comment by ckubs** [comment]
Now I see. I guess I have to read the documentation propperly so I won't get lost again. Since this is solved, or was from the beggining( though, I didn't know hot to properly set up the plugin) the framework rocks. :+1:
