### ISSUE TITLE
 bbPress?

### ISSUE THREAD

**Issue by jazzcrack** [Obox/layerswp#60]
What about bbPress support? Just have the option to have bbPress on full width or have a sidebar and can add widgets would be nice. Anything planned?

**Comment by vailjoy** [comment]
Hi there,

We will not be adding any explicit support for 3rd party fucntionality into the framework and want for that support to come in a plugin or child theme. As we have time to work on free projects we check the Layers community for what is requested most. Please add your request here so others can vote it up! 

http://docs.layerswp.com/help/
