### ISSUE TITLE
Page numbering

### ISSUE THREAD

**Issue by jazzcrack** [Obox/layerswp#61]
If you activate the page numbering at content widget, the page numbering isnt at the end of the content. Its at random place. :-( I using grid list view.

Example:
![bildschirmfoto 2015-04-03 um 15 05 00]
(https://cloud.githubusercontent.com/assets/2137308/6982495/e2d6d3a4-da12-11e4-9bac-f07391180659.png)

![bildschirmfoto 2015-04-03 um 15 06 05](https://cloud.githubusercontent.com/assets/2137308/6982509/05ac2e10-da13-11e4-914f-7e3c43e3bf63.png)

**Comment by douglas** [comment]
I can confirm this.

**Comment by marcperel** [comment]
Thanks for pointing the issue out @douglas & @jazzcrack

**Comment by jazzcrack** [comment]
Add "float: left" to the DIV of the pagination help. Please add in next release. Just add "float" to class ".pagination" do not help, because class ".span-12" says "float: none".

<div class="pagination row span-12 text-center">
<ul class="page-numbers">
...

**Comment by ryanmccrary** [comment]
The .pagination element can also be made block instead of inline-block to fix this issue

**Comment by marcperel** [comment]
@ryanmccrary We've fixed this in our soon to be published release. Thanks for the suggestion though.

**Comment by ryanmccrary** [comment]
@marcperel great, thanks so much! Sorry I was late to the party!

**Comment by marcperel** [comment]
@ryanmccrary No prolly, we've pushed the fix to `develop` branch so you can check it out there.
