### ISSUE TITLE
Site search does not see layerswp page contents & can't find anything

### ISSUE THREAD

**Issue by gb97** [Obox/layerswp#62]
Wordpress 4.1.1
layerswp 1.0.8

**To Reproduce**
- Create a layerswp page. Add a CONTENT widget & add some copy in there & save.
- Add a SEARCH widget to one of the Footers & save.
- Load site & search for any words you added to your layerswp page.

**Result**
- No words are found in layerswp pages!

If you make a regular WP page & add copy to it, search widget works correctly & finds everything.

**Comment by vailjoy** [comment]
Hi there,
Layers stores the content in a custom field rather than the content area of the page editor, therefore SEO doesn't know how to crawl for it. You can add custom fields to some plugins to be included in search results. We are currently working out what the best method is for improving this.

**Comment by marcperel** [comment]
@gb97 We're certainly looking for a solution for this, it's something that's part of our roadmap planning which will be completed this week
