### ISSUE TITLE
Custom widgets created in plugin dissapear

### ISSUE THREAD

**Issue by Jelena1** [Obox/layerswp#63]
When theme is switched, my custom widget content (widget is created in plugin) disappears and it can't be found anywhere. This really not user friendly to force users to export widgets all time.

Is there any solution? 

Also I had to create this custom widget plugin to deactivate automatically when theme is switched because it would break another theme if stays activated with function Layers widget not found...

**Comment by Jelena1** [comment]
I tried to add custom widget directly in child theme and it works without losing content when theme switched, the same as parent theme. You had recommendation for custom widgets to be created in plugin https://github.com/Obox/layerswp/issues/31 but it has issue I reported in first message. It seems for now that it is better to create custom widget it in child theme. Any thoughts?

**Comment by marcperel** [comment]
Hi Jelena,

When you say another theme are you referring to a non-Layers theme?

If that's the case then I'd suggest putting an if statement around the widget so that it gracefully disables, something akin to `if( class_exists('Layers_Widget')`

~ Marc

**Comment by Jelena1** [comment]
Hi,

Yes I reffering to a non-Layers theme.

My custom widget has this code:
if( !class_exists( 'My_Widget' ) ) {
	class My_Widget extends Layers_Widget {
...

and that is the same code as in default widgets.

this code:

if( class_exists( 'My_Widget' ) ) {
	class My_Widget extends Layers_Widget {
...

doesn't show my widget anymore.

But that is not an issue, widget plugin disabling is done with TGM plugin activation "force_deactivation".

Important issue is in first sentence, content added via custom widget (which is in plugin) dissapears when non-Layers theme is activated, then layers child is activated again, custom widget content is gone. It does not happen if custom widget is in child theme. Content added with default widgets stays the same after theme switch to non Layers and switch back to Layers.

**Comment by Jelena1** [comment]
I suppose there is some backup for default widgets content which is not applied to plugin widgets

**Comment by marcperel** [comment]
Thanks for the description, in the latest version we did work which keeps widgets active when you switch between child and parent themes. 

Which version were you running when you tested the switch when your widget was in a plugin?

**Comment by Jelena1** [comment]
Newest version. I'm reffering to non Layers themes, because users will sometimes switch to Twentyfourteen theme and then switch back to Layers child theme and will discover that half of content on site dissappear (content from my custom widget in plugin).

**Comment by marcperel** [comment]
I will run some tests around this. WordPress should keep all widget settings when the theme is switched, so it's certainly something worth testing on our side.

**Comment by Jelena1** [comment]
Ok, thanks. Usually default WP widgets stays in inactive area when themes are switched but Layers widget are not visible there, even if they stay.

**Comment by Jelena1** [comment]
Works fine now with this if statement around widget

if( !class_exists( 'my_widget' ) and class_exists( 'Layers_Widget' )) {
 
class my_widget extends Layers_Widget {

...

**Comment by marcperel** [comment]
Thanks we will take this case to a test Jelena

**Comment by Jelena1** [comment]
Any update?

**Comment by marcperel** [comment]
Hey @Jelena1 we are working on script which backs up widgets. We don't have a completion date on the script but we will have a roadmap of features (this included) out by the end of the week.

**Comment by vailjoy** [comment]
Please see the following for tips on backing up all the content:

http://docs.layerswp.com/doc/backup-your-pages/

Full export of Customizer settings is coming
