### ISSUE TITLE
Incorrect handling of 'widget-updated' event

### ISSUE THREAD

**Issue by cosmocoder** [Obox/layerswp#65]
I am currently working on an extension for Layers and while working on it I encountered a javascript syntax error that was reported by the browser whenever the widget settings were saved using the Apply/Save button. After some debugging I was able to pinpoint the issue with the handling of the `widget-updated` event in the admin.js file of Layers which is located in core/assets/admin.js.

As described in this ticket, https://core.trac.wordpress.org/ticket/19675, and as also seen in the code example at https://make.wordpress.org/core/2014/04/17/live-widget-previews-widget-management-in-the-customizer-in-wordpress-3-9/, the jQuery `widget-updated` event that is triggered by Wordpress whenever a widget's settings are saved is passed the jQuery object for the widget in the Customizer sidebar. However in admin.js of Layers, the argument for the callback function of the `widget-updated` event, is being incorrectly assumed to be the id of the widget container in the currently edited Wordpress page, like this:
```javascript
$( document ).on( 'widget-updated' , function( updatedWidgetId ){
     // more code
});
```

This widget id is then passed into the `layers_widget_focus` function that uses it to scroll the page and bring the widget container into view. But since instead of a string containing the id a jQuery object is actually being passed an error is arising.

The solution is is to change the event callback to something like this:
```javascript
$( document ).on( 'widget-updated' , function( event, $updatedWidget ){
    var widget_id = $updatedWidget.find( '.widget-id' ).val();
    // further actions with the id
});
```

There maybe other similar issues with the event callbacks of `widget-added` and `widget-updated`
events in admin.js, but I have not faced anything else for now, but a thorough code inspection maybe needed.

I hope I was able to describe the issue properly. Please release a patch for this officially as soon as possible.

**Comment by marcperel** [comment]
Great spot Cosmo, we'll definitely check this out.

**Comment by cosmocoder** [comment]
Thanks for looking into this. 

Also a request - please update the official docs for creating Layers extensions that also explains or provides examples for the javascript part of the widget admin area. I have been able to follow the docs for creating the necessary php files but have been struggling to properly code the javascript part that dynamically manipulates the widget form.

**Comment by marcperel** [comment]
Hey Cosmo,

We'll implement this fix into our next release thanks.

Currently our JS docs aren't substantial because we have not setup a solid dynamic framework on the JS side, making the JS more dynamic with better helper functions is in the pipeline though.

**Comment by cosmocoder** [comment]
The JS part of my extension is giving me the most trouble, since the widget form needs to be substantially manipulated for my extension, including the dynamic insertions and removals of input elements. If you could at least update your docs with the way you handled the Layers Slide widget I think that will also be helpful.
