### ISSUE TITLE
Issue: Error, Exporting Layout (Warning: Cannot modify header information)

### ISSUE THREAD

**Issue by ajbat21** [Obox/layerswp#66]
## Description of issue
Warning: Cannot modify header information error when trying to export a layout. Disabled all plugins. Still get the same error. Happened on Hostgator and 1and1. 

## URL of page exhibiting the issue
This is a a production URL. http://s406263526.onlinehome.us/reality_check/

## Web Browser(s) that exhibit the issue
Chrome
Firefox - Developers edition

## Error Message or Steps to Recreate
Followed directions for exporting a layout. Layers Pages > Select page > Click Export on lower left of page.

RECEIVED THE FOLLOWING MESSAGE 

Warning: Cannot modify header information - headers already sent by (output started at /homepages/19/d406263507/htdocs/reality_check/wp-admin/includes/template.php:1877) in /homepages/19/d406263507/htdocs/reality_check/wp-content/themes/layerswp/core/helpers/migrator.php on line 58

Warning: Cannot modify header information - headers already sent by (output started at /homepages/19/d406263507/htdocs/reality_check/wp-admin/includes/template.php:1877) in /homepages/19/d406263507/htdocs/reality_check/wp-content/themes/layerswp/core/helpers/migrator.php on line 59

Warning: Cannot modify header information - headers already sent by (output started at /homepages/19/d406263507/htdocs/reality_check/wp-admin/includes/template.php:1877) in /homepages/19/d406263507/htdocs/reality_check/wp-content/themes/layerswp/core/helpers/migrator.php on line 60

Warning: Cannot modify header information - headers already sent by (output started at /homepages/19/d406263507/htdocs/reality_check/wp-admin/includes/template.php:1877) in /homepages/19/d406263507/htdocs/reality_check/wp-content/themes/layerswp/core/helpers/migrator.php on line 61

Warning: Cannot modify header information - headers already sent by (output started at /homepages/19/d406263507/htdocs/reality_check/wp-admin/includes/template.php:1877) in /homepages/19/d406263507/htdocs/reality_check/wp-content/themes/layerswp/core/helpers/migrator.php on line 62

Warning: Cannot modify header information - headers already sent by (output started at /homepages/19/d406263507/htdocs/reality_check/wp-admin/includes/template.php:1877) in /homepages/19/d406263507/htdocs/reality_check/wp-content/themes/layerswp/core/helpers/migrator.php on line 63
{"obox-layers-builder-107":{"layers-widget-slide-7":{"slide_time":"","slide_height":"350","design":{"advanced":{"customclass":"","customcss":"","padding":{"top":"","right":"","bottom":"","left":""},"margin":{"top":"","right":"","bottom":"15","left":""}}},"slide_ids":"950","slides":{"950":{"design":{"background":{"image":"http:\/\/s406263526.onlinehome.us\/reality_check\/wp-content\/uploads\/2015\/04\/BL_BackGround.jpg","color":"#444","repeat":"no-repeat","position":"center"},"featuredimage":"","featuredvideo":"","imagealign":"image-top","fonts":{"align":"text-center","size":"medium","color":"#ffffff"}},"title":"About Reality Check","excerpt":"Reality Check is a nonprofit youth mentorship organization working to bring about positive social change through direct and meaningful interactions between educators and youth through edutainment.","link":"","link_text":"See More"}}},"execphp-5":{"title":"","text":"post_content);\r\n ?>","filter":""}}}

**Comment by marcperel** [comment]
Hey AJ,

If you update to 1.0.8, we've fixed this issue. Download the Layers Updater and you'll be able to update with one click.

~ Marc

**Comment by ajbat21** [comment]
Thanks Marc. Problem solved. I thought I was using the latest version. Installed the update plugin but never ran it. Problem solved.
