### ISSUE TITLE
Issue: One-Page design Page Scrolling is not smooth when Header Menu is clicked

### ISSUE THREAD

**Issue by SaulsCreative** [Obox/layerswp#67]
## Description of issue
Smooth Scrolling is not working on one-page design. When menu link is clicked it abruptly jumps to the id. How do you implement scrolling that is slow like in the one-page LayersWP Demo?

## URL of page exhibiting the issue
http://www.triciasauls.com

## Web Browser(s) that exhibit the issue
Chrome, Fire Fox and Opera all have this same issue

**Comment by vailjoy** [comment]
Hi there,
There is no smooth scrolling scripting in Layers by default, you would need to add it via a child theme. It is something we are considering in the future, but we want to keep the framework as basic as possible. The jQuery website has several quick and easy snippets for adding smooth scroll.
