### ISSUE TITLE
Adding product list with thumbnail and has-overlay support

### ISSUE THREAD

**Issue by jmotes** [Obox/layerswp#69]
The demo at http://sites.layerswp.com/shoes/ and also the site mentioned on the News page: https://www.nicharry.com/ both have a list of products on the homepage that show an "Add to Cart" button once hovered. 

I've tried a few different ways to build this functionality out in LayersWP but haven't had any luck and haven't found any extensions that generate the required HTML as mentioned on http://docs.layerswp.com/framework/ for thumbnail overlay support. 

Is this section just hard-coded HTML? And if so, what is the best strategy to insert HTML into a Layers page?

Thanks!

**Comment by vailjoy** [comment]
Hello!

This is actually part of an extension that we will be releasing soon. Please see the plugin guide on our website for how to create a custom widget - 
http://docs.layerswp.com/plugin-creation-guide/
The posts widget is a good place to start for looking at how the product version is put together and uses the html under Thumbnail list with overlay:
http://docs.layerswp.com/framework/
You must also reference the WooCommerce API for how to loop products or display specific meta etc.

**Comment by jmotes** [comment]
That's very helpful - thank you! Any chance you have an ETA on the extension?

**Comment by Spark3000** [comment]
Hi @jmotes - Likely Tuesday next week.
