### ISSUE TITLE
Slider Widget: when a new slide is added, the color picker is initialized but its events aren't binded.

### ISSUE THREAD

**Issue by eliorivero** [Obox/layerswp#71]
**Steps to Reproduce**

Add a slider widget
Add a new slide
Change the background color

**Result**

The background color is not updated.

**Expected Result:**

The background color is updated to match the one in color picker.

**Comment by vailjoy** [comment]
Hi there,
We are tracking this here. It should be resolved in the next update.
https://github.com/Obox/layerswp/issues/56

**Comment by eliorivero** [comment]
Oh I see. I checked the list of issues looking at their title but found none similar. Will comment there.
Cheers.
