### ISSUE TITLE
Youtube Embeds too large in blog posts

### ISSUE THREAD

**Issue by ryanmccrary** [Obox/layerswp#73]
Not sure if I'm the only one seeing this but oembed's from Youtube look great in Thumbnails, but are too tall and narrow in the actual post views because the #player is in the body tag and makes the height 100%. It doesn't show the video well at all. We solved it by fixing the height in the .format-video iframe element.

Is there any reason the player has to be put in an iframe? Worried that it could be blocked by some browsers that way.

**Comment by vailjoy** [comment]
Hello!

Is this when adding a "featured" video using the post meta or from inserting oemned url directly into the post editor? (we do not put the video in an iframe, oEmbed does that)

**Comment by ryanmccrary** [comment]
It's when we paste the link in the Layers>Options Rich Media Embed seen here https://www.dropbox.com/s/oik1pii85dji66c/Screenshot%202015-04-23%2012.49.41.png?dl=0

**Comment by vailjoy** [comment]
Thanks Ryan! I can recreate this and confirm it is pulling in a 1024px wide iframe. We can't solve the part about it being put into an iframe (that is default oembed behavior) but we can fix the sizing so it works like a standard WordPress embed.

**Comment by ryanmccrary** [comment]
No problem - we've added some CSS ourselves to fix the sizing for now, but glad to get a fix in for others. The iframe is fine. Just a small nitpick, but functionally it's fine.

**Comment by marcperel** [comment]
Thanks Ryan, we'll continue to work at getting a solution out for this
