### ISSUE TITLE
virus/malware detection

### ISSUE THREAD

**Issue by jazzcrack** [Obox/layerswp#74]
Using a antivirus/antimalware plug-in (http://wpantivirus.de/) which now raises the alarm.

/themes/layerswp/parials/header-centered.php
... => 'nav nav-horizontal', 'fallback_cb' => create_function ('', 'echo "&nbso";') ) ); ?>

![bildschirmfoto 2015-04-23 um 13 57 20](https://cloud.githubusercontent.com/assets/2137308/7296652/cda4edfe-e9c1-11e4-9a19-302616212f52.png)

I think i can ignore it manuel, but maybe its possible to code in a way its not detected as virus/malware.

**Comment by marcperel** [comment]
Thanks for the feedback JC
