### ISSUE TITLE
Categories layout missing

### ISSUE THREAD

**Issue by jmotes** [Obox/layerswp#76]
If I change the Shop Page Display setting (under WooCommerce > Settings > Products > Display) to "Show categories and sub-categories" instead of "Show products" , each category is shown on a separate row on the Shop page. WPLayers needs a grid layout for categories there.

**Comment by marcperel** [comment]
@jmotes WooCommerce are releasing a filter for this which we'll be able to tap into in WooCommerce 2.4 so we'll have to wait for that release before getting this fix out.

**Comment by vailjoy** [comment]
This is resolved in 1.2.4
