### ISSUE TITLE
Losted all my designs after installed buddypress child theme

### ISSUE THREAD

**Issue by danielchicote** [Obox/layerswp#77]
All the texts, photos and texts losted. Two weeks of hard work, and i dont have a backup!!!

**Comment by marcperel** [comment]
Hey Daniel, is the child theme built for Layers? If so it should have kept the widgets and theme options. Wordpress usually saves the widget settings per theme so if you switch back to Layers your pages should still be active.

**Comment by vailjoy** [comment]
I can confirm the BuddyPress theme linked from the tutorial and my gitub here works without issue and will not cause data loss (it does not actually modify or change any part of the Layers core, just adds templates) -  all of your Layers pages should be visible under Layers > Layers Pages:
http://docs.layerswp.com/doc/how-to-add-support-for-buddypress-to-layers/

Note that switching the active theme in WordPress does reset global settings, which include your Site Settings, sidebar widgets, colors, menus, sidebar options, etc. You can read more about this here:
http://iampuneet.com/theme-customizer-child-theme/

Always do a quick backup of Layers pages by Exporting the json files, just to be safe !

As Marc says, try switching back to Layers, then use the Widget Importer&Exporter plugin to export your widget setup. Activate the buddypress theme, then import the widget file and you should be all set :)

**Comment by danielchicote** [comment]
I don´t understand what really happened. When i reverted to the default layerswp theme, the indexes from the menus, names, dependencies and urls have increment his values (i think), and the links don´t get the correct contents. None. The content and widgets were there, but were not visible. It was needed to see all pages one by one and all the item menus and rewrite all. Now its all ok, only have lost 2 pages of content, i think.
