### ISSUE TITLE
Update 1.1.2 dont update

### ISSUE THREAD

**Issue by danielchicote** [Obox/layerswp#78]
Hello, i try to update again and again, and always have the message of succesfull update, but all the times it continues the 1.1.1 version installed, and wordpress says me that there are a new version of the theme to install. WTF?

**Comment by marcperel** [comment]
Hey Daniel,

It could be a simple versioning number issue, well get onto it right away.

**Comment by marcperel** [comment]
Daniel if you update now you'll be on the latest version. Thanks for bringing it to our attention!

**Comment by danielchicote** [comment]
Solved problem: i have needed to enable multisite and update from the network updater.
