### ISSUE TITLE
http://themecheck.org/ score

### ISSUE THREAD

**Issue by szepeviktor** [Obox/layerswp#79]
Please try to reach ~99-100 on http://themecheck.org/
Someone else may also check it...

**Comment by szepeviktor** [comment]
Now it is <small>56</small>.

**Comment by vailjoy** [comment]
Hi there,

We do run the theme through the official Themecheck plugin. Additonally, the theme has been put throught rigorous testing and scrutiny by members of the wordpress.org, wordpress.com and Themeforest teams. We are confident the theme is at a strong place in terms of speed and security. Naturally there is always room for improvement, and our community here is great at offering ways to optimize code. You are welcomed to submit Layers to that site if you like. As a third party site that does not offer any information on how they are scoring themes, we can't really deem it reliable in terms of scoring against what .org has already done for us.  I appreciate you sharing the link!

**Comment by szepeviktor** [comment]
<div class="col-md-12"><h2 style="line-height:100px;color:#D00;">Critical alerts</h2><ol><h4 style="color:#666;margin-top:40px;"><li>Security breaches : Use of variable functions</li></h4><p style="color:#c94b4b;">Found <strong>$method</strong> in file <strong>design-bar.php</strong>. </p><pre>Line 97: $this-&gt;$method( $args );</pre><pre>Line 108: $this-&gt;$method();</pre><pre>Line 177: * @param    array       <span>$array(</span>)    Existing option array if exists (optional)</pre><p></p><h4 style="color:#666;margin-top:40px;"><li>Admin menu : Themes that support admin pages should use <strong>add_theme_page()</strong> instead of other functions (add_admin_page, add_submenu_page...)</li></h4><p style="color:#c94b4b;">File <strong>init.php</strong> : </p><pre>Line 276: $dashboard = <span>add_menu_page</span>(</pre><p></p></ol><h2 style="line-height:100px;color:#eea43a;">Warnings</h2><ol><h4 style="color:#666;margin-top:40px;"><li>Custom elements : Presence of custom header</li></h4><p style="color:#eea43a;">No reference to <strong>custom header</strong> was found in the theme.</p><h4 style="color:#666;margin-top:40px;"><li>Custom elements : Presence of custom background</li></h4><p style="color:#eea43a;">No reference to <strong>custom background</strong> was found in the theme.</p><h4 style="color:#666;margin-top:40px;"><li>Editor style : Presence of editor style</li></h4><p style="color:#eea43a;">No reference to <strong>add_editor_style()</strong> was found in the theme. It is recommended that the theme implements editor styling, so as to make the editor content match the resulting post output in the theme, for a better user experience.</p><h4 style="color:#666;margin-top:40px;"><li>Featured image : Use of the_post_thumbnail() instead of custom fields for thumbnails</li></h4><p style="color:#eea43a;">No reference to <strong>the_post_thumbnail</strong> was found in the theme.</p></ol><h2 style="line-height:100px;color:#00b6e3;">Info</h2><ol><h4 style="color:#666;margin-top:40px;"><li>Optional files : Presence of rtl stylesheet rtl.css</li></h4><p style="color:#00b6e3;">This theme does not contain optional file <strong>rtl.php</strong>.</p><h4 style="color:#666;margin-top:40px;"><li>Optional files : Presence of front page template file front-page.php</li></h4><p style="color:#00b6e3;">This theme does not contain optional file <strong>front-page.php</strong>.</p><h4 style="color:#666;margin-top:40px;"><li>Optional files : Presence of home template file home.php</li></h4><p style="color:#00b6e3;">This theme does not contain optional file <strong>home.php</strong>.</p><h4 style="color:#666;margin-top:40px;"><li>Optional files : Presence of category template file category.php</li></h4><p style="color:#00b6e3;">This theme does not contain optional file <strong>category.php</strong>.</p><h4 style="color:#666;margin-top:40px;"><li>Optional files : Presence of tag template file tag.php</li></h4><p style="color:#00b6e3;">This theme does not contain optional file <strong>tag.php</strong>.</p><h4 style="color:#666;margin-top:40px;"><li>Optional files : Presence of term template file taxonomy.php</li></h4><p style="color:#00b6e3;">This theme does not contain optional file <strong>taxonomy.php</strong>.</p><h4 style="color:#666;margin-top:40px;"><li>Optional files : Presence of author template file author.php</li></h4><p style="color:#00b6e3;">This theme does not contain optional file <strong>author.php</strong>.</p><h4 style="color:#666;margin-top:40px;"><li>Optional files : Presence of date/time template file date.php</li></h4><p style="color:#00b6e3;">This theme does not contain optional file <strong>date.php</strong>.</p><h4 style="color:#666;margin-top:40px;"><li>Optional files : Presence of image template file image.php</li></h4><p style="color:#00b6e3;">This theme does not contain optional file <strong>image.php</strong>.</p></ol></div>

**Comment by szepeviktor** [comment]
I had to upload and

> The name "Layers" of this theme is already used by a theme that was previously submitted. The results of this validation could not be saved.

**Comment by szepeviktor** [comment]
I think you have a good reason for `Use of variable functions` but please consider avoiding it.
It look like malware.
Please take a look at WP's `do_action()` function.

**Comment by vailjoy** [comment]
Hi there,

Marc will need to provide some detail around $method, but I can tell you that these suggestions all have to do with themes submitted to WordPress.org and have no bearing on themes in the wild. 
1. We purposely do not use submenus as we need Layers to be its own Admin menu.
2. We do not include the custom header or background by design currently. That is a job we wish to leave for child themes
3. We do not use the_post_thumbnail directly, we use a much more dynamic function for handling featured images so that video is supported.
4. All of the PHP template files in the info section are not required and are up to child themers to add if whey wish to provide special layouts for those archives. Currently the primary WordPress template heirarchy is used to fall back to the standard set of templates included in layers. I will point out that home.php, front-page.php and image.php are proprietary and would not exist in a basic WordPress theme or in Layers as it uses builder.php or falls back to index.php to display a blog archive as default if no static page is set.

**Comment by marcperel** [comment]
Hi Szep,

We use the variable function purely to keep the loop dynamic, I'm afraid that it's probably not something we'll change immediately but we'll definitely take any on points about security and revisit them when need be.

~ Marc
