### ISSUE TITLE
PHP class autoloading

### ISSUE THREAD

**Issue by szepeviktor** [Obox/layerswp#81]
Please consider class autoloading instead of `require`-s like in
https://github.com/Yoast/wordpress-seo/blob/trunk/wp-seo-main.php#L33-L39
It is a modern solutio and **is** very fast, consumes smaller amout of memory.
This is the plugin to measure memory usage:
https://wordpress.org/plugins/whats-running/

**Comment by marcperel** [comment]
Thanks @szepeviktor we've added this as a task in our task manager, we'll investigate including this method in the next release.

~ Marc
