### ISSUE TITLE
hatom Microformat

### ISSUE THREAD

**Issue by szepeviktor** [Obox/layerswp#82]
I personally miss hatom classes from this theme.
https://github.com/automattic/_s

Google WMT has a page that [tests](https://developers.google.com/structured-data/testing-tool/) and reports missing hatom data. Maybe it is a ranking factor.

**Comment by vailjoy** [comment]
Hi there,

Our initial focus with Layers was to make a free theme that incorporated WordPress-centric customization via their Visual Customizer. As a framework, our priority has been on stability, security and usability so things like hatom and other accessibility optimizations like roles are things we will be looking at down the road once we are totally comfortable with where the Layers foundation is at and feel it ready for enhancement. I agree, these would be a nice addition!
