### ISSUE TITLE
Issue: Quotation marks not supported in Content Block Title

### ISSUE THREAD

**Issue by mark-os** [Obox/layerswp#83]
Add a title to a Content Column like: Things that make you go "ooh"

You will see the text within the quotes disappear from the title as soon as you save it. Adding HTML character codes does not work either.

**Comment by marcperel** [comment]
Thanks Mark, we'll check this out

**Comment by marcperel** [comment]
Mark, we've logged this in our task management app, so keep an eye out for the fix in the next releast.
