### ISSUE TITLE
Issue: Can't edit Posts Layout

### ISSUE THREAD

**Issue by svdm83** [Obox/layerswp#84]
## Description of issue
When I add the display Posts Widget, it does display 6 posts, but when I edit any settings, the posts disapear in the preview (they're also still gone when I publish anything). The category 'all' doesn't work and I have to manually select all the cats to see anything again. But then it's still impossible to change the image ratio. Or should I use a thumbnail generator for that?

## URL of page exhibiting the issue
www.scoutingrijsbergen.nl (multisite)

## Web Browser(s) that exhibit the issue
Chrome

## Error Message or Steps to Recreate
none

**Comment by marcperel** [comment]
Hey,

Thanks we will check this issue out and hopefully get a fix out in the next release.

~ Marc

**Comment by marcperel** [comment]
We are releasing version `1.1.3` which fixes this issue :)
