### ISSUE TITLE
Feature request: List item

### ISSUE THREAD

**Issue by Theme20** [Obox/layerswp#85]
Hello, 

Could you please add 'list-item' for next update, i think list-item is really useful for all users.

Ex: https://docs.google.com/file/d/0B7q-ingsr5hKRGdTVHN1Vk0wSm8

Thanks :)

**Comment by marcperel** [comment]
Hello,

Can you help us with more explanation on how it would look on the front end?

**Comment by Theme20** [comment]
Hi Marc, 

With list items we can add something like social icons in header and re-order them also it will usefull for other sections.

I hope this helps: http://i.imgur.com/zEe0c5g.gif

Cheers

**Comment by vailjoy** [comment]
Hi there,
Just a note on this specific implementation - you can do that already with the Media Social Icons plugin which attaches social icons to a qualified WordPress menu, which is a little better approach since it generates a valid nav element.

**Comment by vailjoy** [comment]
List item has been added via the RTE in all Layers widgets content areas. At this time we have no plans to allow RTE in non-content fields (such as the header or footer)
