### ISSUE TITLE
adding section - documentation code not working

### ISSUE THREAD

**Issue by krike** [Obox/layerswp#86]
I just started with layerswp and i'm digging through the docs. I'm trying to add a custom section but it just won't work.

The documentation has the following code:

    function my_layers_customizer_sections( $sections ){
        $sections[ 'header-social-media' ] => array(
                'title'      => __( 'Social Media Profiles' , 'layerswp' ),
                'panel'     => 'header',
            )
        );

        $sections = array_merge( $sections, $social_media_section );

        return $sections;
    }

But $social_media_section (used in the array merge) is not being set anywhere. So I thought it was a mistake in the docs and I changed it to the following:

    public function my_layers_customizer_sections( $sections )
    {

        $social_media_section['header-social-media'] = array(
            'title' => __( 'Social Media Profiles' , LAYERS_SAK_SLUG ),
            'panel' => 'header',
        );

        $sections = array_merge( $sections, $social_media_section );
        /*echo '<pre>';
        print_r($sections);
        exit;*/
        return $sections;
    }

Still the section won't appear. Is this a bug or am I doing something wrong?

**Comment by marcperel** [comment]
Hi Krike,

Thanks for pointing the `array_merge()` issue out. Sections don't display unless they have controls inside them. We'll update the documentation to correct the merge issue and further explain adding the controls.

**Comment by krike** [comment]
Aha. that did cross my mind and i had of course added controls to the new section. I just noticed an error in the function for the controls. it works now. Thanks

**Comment by marcperel** [comment]
Fantastic, excited to see your work once you're done.
