### ISSUE TITLE
Bug in partials/content-single.php?

### ISSUE THREAD

**Issue by openforest** [Obox/layerswp#87]
partials/content-single.php may have a bug. See post and diff which fixes the issue here: http://docs.layerswp.com/help/question/9868/conflict-between-layers-and-wpmu-pro-sites/

**Comment by vailjoy** [comment]
the_content() is called on line 29 of the content-single.php.
https://github.com/Obox/layerswp/blob/master/partials/content-single.php#L29

 Prior to that are two conditions: one checks to make sure the content is not empty before outputting the entire block. The next checks to see if this page is using the Blank Page template. If it is, the story wrapper is not applied and the content is output. If it is a default page or sidebar page, the story wrapper is applied and the content output.

The issue may be that these pages need to use the Blank Page template explicitly to avoid getting the story wrapper, or vice versa.
