### ISSUE TITLE
Post Widget Post 

### ISSUE THREAD

**Issue by lwoods** [Obox/layerswp#88]
## Description of issue

Selecting "All" for a Category in the "Posts - Latest Posts" does not display any Posts.  I was just starting to work with Layers and have an "empty" site with two Posts: Hello, World and then a Dummy Post.  Both have only one Category: Uncategorized.

**Comment by marcperel** [comment]
Hey,

Can you please make sure you are running version 1.1.3, and if so id recommend creating a new page wit the post widget, as we had an issue with the widget in 1.1.2.

~ Marc

**Comment by lwoods** [comment]
Sorry for being ignorant but I don't know where the Version # is stored.  There was an update that I downloaded which consisted of an includes folder with a class-updater.php and a functions.php .  I see no code in the functions.php that indicates Layer version.  Also, I don't know how to "install" the update.  Are there instructions on the Layers site for that?  If so, I will chase them down.

Thanks

**Comment by marcperel** [comment]
No problem,

You can see your theme version under Appearance > Themes.

You can get the updated here http://layerswp.com/download/layers-updater and install it under Plugins > Add New.

That will add the update to the updates section in your WordPress site.

**Comment by lwoods** [comment]
You might want to pass these comments to whomever.

 

FYI,  Layers doesn't display it's version under Appearance -> Themes.  It's also not on the Layers -> Dashboard page.  I did find it somewhere earlier today but I don't remember where.

 

If you go to the Layers -> Dashboard, "Contribute to Layers" there is a link that says "Layers on GitHub.  Check out the issues tab for ways to help."  The link is to http://docs.layerswp.com/contributing-to-layers/ .  Not THAT big a deal but inconsistent.

 

And, hey, I looked through the class-updater.php.  When is the api going to pop up?  ;-)

 

PLEASE take the above comments constructively.  I am an "old" PHP and Genesis developer and would like to see a little competition so I am all for you.

 

Larry

**Comment by marcperel** [comment]
Thanks Larry, 

We appreciate your feedback, your delivery makes it easy to take on :)

Good note about contribution wording we'll check that out, we like to channel through docs.layerswp.com as it gives us flexibility on ways to communicate different methods to contributors.

The 'api' method is really a way to prep for more dynamic updates for our items we're selling on Envato.

~ Marc

**Comment by lwoods** [comment]
I will not take advantage of this "personal" connection that we have but I do want to suggest a future feature:

 

I want the capability of creating my own Widget Areas within your widget areas, or at least being able  to "mix and match" your widgets.  For example, when I create a Content widget I would like to specify two columns, for example, which I can today.  BUT, I want to put "Latest Posts" in one of the columns and "Calendar", for example, in the other.  Actually, I think the "ultimate" would be to be able to specify an empty Widget area in either or both of those columns.  Then I can put whatever widgets I want in the columns.  This "feature" is something that I have needed many times.  

 

What it amounts to is a "partial" sidebar, rather than a sidebar that extends the full height of the main content area.

 

Sorry for tying you up with these "brilliant" suggestions.

 

Larry

 

PS:  I do realize that at least one of your target audiences is the "non-technical" WP user so your large offerings of predefined widgets makes all sorts of sense.  But, it would sure be nice if there was another level of widgets of one wanted to "take the next step!"

**Comment by marcperel** [comment]
Hey Larry,

The partial sidebar logic is something that we may add in the future, the logic is not difficult. Creating the feature so that the UX reacts live to new sidebars being added to the page is what holds us back. So yes, the idea is on the cards but there is no milestone and date on it yet.

~ Marc
