### ISSUE TITLE
Example plugin

### ISSUE THREAD

**Issue by AleksandarPredic** [Obox/layerswp#90]
Hello,

I noticed that example plugin is mentioned in tutorial http://docs.layerswp.com/plugin-creation-guide/. 

"Starting with a file framework like the one below, or downloading our example plugin should help simplify the process."

Where can I download it? I can't find a link, please provide one.

Thanks

**Comment by marcperel** [comment]
Hey Aleksandar,

We will certainly be creating one which encompasses how to extend the Customizer, how to add a Widget and how to add custom templates.

~ Marc
