### ISSUE TITLE
Need a comma to be localized?

### ISSUE THREAD

**Issue by tmconnect** [Obox/layerswp#91]
Because I'm working on the German localization again, I discovered that in `core/helpers/post.php` on line 58 and again on line 77 a single comma in the implode function is intended for translation.

Is that really necessary?

The comma is intend to separate categories or tags on the front end. A normal WP user doesn't know where to change this, if he wants to change this into a dash or something else. A developer suspects this is not in the translation, but rather in the code.

**Comment by marcperel** [comment]
Thanks Thomas, that's an oversight, we'll check it out and fix it  in the next release.
