### ISSUE TITLE
Is there any way to use only the content builder?!

### ISSUE THREAD

**Issue by raphaelkross** [Obox/layerswp#97]
Hi guys!

I have a question, is there a way to use only the builder in my themes, instead using all the other parts of the Layer, can we use only the builder part?!

Any specific instructions on how to do it?! Is it even allowed?!

Kind Regards.

**Comment by TiagoGoddard** [comment]
As the Layers is a theme, i don't think you can.

Maybe if you make your theme a child theme from Layers, and make the changes you need for your theme to work, it might.

**Comment by raphaelkross** [comment]
Yes, I noticed it - but for example.

If I need to use only the Customizer/Builder capabilities from Layers without using it as a parent theme, am I allowed to do it?! Any easy way to do it?!

Thank you guys!

**Comment by marcperel** [comment]
Hey @raphaelkross 

All the Layers functionality is built into the theme, so you'd need to use the Layers parent theme to do so.

~ Marc
