### ISSUE TITLE
Support for Templating Engine

### ISSUE THREAD

**Issue by omarabid** [Obox/layerswp#98]
If I want to structure a very complex widget, I'll probably go for an MVC structure + Twig. I know that PHP is a templating language too, but every developer/team make a choice.

The problem is that the "Layers_Form_Elements" forces you to use PHP as a templating language.

It echoes the HTML instead of returning it, or it should at least give the option to return it.

Looking for your advice here.

**Comment by vailjoy** [comment]
Hi there,
I will let Marc provide a more detailed response, but in general Layers needs to stay as simple and newb-friendly as possible. Before we would build in something like Twig support, we would need to be sure it has a broad enough application that a high number of devs will utilise. You may be interested in the Twig or Timber plugins, either of which could be wrapped into your extension.
https://wordpress.org/plugins/tags/template-engine

**Comment by omarabid** [comment]
@vailjoy I didn't suggest that Layers support Twig. I don't think it should ever "support" a templating library in a sense that it has special code for that library or templating in general.

**Comment by marcperel** [comment]
Hi @omarabid,

I may understand what you are referring to, are you referring to implementing our classes in such a way that it is easier for you to edit the output of forms, design bar items etc.

**Comment by omarabid** [comment]
@marcperel Exactly. If the HTML code is returned, instead of printed directly, it'll make it easier for filtering and tinkering with it.
